### ISSUE TITLE
Alpaka min/max vs CUDA min/max

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/alpaka#1009]
The following code compiles fine with nvcc:
```
constexpr auto limit = 10;
__device__ int f(int a) {
    return min(limit, a);
}
```
Now porting this alpaka gives:
```
constexpr auto limit = 10;
template<typename AlpakaAcc>
ALPAKA_FN_ACC int f(const Acc& acc, int a) {
    return alpaka::math::min(acc, limit, a);
}
```
The second example does no longer compile with the following error message:
error: identifier "limit" is undefined in device code

The reason is that, alpaka captures its arguments by const reference and therefore ODR-uses `limit` which hence requires a definition, whereas the CUDA builtins capture by value.

For reproducing: https://cuda.godbolt.org/z/b6SiNV
As a sidenote: `std::min()` behaves like alpaka and has the same problem.

Is there a strong reason for the parameters of min/max to be declared as const references? Otherwise we could improve the usability/portability here.

**Comment by BenjaminW3** [comment]
I do not see a strong reason to capture by reference. It would also be ok to capture by value for those methods.

**Comment by bernhardmgruber** [comment]
Btw, adding a unary plus in front of the constant makes it compile, because the reference then binds to the created temporay instead of the constant:
```
return alpaka::math::min(acc, +limit, a);
```
Weird workaround.

**Comment by sbastrakov** [comment]
Out of curiosity, does putting `constexpr auto deviceLimit= limit;` and passing this new variable to the `min()` make it work?

**Comment by psychocoderHPC** [comment]
Note: Somewhere in the CUDA specs there is a link how `constexpr` and references work together. If I remember correctly they wrote that they do not allow to capture a constexpr by reference. The CUDA devs argued that this is how it is described in the standard. I try to find the reference but it will take some time.
