### ISSUE TITLE
Considerations for C++17-only release

### ISSUE THREAD

**Issue by BenjaminW3** [alpaka-group/alpaka#1011]
CUDA 11 will add support for C++17. This would allow us to require C++17 as minimum version for alpaka which would allow us to simplify some internals.

As an intermediate step we should create a release that still supports c++14 but already adds support for CUDA 11 and c++17.

In a follow up release we could drop support for the following dependencies because they miss full c++17 support:
* CUDA 9.0, 9.1, 9.2, 10.0, 10.1, 10.2
* clang 4
* gcc 5 and 6

**Comment by psychocoderHPC** [comment]
Note: we need to stay with CUDA 10.1 requirements as long as the most used HPC systems using CUDA 10.1.
A stable release with C++14 will help but also increase the required work because we need to create back-ports and work on multible alpaka versions at the same time.

**Comment by bernhardmgruber** [comment]
As discussed in a VC: I think compiler/toolchain updates are governed by what kinds of (HPC-) systems we want to support. So if all of these systems have upgraded to a new compiler/toolchain, we can upgrade as well. @sbastrakov pointed me to a list of systems where picongpu has been run, so we have a (partially outdated) sample of these supported systems.

I think we should have a table of supported systems and their compiler/toolchain versions and then regularly (like every month) check if those have changed. This will allow us to know when the time for an update has come.

**Comment by ax3l** [comment]
Fantastic ideas, maybe we could do a simple wiki page in the Alpaka repo?

**Comment by bernhardmgruber** [comment]
We mentioned this topic again in the last alpaka VC and decided to put together a list of arguments for and against a transition to C++17 after the next release (alpaka 0.8 will ship in C++14, then upgrade).

Arguments for are primarily big improvements in programmer convenience. There are especially new metaprogramming features (e.g. `if constexpr`, fold expression, new type traits) that would help.
Arguments against are higher requirements on compilers and tools. This especially concerns CUDA/nvcc, where we would need to drop support for CUDA 10 with the next but one release (Spring 2022).

**Comment by bernhardmgruber** [comment]
The upgrade to C++17 has further implications. Since we need to require at least CUDA 11.0 to support C++17, it seems we can no longer support clang as CUDA compiler below clang-12, as clang-11 and below fail to detect a CUDA 11.0 SDK. See https://github.com/alpaka-group/alpaka/pull/1466#issuecomment-972709222. Or at least I could not find a way yet to make clang-11 and below work with CUDA SDK 11.0.

**Comment by psychocoderHPC** [comment]
I can confirm that CUDA 11.0 is not working with clang++-9 and clang++-10.
I can use PIConGPU with clang++-11 together with CUDA 11.0.
