### ISSUE TITLE
Missing doc for `mem::buf::alloc`'s `TIdx`

### ISSUE THREAD

**Issue by Axel-Naumann** [alpaka-group/alpaka#1026]
Hi,

`TIdx`, the second template parameter for `mem::buf::alloc` https://github.com/alpaka-group/alpaka/blob/develop/include/alpaka/mem/buf/Traits.hpp#L116 isn't documented. Could you fix that, please? It's a function that seems to be used in tutorials - thus fairly visible. Thanks!

Cheers, Axel.

**Comment by sbastrakov** [comment]
Hello @Axel-Naumann , thanks for pointing out! It is indeed an important one. Just made a small PR #1027 to add the missing description.
