### ISSUE TITLE
Push to fork result in workflow errors

### ISSUE THREAD

**Issue by bertwesarg** [alpaka-group/alpaka#1032]
Hi,

I have a fork of Alpaka and just pushed an update since a long time. But now I get workflow error messages:

```
Run failed for develop (0af7a5f)

Repository: mephisto-hpc/alpaka
Workflow: Publish documentation to gh-pages
Duration: 1 minute and 3.0 seconds
Finished: 2020-06-08 07:15:02 UTC

View results: https://github.com/mephisto-hpc/alpaka/actions/runs/128297861

Jobs:
  * gh-pages failed (1 annotation)

```

This is rather surprising and also very unpleasant. Is there anything the upstream repository can do to prevent these messages, or can the fork do something?

Thanks

**Comment by sbastrakov** [comment]
Hello @bertwesarg . I agree this looks annoying, also with that "helpful" error message. Unfortunately, I do not have an idea what went wrong. Perhaps @BenjaminW3 does?

**Comment by sbastrakov** [comment]
It seems we have the same problem with our main fork as well #1036

**Comment by bertwesarg** [comment]
I got this error per mail

**Comment by SimeonEhrig** [comment]
I'm working on the problem. At the moment, I create a Issue, which explains what is going wrong.

**Comment by SimeonEhrig** [comment]
@bertwesarg 
The is issue is finish.

**Comment by BenjaminW3** [comment]
This should be solved now. Please reopen if it did not work.
