### ISSUE TITLE
doxygen build failes

### ISSUE THREAD

**Issue by SimeonEhrig** [alpaka-group/alpaka#1037]
# Problem

The GitHub `gh-pages` is failing, which updates the doxygen documentation. It was mentioned in #1032. I think the reason is the new Sphinx Doc documentation.

# Background

At the moment, the Sphinx Doc and the doxygen documentation are built and published separately.
- **Sphinx Doc**: is build by the readthedocs builder and published on https://alpaka.readthedocs.io
- **Doxygen API**: is build by a GitHub action job and published on https://alpaka-group.github.io

# Reason

The doxygen api should be integrated or linked in the sphinx doc. During the integration/linking process something was going wrong an the process was not finished. I believe, it was planed to integrate the doxygen build in the sphinx doc but at the moment, the sphinx doc links to https://alpaka-group.github.io. The problem is, that the output type of doxygen is changed from `html` to `xml`, which I think can be better integrated in the Sphinx doc. But the GitHub workflow want to push the `html` output, so it fails because there is not `html` support.

# Solutions

1. **Finish the integration in Sphinx Doc:** Use the .xml files generated by the readthedocs, change the doxygen link from https://alpaka-group.github.io to a internal link (https://alpaka.readthedocs.io) and delete the GitHub workflow. [1]
2. **Keep the GitHub workflow:** Change the doxygen output back to `html`, keep the link in the sphinx doc and the delete everything in the sphinx doc build recipe, which is related to the doxygen build.

[1] A possible solution was posted by @ax3l : https://github.com/alpaka-group/alpaka/pull/990#issuecomment-636128010

@psychocoderHPC @BenjaminW3 @sbastrakov 
What do you think, is the better solution?

**Comment by sbastrakov** [comment]
Thanks for investigating and providing the options @SimeonEhrig ! I do not have a particular preference, so perhaps would prefer the way that gets this issue resolved or worked around quickly. Currently because of this issue CI considers all branches failing.

**Comment by BenjaminW3** [comment]
I would prefer 2. because it will fix the immediate problem. We can still enhance the sphinx doc later.

**Comment by SimeonEhrig** [comment]
> I would prefer 2. because it will fix the immediate problem. We can still enhance the sphinx doc later.

Okay, I use this solution.

Just for information. I found out, that the doxygen integration in Sphinx doc has another target than expected. Instead integrating the whole documentation like the normal doxygen build, it allows to reference certain classes, functions and so one in the documentation. So, for both solutions, it is necessary to build the `html` and `xml` output. The `html` is for the classic webpage and the `xml` for the references in Sphinx doc.

**Comment by SimeonEhrig** [comment]
@BenjaminW3 
I tested a little bit in my fork to find out, what is the problem: https://github.com/SimeonEhrig/alpaka/commit/2a9586b34c0f15a9bcec57e7637263b0aa4e61e4
The `git push` fails. When I try to update my forked `gh-pages` branch, I get the following error:

```bash
$ git push simeon gh-pages 
To git@github.com:SimeonEhrig/alpaka.git
 ! [rejected]        gh-pages -> gh-pages (non-fast-forward)
error: failed to push some refs to 'git@github.com:SimeonEhrig/alpaka.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
``` 

Maybe rebasing the `gh-pages` branch solves the problem.

**Comment by BenjaminW3** [comment]
The fix seems to have worked

**Comment by psychocoderHPC** [comment]
I fixed the hooks for readthedocs last Freiday all is working now.
