### ISSUE TITLE
Suggestion: get static shared memory variables by reference instead of forwarding reference?

### ISSUE THREAD

**Issue by sbastrakov** [alpaka-group/alpaka#1053]
Edit: this concerns not alpaka interface, but how we use it in examples and tests.

So far we use syntax like [that](https://github.com/alpaka-group/alpaka/blob/08710cb752bfec348ba785fd5518aeb7d785c80d/test/unit/block/shared/src/BlockSharedMemSt.cpp#L39) everywhere.

I think in this case there is no advantage of forwarding reference here over a normal one. And if so I suggest switching to the normal one for less confusion.

Edit: and for dynamic shared memory, perhaps just a pointer is enough, and not a forwarding reference to a pointer like [here](https://github.com/alpaka-group/alpaka/blob/08710cb752bfec348ba785fd5518aeb7d785c80d/test/unit/block/shared/src/BlockSharedMemDyn.cpp#L32).

**Comment by sbastrakov** [comment]
@psychocoderHPC @BenjaminW3 ping, do you see any problem with having normal references instead of forwarding ones here?

**Comment by psychocoderHPC** [comment]
> Edit: and for dynamic shared memory, perhaps just a pointer is enough, and not a forwarding reference to a pointer like here.

I would not change the interface to return a pointer. If we will change it I suggest to return a container where you can get slices of memory from. The reason is this would more fit with the required interfaces for SYCL where we try to avoid pointer at all.

**Comment by BenjaminW3** [comment]
Using `auto &` in the tests should make it easier to understand which is better. You can change it if you like.
