### ISSUE TITLE
RelWithDebInfo & CUDA -G

### ISSUE THREAD

**Issue by ax3l** [alpaka-group/alpaka#1060]
The CMake option `RelWithDebInfo` is runtime performance neutral and enables all optimizations. On Linux, debug symbols are stored in a separate part of the binary and with MSVC in separate files.

Therefore, we should not add `-G` debug with `RelWithDebInfo` as this turns all device optimizations off:
https://github.com/alpaka-group/alpaka/blob/0.5.0/cmake/alpakaCommon.cmake#L514

Without checking, this is probably similar with HIP:
https://github.com/alpaka-group/alpaka/blob/0.5.0/cmake/alpakaCommon.cmake#L642

References:
- https://cmake.org/cmake/help/v3.17/variable/CMAKE_BUILD_TYPE.html
- https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#options-for-altering-compiler-linker-behavior-generate-line-info
- details: https://reviews.llvm.org/D55056#1314996 (only with MSVC a "problem", but we inline everything we want to anyway;  https://www.brianlheim.com/2018/04/09/cmake-cheat-sheet.html#build-types)

**Comment by j-stephan** [comment]
Which flags does CMake's first class CUDA support use? Maybe we should just mirror those.

**Comment by ax3l** [comment]
As far as I can see it, CMake does not add `-G` in debug mode for CUDA device code. But it seems to generally not manipulate the device flags depending on the build type much (yet), which could just be originated in the relatively recent addition of it.
