### ISSUE TITLE
Azure Pipelines

### ISSUE THREAD

**Issue by ax3l** [alpaka-group/alpaka#1068]
I would recommend to run some of the CI tests on https://dev.azure.com

It's essentially the same hardware as GH Actions but gives you an extra 10 parallel jobs. This should lower the overall CI time for a pull request.

Example:
- https://github.com/openPMD/openPMD-api/tree/azure_install
- https://dev.azure.com/axelhuebl/openPMD-api/_build/results?buildId=415&view=results
- https://github.com/marketplace/azure-pipelines

**Comment by SimeonEhrig** [comment]
Does the azure pipeline use the same scripts as the GitHub actions? We also plan to use GitLab CI for runtime testing on GPU hardware. So we should keep the amount of CI scripts as smal as possible so we don't have to spend too much time managing the CI.

**Comment by ax3l** [comment]
Slightly different base yaml file, as linked. But the Alpaka CI is based on bash scripts that can be executed on various CI platforms, so it's not too much to set up besides adding the compile matrix entries.

**Comment by SimeonEhrig** [comment]
Okay, that's not so cool, because then we spread the test configuration over two files. In my opinion, we shouldn't spend time on a 3rd CI, since the integration of GitLab CI is already planned (see #967 ), and then it should be easy to add additional resources.

**Comment by ax3l** [comment]
Sounds good, understand. Just want to mention the option :)
