### ISSUE TITLE
Merging options: create a merge commit or rebase and merge?

### ISSUE THREAD

**Issue by sbastrakov** [alpaka-group/alpaka#1103]
Currently PIConGPU does "create a merge commit", while alpaka has it disabled and uses "rebase and merge", . @BenjaminW3 what is the reason for it? Not saying we should change, just not being aware of the reasoning, pros and cons, etc..

**Comment by BenjaminW3** [comment]
You can find opinions about this topic everywhere.

My opinion is that rebasing and ~fast-forward~ merging makes the history much simpler to understand. I do not see any disadvantages of this approach in contrast to merging without prior rebase.

**Comment by bertwesarg** [comment]
I only see one, its for multi-commit merge requests. In this case I consider a merge commit of more value. First you could potentially include the description of the merge request into the history directly, instead only to have it by a link to GutHub. Tough this is not very well supported by GitHub. The second is, that the commits of the merge commit are still recognized as a group. And _good MRs have multiple commits and the form a sensible groups. Though these multi-commit MRs still should be rebased to the tip, before the merge commit is created. Just my 2ct.

**Comment by bertwesarg** [comment]
BTW, single commits should always be rebase and fast-forward

**Comment by j-stephan** [comment]
I agree with @BenjaminW3 on this topic (and also the others, see the discussion linked above my comment). If there is further need to discuss this please refer to the linked discussion. Closing this as duplicate.
