### ISSUE TITLE
Some icc versions (reportedly) still cause ICE

### ISSUE THREAD

**Issue by sbastrakov** [alpaka-group/alpaka#1134]
After the efforts to fix #995 were merged, we've got an email report that it solved the issue for ICC 2020.1 and 2019.2. But on versions 2018.3, 2018.1, 2017.8 there are still ICEs. However, we do not have a suitable environment on Hemera to investigate it.

This already stayed in an email conversation for too long, making an issue so that it's no longer forgotten.

**Comment by j-stephan** [comment]
Do we still officially support these old versions of a legacy compiler?

**Comment by sbastrakov** [comment]
I do not know. But i think it is reasonable to close this, and open a new issue if there is a report for current alpaka version.
