### ISSUE TITLE
Add CUDA 11 and MSVC tests to CI

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/alpaka#1138]
CUDA toolkit 11 for Windows was released a while back and so far CUDA 11 is just tested with Linux targets. We should add tests with Windows as well.

**Comment by psychocoderHPC** [comment]
@BenjaminW3 is integrating CUdA 11 for windows in #1086 but there are some issues.

**Comment by sbastrakov** [comment]
#1086 was just merged.
