### ISSUE TITLE
Create CHANGELOG.md

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/alpaka#1167]
Create a file CHANGELOG.md that lists the changes introduced in each version of alpaka. It should also list the breaking changes currently on the develop branch.

**Comment by sbastrakov** [comment]
Thanks @bernhardmgruber  for making the changelog and issue for it!
I am wondering if namespace renamings that were put to the log are also reflected in the readthedocs, e.g. in the cheatsheet there? In case something was forgotten, however the changelog allows restoring it.

**Comment by bernhardmgruber** [comment]
You are absolutely right, I forgot the documentation and cheatsheet! I created #1175 for this.

**Comment by bernhardmgruber** [comment]
Since the CHANGELOG.md was added, this issue is resolved.
