### ISSUE TITLE
Release 0.6.0

### ISSUE THREAD

**Issue by psychocoderHPC** [alpaka-group/alpaka#1178]
I pulled out a first release candidate for 0.6.0 https://github.com/alpaka-group/alpaka/tree/release-0.6.0-rc1
This branch is feature freezed and we will pull in only bugfixes

I opened a new project to not forget any tasks: https://github.com/alpaka-group/alpaka/projects/10

I like to perform before the release integration tests with cupla and PIConGPU.

@alpaka-group/alpaka-maintainers

**Comment by psychocoderHPC** [comment]
The scope for the release should be begin to mid of November 2020.

**Comment by psychocoderHPC** [comment]
@alpaka-group/alpaka-maintainers Feel free to grep the task to update the changelog with missing changes.

**Comment by bernhardmgruber** [comment]
I remember you stating that you are kind of waiting for the namespace refactorings to finish before creating the next alpaka release. I still would like to land 2 refactorings, as commented here: https://github.com/alpaka-group/alpaka/issues/1034#issuecomment-713473167

Can I still get these into the release if I finish them this week?

**Comment by psychocoderHPC** [comment]
https://github.com/alpaka-group/alpaka/tree/release-0.6.0-rc2 is now including all changes of the development branch until 1a06a20eb7be86317d67ffb3b197cbd0245541b5.

I will delete rc1

**Comment by psychocoderHPC** [comment]
https://github.com/alpaka-group/alpaka/tree/release-0.6.0-rc3 is now available. All changes from the dev branch until https://github.com/alpaka-group/alpaka/tree/95973a5b2f20b6fc3796318763687e95c9fce219 are available.

IMO we should fix #1205 and pull the changes also into release 0.6.0, this is a tiny fix with big effects.

**Comment by psychocoderHPC** [comment]
The hopefully last release candidate is out: https://github.com/alpaka-group/alpaka/tree/release-0.6.0-rc4
The release candidate is providing the feature to control the scheduling strategy for OMP #1223

**Comment by BenjaminW3** [comment]
Is this done now? As well as the 0.6.0 release?

**Comment by psychocoderHPC** [comment]
> Is this done now? As well as the 0.6.0 release?

Yes the release 0.6.0 is available https://github.com/alpaka-group/alpaka/releases/tag/0.6.0
