### ISSUE TITLE
clangFormat broke indetation of complex compile-time guards

### ISSUE THREAD

**Issue by jkelling** [alpaka-group/alpaka#1211]
Here:
https://github.com/alpaka-group/alpaka/blob/474412ec54b43e95bb2de7039b1b4f53a744b5f3/test/common/include/alpaka/test/acc/TestAccs.hpp#L89
and here:
https://github.com/alpaka-group/alpaka/blob/474412ec54b43e95bb2de7039b1b4f53a744b5f3/test/common/include/alpaka/test/acc/TestAccs.hpp#L109

**Comment by bernhardmgruber** [comment]
Firstly: clang-format is not perfect. But manual formatting is worse. And perfect is the enemy of the good ;)
Secondly: that whole `#if` directive is horrible IMO and probably needs a simplification anyway. E.g. we could split out all tests where OpenMP5 or OpenACC do not work into a separate macro and then use this macro inside the `#if`.

**Comment by j-stephan** [comment]
I think clang-format may have uncovered a bug here. `A && B || C` is evaluated as `(A && B) || C`. In the example here:

```c++
(BOOST_COMP_GNUC < BOOST_VERSION_NUMBER(11, 0, 0)) && defined(TEST_UNIT_BLOCK_SHARED) || defined(TEST_UNIT_BLOCK_SYNC)
```
This will turn into (simplified the Boost stuff):

```c++
(BOOST_VERSION_CHECK && defined(TEST_UNIT_BLOCK_SHARED)) || defined(TEST_UNIT_BLOCK_SYNC)
```

Is this the actual intention of the macro?

**Comment by jkelling** [comment]
There is indeed a pair of parens missing. Still, the clang format did also not propertly reflect the wrong logic.
