### ISSUE TITLE
Publishing the doxygen doc is brocken

### ISSUE THREAD

**Issue by SimeonEhrig** [alpaka-group/alpaka#1221]
Since commit 7ba4c30a4947b97169b3216436ca23e2db2f5935, the CI cannot publish a new version of the doxygen doc.

**Comment by BenjaminW3** [comment]
@psychocoderHPC Could you please take a look at what broke there?

**Comment by SimeonEhrig** [comment]
@psychocoderHPC I saw, you tried to fix this issue: https://github.com/alpaka-group/alpaka/pull/1229
But it is still broken: https://github.com/alpaka-group/alpaka/runs/1542136786
I think, there is a new bug.

**Comment by psychocoderHPC** [comment]
I removed this issue from the 0.6.0 release. Our gh-page is always showing the development of branch documentation. 
I do not know why it is still broken.

**Comment by psychocoderHPC** [comment]
I opened a PR to remove changes from the PR @SimeonEhrig pointed to. I hope this will solve the issue.
