### ISSUE TITLE
Discussion: add alpaka function to abort a kernel?

### ISSUE THREAD

**Issue by sbastrakov** [alpaka-group/alpaka#1233]
There seems to be no unified way to hard-stop a kernel, while in some (rare I assume) cases that would be beneficial. This came up from @pordyna debugging [his PIConGPU feature](https://github.com/ComputationalRadiationPhysics/picongpu/pull/3416) that has to allocate memory inside a kernel and can run out of it. And then we realized there seems to be no single way to abort that works on all alpaka-supported variety. I assume there are also restrictions from OpenMP what kind of things are allowed inside parallel regions. So it may be yet another utility to abstract away with alpaka.

Searching through alpaka, we now only disable [HIP macro for abort()](https://github.com/alpaka-group/alpaka/blob/ec56e2e3f51dbe394e6a394a2a9b952f3c2bf066/include/alpaka/core/BoostPredef.hpp#L27-L28).

What are your thoughts?

**Comment by bernhardmgruber** [comment]
There are a lot of questions if we would implement such a feature:
* Does it abort only the kernel or the entire program (thus aborting the host code as well)?

If it just aborts the kernel:
* How to implement this on CPU backends? I could envision throwing a "special" exception and catching it inside the backend. Or `setjump`/`longjump`.
* Will stack unwinding occur and destructors are run?
* Will other CPU worker threads continue or also abort? If they should also abort as well, we need to communicate from the aborting thread to the worker threads. This is overhead.
* How fast does this abort guarantee kernel termination? AFASP? Or can the kernel (other threads) still spin for a while?

If it also aborts the host program:
* How do we exit? `std::abort`? `std::exit`? `std::terminate`? `std::quick_exit`? :D
* Will stack unwinding occur and destructors are run?

**Comment by j-stephan** [comment]
Is there a real-world use case that doesn't involve debugging? I don't really see the need for a *portable* `abort` function.

**Comment by bernhardmgruber** [comment]
`assert` also seems to be an option btw. That will halt the program on CPUs and abort a CUDA kernel with throwing a `cudaErrorAssert` on the host. If we let the exception propagate up to `main` that will also terminate.

**Comment by j-stephan** [comment]
@sbastrakov Do you (still?) think we need this?

**Comment by sbastrakov** [comment]
Probably not, I'll close tge issue
