### ISSUE TITLE
Support for ICX/ICPX in CI

### ISSUE THREAD

**Issue by psychocoderHPC** [alpaka-group/alpaka#1238]
@ax3l suggested adding new Intel ICX/ICPX compiler to our CI.

see: https://github.com/alpaka-group/alpaka/issues/995#issuecomment-758120292

**Comment by j-stephan** [comment]
Is this different from the current ICPC CI job?

**Comment by j-stephan** [comment]
To answer my own question:

* `icc` and `icpc` refer to the classic Intel compiler that is slowly phased out.
* `icx` and `icpx` refer to the new clang-based Intel compiler which is also known as `dpcpp` to the SYCL crowd.

We should decide on how long we still want to support the classic Intel toolchain.
