### ISSUE TITLE
Pitch missing in bufferCopy example

### ISSUE THREAD

**Issue by SimeonEhrig** [alpaka-group/alpaka#1240]
I think the pitch is not respected if the data is initialized on the host: https://github.com/alpaka-group/alpaka/blob/ca51f5093f43a6d22ab0561b2d47155444c218f5/example/bufferCopy/src/bufferCopy.cpp#L229-L232

The kernels calculate the pitch in the address.

**Comment by bernhardmgruber** [comment]
This will be resoved with: https://github.com/alpaka-group/alpaka/pull/1249

**Comment by j-stephan** [comment]
We need to revisit this once accessors no longer live inside `alpaka::experimental`.

**Comment by psychocoderHPC** [comment]
> We need to revisit this once accessors no longer live inside `alpaka::experimental`.

Where do they live now? Are they not experimental anymore?

**Comment by j-stephan** [comment]
They currently live in `alpaka::experimental`. One day they will (hopefully) be put into `alpaka` like everything else.

**Comment by bernhardmgruber** [comment]
This was fixed when the example was rewritten with `std::mdspan`: #1788
