### ISSUE TITLE
Make CMake options feel more like compiler options

### ISSUE THREAD

**Issue by sbastrakov** [alpaka-group/alpaka#1286]
We discussed it on a VC before and after #1285 . There are two directions to improve alpaka CMake options concerning compiler flags:

- Avoid enabling options influencing user code by defaut. For fast math, #1285 is a fix, but there may be more of this kind, we need to check. The reason is that a user may not expect alpaka to hard-set it by default, and therefore not disable it when needed.
- Generally try to go to the ON / OFF / AUTO system, where a certain aspect can be hard-enabled, hard-disabled, or left by default. Again, how compiler flags are mostly operating.

**Comment by bernhardmgruber** [comment]
Is `AUTO` the right term then, if CMake does not specify anything and just lets it to the compiler's default? Wouldn't `DEFAULT` be a more fitting term?

**Comment by sbastrakov** [comment]
Yes, maybe `DEFAULT` would be more fitting. I've put `AUTO` since it's what we discussed.

**Comment by psychocoderHPC** [comment]
I am working on this issue. I am fine with replacing `AUTO` with `DEFAULT`. I also thought yesterday about the naming.

**Comment by j-stephan** [comment]
Closed by #1289.
