### ISSUE TITLE
Intel compiler version 20 bug

### ISSUE THREAD

**Issue by sbastrakov** [alpaka-group/alpaka#1288]
As discussed on the VC, making an issue to document and so that we could reference it in the code briefly. While working on #1279 I've faced an issue with internal compiler error when using Intel compiler version 20. It seems to not appear for earlier versions. The behavior we observed exactly matches [this bug already reported to Intel](https://community.intel.com/t5/Intel-C-Compiler/compiler-2020-1-217-internal-error-assertion-failed-find-assoc/m-p/1227009#M37871).

@psychocoderHPC found a workaround for that piece of code and shared it in that discussion:
```cpp
template < typename F>
void foo(const F& f)
{
  #pragma omp parallel for schedule(dynamic) collapse(2) 
  for (unsigned int v = 0; v < 0; ++v){
   for (unsigned int t = 0; t < 0; ++t){
      auto x = [&f]( const auto & i){ f(i);};
      x(0);
   }
  }
}

void f() {
 foo( [](const auto &indices_2) {} );
}
```

**Comment by psychocoderHPC** [comment]
Note I reproduced the bug with `Intel(R) C++ Intel(R) 64 Compiler for applications running on Intel(R) 64, Version 19.1.3.304`  too, see community.intel.com/t5/Intel-C-Compiler/compiler-2020-1-217-internal-error-assertion-failed-find-assoc/m-p/1273228#M38624

**Comment by j-stephan** [comment]
This is still present in the current version of icpc:

```
$ icpc --version
icpc (ICC) 2021.5.0 20211109
Copyright (C) 1985-2021 Intel Corporation.  All rights reserved.

$ icpc test2.cpp -c -O3 -qopenmp -std=c++17
test2.cpp(9): internal error: assertion failed: find_assoc_pragma: pragma not found (il.c, line 25743 in find_assoc_pragma)

              f(0);
              ^

compilation aborted for test2.cpp (code 4)
```

Is the work-around part of alpaka? If so, can we close this issue?
