### ISSUE TITLE
CMake option for relocatable device code

### ISSUE THREAD

**Issue by psychocoderHPC** [alpaka-group/alpaka#1292]
In #1289 `ALPAKA_CUDA_NVCC_SEPARABLE_COMPILATION` was removed because it was only a renaming of `CUDA_SEPARABLE_COMPILATION`.
Today we found out that this feature is supported for clang too, so we can provide this feature for CUDA (with clang and nvcc) and HIP (hipcc).

Task: add cmake option `ALPAKA_RELOCATABLE_DEVICE_CODE`

Clang supports the following flags:

- <= clang6: flag not supported
- clang-7: `-fcuda-rdc`
- clang-8 `-fgpu-rdc` (`-fcuda-rdc` is no longer available)
- clang-11 and newer `-fgpu-rdc` and `-fno-gpu-rdc`

**ATTENTION**: for clang-CUDA see the requirements https://github.com/alpaka-group/alpaka/issues/1292#issuecomment-823097652

**Comment by SimeonEhrig** [comment]
~~I'm not sure, if it is working with Clang, because I fond this: https://cmake.org/cmake/help/latest/release/3.18.html#id6
Maybe it is fixed in a new version.~~

It is supported with CMake 3.19 https://cmake.org/cmake/help/latest/release/3.19.html#id12

**Comment by psychocoderHPC** [comment]
Currently we do not use native CMake CUDA support, therefore we will add this flag directly to the corresponding compiler.

**Comment by SimeonEhrig** [comment]
Yes, I forgot it.

**Comment by BenjaminW3** [comment]
Someone could try to get #1146 working for older clang compilers ;-)

**Comment by psychocoderHPC** [comment]
> Someone could try to get #1146 working for older clang compilers ;-)

Would be nice but nobody has time to look into it. :-(

**Comment by SimeonEhrig** [comment]
> Someone could try to get #1146 working for older clang compilers ;-)

What do you mean, with older compiler? Clang older than version 7? At the moment, I try to find out, what is the status of the Separated Compilation support of Clang, because I can compile the [official example](https://developer.nvidia.com/blog/separate-compilation-linking-cuda-device-code/) but I have problems to compile an example with `extern __constant__ memory[]`, which works in `nvcc`.

This blog post also mentioned, that the feature is relative new: https://developer.nvidia.com/blog/separate-compilation-linking-cuda-device-code/

**Comment by psychocoderHPC** [comment]
Clang-CUDA requires linking with `nvcc` if we use realicated compile: see https://github.com/root-project/cling/issues/396#issuecomment-822335599

**Comment by SimeonEhrig** [comment]
We found a bug in Clang 12 and maybe older version, which avoids to use CUDA separable compiling: https://github.com/root-project/cling/issues/396#issuecomment-831118957

This bug is fixed in Clang 13.

**Comment by j-stephan** [comment]
So what is the best way here? Can we work around this bug or do we have to wait until we drop support for LLVM < 13?

**Comment by SimeonEhrig** [comment]
I discussed a solution for Cling (basis on clang 9) with developer of the feature a while ago. He means, a workaround would be hard. I would suggest, that we catch this in the CMake and throw an error if `CMAKE_CUDA_SEPARABLE_COMPILATION` is activated together with <= Clang 12.0 and it is fine.

**Comment by j-stephan** [comment]
Okay. This shouldn't be too hard to integrate so it can still land in 0.8.

**Comment by j-stephan** [comment]
@SimeonEhrig If I understand the original issue at cling correctly, we need to use clang 13 for compilation and nvcc as linker to make this work with clang. Is this correct?
