### ISSUE TITLE
CI: update CUDA install (Linux)

### ISSUE THREAD

**Issue by psychocoderHPC** [alpaka-group/alpaka#1299]
We should update the way how we install CUDA in our CI. 
We should use the `ppa` links https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&=Ubuntu&target_version=18.04&target_type=deb_network 
and `apt-get` instead of pulling the full `dep` package.
This would hopefully save download time.

**Comment by j-stephan** [comment]
Do we still want this?

**Comment by SimeonEhrig** [comment]
The fallback, if an alpaka-container with a specific CUDA version is not available is to use a base container and install the CUDA SDK each time in the test job. But I think, we don't need to optimize this "workaround" anymore.

**Comment by j-stephan** [comment]
Closing this issue. Feel free to reopen if you feel this is still an issue.
