### ISSUE TITLE
Add Clang 12 as CUDA compiler to the CI

### ISSUE THREAD

**Issue by SimeonEhrig** [alpaka-group/alpaka#1304]
After removing old Clang from the CI in the PR #1300 , we should also add the latest versions of Clang/LLVM.

Since Clang/LLVM 11, Clang is forward compatible to new CUDA versions: https://github.com/llvm/llvm-project/commit/12fefeef203ab4ef52d19bcdbd4180608a4deae1
So we should change [this line](https://github.com/alpaka-group/alpaka/blob/f428bb0448cf87e27e0d0795543bd675bf2966d3/cmake/alpakaCommon.cmake#L365) in the CMake from a `FATAL_ERROR` to a `WARNING`, if the version is greater than 10.

**Comment by BenjaminW3** [comment]
I will give it a try (also as non-cuda compilers)

**Comment by j-stephan** [comment]
#1766 adds clang-14 as CUDA compiler to the CI. Once that is merged this should be next.

**Comment by bernhardmgruber** [comment]
@SimeonEhrig can you please provide a PR for that change? Thx!

**Comment by SimeonEhrig** [comment]
Clang 13 and older are disabled in this issue https://github.com/alpaka-group/alpaka/issues/1857 because they are not fully supported
