### ISSUE TITLE
Windows CI broken for CUDA builds.

### ISSUE THREAD

**Issue by j-stephan** [alpaka-group/alpaka#1331]
The GitHub actions script was updated to the most recent Visual Studio version 16.10. This breaks CUDA compilation:

https://github.com/actions/virtual-environments/issues/3485

Unfortunately I don't know enough about our CI setup to fix this. It doesn't seem simple since the old image appears to be no longer available. It would be great if one of the experts on this topic could have a look. Pinging @BenjaminW3 @SimeonEhrig @psychocoderHPC

**Comment by BenjaminW3** [comment]
As a fast workaround, we could take those builds out of the list of required builds. This would unblock merging of PRs until this is fixed.

**Comment by j-stephan** [comment]
The bug was reported to the Visual Studio team:

https://developercommunity.visualstudio.com/t/MSVC-C142930037-with-CUDA-112-occur/1437930

**Comment by j-stephan** [comment]
I have also filed a bug on NVIDIA's (non-public) bug tracker with the internal ID 3318837.

**Comment by bernhardmgruber** [comment]
I read through the MSVC bugreport and nvcc fails to compile a simple hello world. It hiccups inside the MS STL. Therefore I conclude that we cannot fix this on our side and need to disable the offending combination of compilers.

**Comment by psychocoderHPC** [comment]
I disabled the requirement for Windows CUDA 11.0/11.1 and 11.3. 
CUDA 10.2 is working and 10.1 should be easy to fix (I will do it).

**Comment by j-stephan** [comment]
NVIDIA responded. They are aware of the issue and will include a fix in the next major CUDA release.

Until then they recommend to switch to `-std=c++17` which apparently fixes the error.

**Comment by psychocoderHPC** [comment]
> NVIDIA responded. They are aware of the issue and will include a fix in the next major CUDA release.
> 
> Until then they recommend to switch to `-std=c++17` which apparently fixes the error.

Thanks for the update, I will wait for which CI tests in #1332 crash and test setting all failing windows tests to `c++17` within the same PR.

**Comment by psychocoderHPC** [comment]
#1332 is now removing the tests for MSVC+nvcc CUDA 11.0 and 11.1. 
Marking tests as not required does not help that maintainer can merge the PR, I realized such behavior already before.

**Comment by j-stephan** [comment]
Since we are moving to C++17 with 0.9 I guess this will automatically solve itself.

**Comment by bernhardmgruber** [comment]
We discovered in #1466, that also the switch to C++17 will not solve this issue.

**Comment by j-stephan** [comment]
In today's alpaka meeting there were no objections to removing CUDA 11.0 / 11.1 support for Windows.
