### ISSUE TITLE
Duplication of CUDA/HIP include checks?

### ISSUE THREAD

**Issue by sbastrakov** [alpaka-group/alpaka#1335]
While working on traits for my ongoing complex number implementation, I've noticed all math function implementation files for CUDA/HIP have [the same piece as "include-and-check"](https://github.com/alpaka-group/alpaka/blob/6861f7b31ef0725cb117d523b94fbe2c53b60b81/include/alpaka/math/abs/AbsUniformCudaHipBuiltIn.hpp#L16-L38). Maybe it is duplicated in some other files as well, but even among the math files it is present too many times. Is there a reason it is not separated into a special include file implementing just that once, and then included when needed?

**Comment by sbastrakov** [comment]
This went a bit unnoticed. Does anyone have an opinion on this matter?

**Comment by BenjaminW3** [comment]
I do not know of a reason which would prevent us from optimizing this.

**Comment by bernhardmgruber** [comment]
IMO, this obviously calls for a refactoring. Go ahead!

**Comment by psychocoderHPC** [comment]
This part should be refactored into a unified include. IMO there is no reason why it is like it is.

**Comment by sbastrakov** [comment]
Okay, I will do it
