### ISSUE TITLE
Drop HIP-nvcc support

### ISSUE THREAD

**Issue by psychocoderHPC** [alpaka-group/alpaka#1337]
I am currently testing using HIP targets for alpaka as suggested by @j-stephan https://github.com/alpaka-group/alpaka/pull/1324#issuecomment-848680830

I found out that if we like to use targets we need to use `find_package(HIP CONFIG)` else there is no target `hip::device` available.
Wenn using the normal old cmake find module the build system is using the `hipcc` wrapper while using `CONFIG` will enforce the usage of a native clang with AMD support.
I prefer to switch using the native clang and drop using `hipcc` to allow clean target usage and modern CMake for HIP.

The disadvantage when using the native `clang` is that we can not use HIP nvcc support anymore because this would require `hipcc`.

I would like to drop `HIP-nvcc` support for alpaka in the current dev (upcoming 0.8.0). 
IMO this is not a problem because we can use NVIDIA GPUs via clang(native) or nvcc(native). 
I do not see that it is useful to maintain `HIP-nvcc` anymore. HIP-nvcc is currently not tested in the CI and maybe not working anyway.

@alpaka-group/alpaka-maintainers If someone has another opinion please feel free to provide reasons to keep HIP-nvcc.

**Comment by SimeonEhrig** [comment]
I'm for dropping the support for HIP on Nvidia. It reduce our work and like @psychocoderHPC already mentioned, we don't lose any functionality and it makes no difference for the user, if they use the HIP backend with CUDA platform or the CUDA backend directly (expect that setting up HIP on a Nvidia machine is more work, than installing the CUDA SDK directly ;-) ).

**Comment by bernhardmgruber** [comment]
I am all up for moving foward and streamlining our setup. Some comments/questions:

There is nothing wrong with using `find_package` in config mode. I guess cmake comes with a find module, which is preferred, and that's why we need config mode explicitely. Does that change our minimum required CMake version?

> The disadvantage when using the native clang is that we can not use HIP nvcc support anymore because this would require hipcc.

What is HIP nvcc support? And does that matter for us?

> HIP-nvcc is currently not tested in the CI and maybe not working anyway.

If we did not promise support in the first hand,then I see no reason why we cannot drop it.

**Comment by j-stephan** [comment]
> Does that change our minimum required CMake version?

No, that has been around since (at least) CMake 3.0.

> What is HIP nvcc support? And does that matter for us?

You can use hipcc to target NVIDIA GPUs. Internally this will then delegate compilation to nvcc. I never really understood why we had support for this in alpaka since hip+nvcc requires CUDA anyway and we already had a CUDA back-end.

> If we did not promise support in the first hand,then I see no reason why we cannot drop it.

Well, we kinda did but I'm not aware of anyone explicitly using the alpaka -> HIP -> CUDA path instead of direct alpaka -> CUDA.

**Comment by bernhardmgruber** [comment]
> You can use `hipcc` to target NVIDIA GPUs. Internally this will then delegate compilation to `nvcc`. I never really understood why we had support for this in alpaka since hip+nvcc requires CUDA anyway and we already had a CUDA back-end.

Ah ok. I guess that is used for programs written just in HIP so that they can run on NVIDIA. Alpaka provides a different mechanism for that. So yeah, we can drop it.

**Comment by psychocoderHPC** [comment]
> There is nothing wrong with using `find_package` in config mode. I guess cmake comes with a find module, which is preferred, and that's why we need config mode explicitely. Does that change our minimum required CMake version?

ROCm is shipping a `find_package` module and a `cmake_config`. Depending on what you load the setup is locking differently. 
Using the find module will result in an environment where you must use `hipcc` were loading the `config` will result in an environment where you must use `clang/clang++` and you can use cmake modules `hip::device`. 

> Ah ok. I guess that is used for programs written just in HIP so that they can run on NVIDIA. Alpaka provides a different mechanism for that. So yeah, we can drop it.

Yes, if you write you use `hipMalloc(), ...` the compiler will link to `cudaMalloc()` on a NVIDIA platform. It was for alpaka yet another way to target NVIDIA GPUs and at the beginning of our development more stable than `hip`.

**Comment by ax3l** [comment]
> we need to use find_package(HIP CONFIG) else there is no target hip::device available.

actually lower-case `hip`, according to the docs:
https://rocmdocs.amd.com/en/latest/Installation_Guide/Using-CMake-with-AMD-ROCm.html#using-hip-in-cmake

Be aware of https://github.com/ROCm-Developer-Tools/HIP/pull/2280, landing in ROCm 4.4 as it seems.

**Comment by psychocoderHPC** [comment]
> > we need to use find_package(HIP CONFIG) else there is no target hip::device available.
> 
> actually lower-case `hip`, according to the docs:
> https://rocmdocs.amd.com/en/latest/Installation_Guide/Using-CMake-with-AMD-ROCm.html#using-hip-in-cmake
> 
> Be aware of [ROCm-Developer-Tools/HIP#2280](https://github.com/ROCm-Developer-Tools/HIP/pull/2280), landing in ROCm 4.4 as it seems.

I tried `find_package(hip)` and `find_package(hip CONFIG)` both is not working with ROCM 4.2.
Even if I explicit set `list(APPEND CMAKE_PREFIX_PATH /opt/rocm/hip /opt/rocm)`.

@ax3l  I saw in the issue you kinked that you provided a mini app to reproduce the multi-language issue. Do you changed anything in your environment that cmake find works? Which cmake version do you use?

**Comment by psychocoderHPC** [comment]
> > > we need to use find_package(HIP CONFIG) else there is no target hip::device available.
> > 
> > 
> > actually lower-case `hip`, according to the docs:
> > https://rocmdocs.amd.com/en/latest/Installation_Guide/Using-CMake-with-AMD-ROCm.html#using-hip-in-cmake
> > Be aware of [ROCm-Developer-Tools/HIP#2280](https://github.com/ROCm-Developer-Tools/HIP/pull/2280), landing in ROCm 4.4 as it seems.
> 
> I tried `find_package(hip)` and `find_package(hip CONFIG)` both is not working with ROCM 4.2.
> Even if I explicit set `list(APPEND CMAKE_PREFIX_PATH /opt/rocm/hip /opt/rocm)`.
> 
> @ax3l I saw in the issue you kinked that you provided a mini app to reproduce the multi-language issue. Do you changed anything in your environment that cmake find works? Which cmake version do you use?

Never mind, it was my fault I still checked `if(NOT HIP_FOUND)` instead of `if(NOT hip_FOUND)`
