### ISSUE TITLE
CI: runtime tests CUDA and HIP are missing

### ISSUE THREAD

**Issue by psychocoderHPC** [alpaka-group/alpaka#1340]
We running all our CI tests on free Github action runner. This is a very big issue because we can not tests our main target backends CUDA and HIP.
Currently, we do not perform runtime tests for CUDA and HIP, this results in hidden runtime bugs e.g. https://github.com/alpaka-group/alpaka/pull/1339

Todo: integrate HZDR CI and perform GPU runtime tests!

**Comment by j-stephan** [comment]
Is this still relevant? AFAIK we have GitLab runners that execute CUDA and HIP tests.

**Comment by j-stephan** [comment]
This was fixed by #1375, #1407, #1409 and #1520. I'm closing this now. Feel free to reopen if I was wrong.
