### ISSUE TITLE
Log10 math trait is missing?

### ISSUE THREAD

**Issue by sbastrakov** [alpaka-group/alpaka#1344]
It is not super necesary in terms of being computable with the natural log. But if the idea is to mirror the math functions in `std::` when possible, alpaka is missing this one.

**Comment by sbastrakov** [comment]
Actually quite a lot of counterparts to `std::` math functions are missing. So maybe that was not the goal in the first place (I do not know).

Basically I was going for `std::complex` interface (including functions accepting it) and tried to made alpaka's Complex (#1336) interface-compatible, and so that's how I noticed not fully 1:1 relation between alpaka's math and `std::`

**Comment by BenjaminW3** [comment]
The initial goal was to provide all CUDA math functions in alpaka and use the std lib equivalents. However, turning this around might be a valid goal, but it could lead to a larger implementation work.

**Comment by sbastrakov** [comment]
Thanks for clarifications. I think I will close this issue then, as my initial question is resolved. If we plan to make a full std-counterpart math support, that should become a separate issue with a milestone.
