### ISSUE TITLE
On CUDA/HIP only AtomicAdd and AtomicExch support floating-point types

### ISSUE THREAD

**Issue by sbastrakov** [alpaka-group/alpaka#1355]
I know CUDA only supports those, but can alpaka implement e.g. `atomicSub` for these backends as calling the native `atomicAdd` with the negative value? For now it is a bit unintuitive, and also not portable between backends, as other atomic implementations seem to work for all types.

Was discovered when I looked at a PIConGPU compile issue with @BrianMarre .

**Comment by tonydp03** [comment]
@alpaka-group/alpaka-maintainers what's your opinion on that?

**Comment by fwyzard** [comment]
The CUDA documentation for [Atomic Functions](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#atomic-functions) suggests that

> any atomic operation can be implemented based on `atomicCAS()` (Compare And Swap)

Of course for `atomicSub(addr, val)` it makes much more sense to implement it as `atomicAdd(addr, -val)`.

One could also check the implementation of (or use) the atomic operations in the CUDA std library.

**Comment by psychocoderHPC** [comment]
`atomicSub` is in CUDA only implemented for 32bit signed/unsigned value. I do not know why there is no 64bit and half prediction interface available.
IMO we should remove a implement alpaka's `atomicSub` with atomicAdd or at least for all other types than `int` and `unsigned int`
