### ISSUE TITLE
Bundle test/common/include with install.

### ISSUE THREAD

**Issue by frobnitzem** [alpaka-group/alpaka#1357]
When writing software that uses alpaka, it would be nice to use the header files from `alpaka/test`.  However, those aren't installed by alpaka.

Currently, the `CMakeLists.txt` only says this about tests:
```
if(BUILD_TESTING)
    add_subdirectory("test/")
endif()
```

Why not always add the `test/common/include` to the installed header list?
e.g. somewhere around `set(_ALPAKA_INCLUDE_DIRECTORY "${_ALPAKA_ROOT_DIR}/include")`

**Comment by BenjaminW3** [comment]
Are you interested in some specific parts of the test helpers? We may think about moving them to the public API.

**Comment by frobnitzem** [comment]
Mostly`KernelExecutionFixture.hpp`.
To support it, I ended up manually adding `TestsAccs.hpp` and `Check.hpp` to my project.  I would have put in `TestDims.hpp` and `TestIdxs.hpp`, except I only use one kind of dim and index type.

To export those, I would create a top-level `createTestFixture` interface that takes dim-size-tuples and index-type-tuples.

**Comment by BenjaminW3** [comment]
What do you want to do with it? Writing tests for your own extensions?
The KernelExecutionFixture and related types really should not be used in production code because they are very suboptimal in terms of performance (The additional return value copy, new queue for each call, ... ).
I can not imagine a use case except tests where this would be desirable. We know that there is the wish for a simpler interface to start a kernel, but it is hard to provide something that is not too use-case specific.

**Comment by frobnitzem** [comment]
Exactly - here's the test cases I have so far:
https://github.com/frobnitzem/FastParticleToolkit/tree/master/tests

**Comment by sbastrakov** [comment]
We discussed this matter on a VC today. The concencus was that the helper types for tests probably make sense to be shipped as part of alpaka public API. E.g. as `alpaka::test` namespace and the corresponding location. Then a user (including some of our own software that uses alpaka) is free to choose if they want to make use of that given there may be limitations.

**Comment by psychocoderHPC** [comment]
We also discussed that header containing `alpaka::test` should only be installed if a cmake variable is set which explicitly asked to install these files. This allows us to show a warning, the user should not assume any stability in the interfaces of this test namespace.

**Comment by SimeonEhrig** [comment]
I'm working on it.
