### ISSUE TITLE
kernel parameter should be trivially copy-able

### ISSUE THREAD

**Issue by psychocoderHPC** [alpaka-group/alpaka#1384]
During the CUDA HIP refactoring, important checks were removed

https://github.com/alpaka-group/alpaka/blob/ab0b8a460f398fef7e475892ff5af98f947ce128/include/alpaka/kernel/TaskKernelGpuCudaRt.hpp#L145-L154

These checks are important to check compatibility and must be reintroduced.

**Comment by sbastrakov** [comment]
Some related discussion also in #1381 (but these are not identical things)
