### ISSUE TITLE
alpaka_compiler_option fails to add options

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/alpaka#1391]
I noticed that several options defined in `alpakaCommon.cmake` are not shown in the CMake GUIs. Notably `ALPAKA_CUDA_EXPT_EXTENDED_LAMBDA` was missing. I tracked the issue down and I think there is a bug in `alpaka_compiler_option`:
```cmake
function(alpaka_compiler_option name description default)
    if(NOT DEFINED name)
        set(ALPAKA_${name} ${default} CACHE STRING "${description}")
        set_property(CACHE ALPAKA_${name} PROPERTY STRINGS "DEFAULT;ON;OFF")
    endif()
endfunction()
```
The conditional checks whether a variable `name` exists, which is certainly not what we want. The conditional should probably be `if(NOT DEFINED ALPAKA_${name})` instead. With this change I have the options available again.

**Comment by SimeonEhrig** [comment]
I noticed it when writing the [cmake documentation](https://alpaka.readthedocs.io/en/latest/advanced/cmake.html) documentation, but I was not aware why the variables are not displayed. Maybe you can also update the documentation.

**Comment by bernhardmgruber** [comment]
@SimeonEhrig what should I update in the documentation? The options which were missing *are* documented.

**Comment by SimeonEhrig** [comment]
Oh, thought there are some options displayed now, which I missed. Then it is fine.
