### ISSUE TITLE
Inconsistent Atomic support handling/testing

### ISSUE THREAD

**Issue by jkelling** [alpaka-group/alpaka#1402]
This is both an issue and a question.

## Question: How does the `atomic` test pass for the CUDA/HIP backend?

The atomic test tests 8-bit atomic operations:
https://github.com/alpaka-group/alpaka/blob/a972d5eb00c36c4806f8162dc217eae9beafa2c3/test/unit/atomic/src/AtomicTest.cpp#L785-L786
The CUDA backend does not implement these because CUDA does not support those (I could also not find 16-bit, even though CUDA supports those, but this would be a different issue). I am confused about this because, the atomic test does not exclude CUDA from them 8-bit case and CUDA provides a "fallback" specialization which would have a failing `static_assert` unless there is something special about the `THierarchy` argument:
https://github.com/alpaka-group/alpaka/blob/a972d5eb00c36c4806f8162dc217eae9beafa2c3/include/alpaka/atomic/AtomicUniformCudaHipBuiltIn.hpp#L777-L790

## Issue: inconsistent testing

While 8-bit operations are not supported by all backends (i.e. CUDA) but are still tested, the floating point cases have been deactivated in the test, because they are apparently not supported everywhere:

https://github.com/alpaka-group/alpaka/blob/a972d5eb00c36c4806f8162dc217eae9beafa2c3/test/unit/atomic/src/AtomicTest.cpp#L798-L800

## My Problem

In the OpenMP5 and OpenACC backends, 8 and 16 bit atomics are not supported when targeting GPUs, due to missing support in the underlying hardware (see CUDA). How can this be handled in agreement with alpaka's `atomic` test?

**Comment by psychocoderHPC** [comment]
For CUDA some tests are disabled https://github.com/alpaka-group/alpaka/blob/a972d5eb00c36c4806f8162dc217eae9beafa2c3/test/unit/atomic/src/AtomicTest.cpp#L518-L526

I saw that HIP tests are not up to date, IMO the atomic tests need some love.
We should discuss in the developer meeting tomorrow if alpaka should support 32 and 64bit atomics only, those should work on all devices well.

**Comment by jkelling** [comment]
As per our discussion, @psychocoderHPC will you send a PR to remove the <=16bit atomic tests?

**Comment by psychocoderHPC** [comment]
> As per our discussion, @psychocoderHPC will you send a PR to remove the <=16bit atomic tests?

Never said that I will do it, I suggested doing it. I try my best to provide a PR :-(

**Comment by j-stephan** [comment]
As discussed offline: @tonydp03 will work an PR that fixes this. The plan is to integrate this into 0.8 (next release).

**Comment by bernhardmgruber** [comment]
We had another offline discussion. We should:

* Keep running the 8- and 16-bit tests, which are not run for the CUDA/HIP backend
* Reenable the `float`/`double` tests for atomics.
* Not run the `float`/`double` tests for the CUDA backend
* Not run the `float`/`double` tests for bitwise atomics

**Comment by tonydp03** [comment]
I opened the draft pull request [here](https://github.com/alpaka-group/alpaka/pull/1431) with the changes that @bernhardmgruber mentioned.
