### ISSUE TITLE
Add DevType<Event> trait

### ISSUE THREAD

**Issue by fwyzard** [alpaka-group/alpaka#1428]
Hi,
for simplifying some generic code we are writing, we would benefit for traits to extract the `Device` type from the `Event` type, something that returns `TDev` for `EventGenericThreads<TDev>` and `DevUniformCudaHipRt` for `EventUniformCudaHip`.

Of course we can add such  trait in our code, but it could come in useful for other projects as well.

**Comment by j-stephan** [comment]
You mean something like the `getDev` function?

https://github.com/alpaka-group/alpaka/blob/d5f396ada7bb92f100bbb2f96e15fb8b1c8d9fca/include/alpaka/dev/Traits.hpp#L59

From a quick glance it should be specialized for `Event` (at least for the CUDA/HIP case).

**Comment by fwyzard** [comment]
`getDev` returns the actual device object; I meant something to extract the device C++ type, like `DevType<Queue>::type` for a `Queue`.

**Comment by j-stephan** [comment]
Ah, got it. Yes, this is currently missing from alpaka but should not be too hard to integrate.

**Comment by j-stephan** [comment]
Shifting to 0.9 since we are branching 0.8 off this week.

**Comment by fwyzard** [comment]
Done in #1479 .
