### ISSUE TITLE
Cmake reading binary file for atomic test

### ISSUE THREAD

**Issue by tonydp03** [alpaka-group/alpaka#1429]
After building the unit test for atomics, a binary file called "atomic" is created in the `build/test/unit/atomic/` directory. If the source code for the Atomic tests is then modified, the compiler fails to rebuild the application as it tries to read the binary file from the above mentioned directory instead of the std library header <atomic> (included in the source code).

<img width="1433" alt="Screenshot 2021-10-22 at 11 58 57" src="https://user-images.githubusercontent.com/41752419/138452366-62df2a90-34cd-4431-85ab-3ad12c3bf0ca.png">

It has been verified that this also happen if including the std library header <queue> in the source code of the unit test called `queue`.

A quick and easy solution might be to rename the target name of all the tests, i.e.: from `atomic` to `test-atomic` or `atomicTest` in the CMake files, to preven this from happening for other tests as well.

**Comment by jkelling** [comment]
Sounds like this issue: https://github.com/alpaka-group/alpaka/issues/815 .

**Comment by tonydp03** [comment]
As far as I see yes. While I read there might be some workaround, I think that just renaming the target tests in the cmake files could help to avoid anyone to get this error in the near future (although the directory containing the binary file should not be present in the include path.

**Comment by bernhardmgruber** [comment]
Pure speculation: nvcc might have a bug and when encountering `#include <atomic>` looks into the local directory as well. Reading #815, maybe that bug/behavior is even spurious. 

I think renaming the tests is among the easiest solutions.

**Comment by tonydp03** [comment]
I experienced the same issue with serial accelerator and TBB

<img width="1028" alt="Screenshot 2021-10-25 at 10 18 43" src="https://user-images.githubusercontent.com/41752419/138659896-2c75631a-d8ad-4192-bf87-94aec519087e.png">
