### ISSUE TITLE
Cancel running CIs on push

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/alpaka#1439]
We should configure the CI to cancel existing runs for a PR when a new commit is pushed to this PR. This way, we can free up some CI resources.

GitLab supports this, see e.g.: https://github.com/alpaka-group/alpaka/blob/develop/script/gitlabci/job_base.yml#L11
There seems to be a GitHub action that might be able to do it: https://github.com/styfle/cancel-workflow-action

**Comment by j-stephan** [comment]
Fixed by #1717.
