### ISSUE TITLE
stream-ordered memory allocations, and a caching memory allocator

### ISSUE THREAD

**Issue by fwyzard** [alpaka-group/alpaka#1448]
Many of the algorithms in CMSSW and the split `acquire()`/`produce()` approach rely on _stream-ordered_ memory allocations:
  - device memory is allocated (from the host) in association with a CUDA stream / Alpaka queue
  - device memory is used by asynchronous operations enqueued to the same stream / queue
  - device memory is marked for freeing (from the host) while it may still be used (on the device): the "stream ordering" guarantees that it is not freed and reused until the "event" of the freeing is reached by the stream associated to the memory

This effectively means that host-side `malloc` and `free` operations on device memory are asynchronous, or
_stream-ordered_, similar to the asynchronous `memcpy`, `memset` and kernel submissions.

This approach is available in CUDA since version 11.2 via [`cudaMallocAsync`/`cudaFreeAsync`/_etc._](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY__POOLS.html), but has been available from CUB as part of its _caching allocator_ since quite some time, and that version has been integrated and extended for CMSSW.
Surprisingly enough, the CUB-derived approach is still significantly faster than `cudaMallocAsync`/`cudaFreeAsync`.

While some work to re-implement the _caching allocator_ on top of Alpaka has started, it's not clear if that is the best
approach, or if we should aim for a different solution. In fact, while the _caching allocator_ make sense only when
using _stream-ordered_ memory operations (a large part of the cost comes from the global synchronisation when freeing
device memory), _stream-ordered_ memory operations could be implemented independently of it.

Some possible options are:
  - implement the _caching allocator_ and _stream-ordered_ memory operations on top of Alpaka buffers (current attempt)
      - only for the CUDA backend, or for all backends ?
      - the _stream-ordered_  part is needed for correctness for all non-blocking backends

  - implement the _stream-ordered_ memory operations in Alpaka
      - on top of the current Buffers ?
      - as a new AsyncBuffer type ?
      - orthogonal to the _caching allocator_ part

  - implement the _caching allocator_ only for the CUDA backend, using `cudaMalloc`/`cudaFree` directly

  - implement the _caching allocator_ and _stream-ordered_ memory operations within Alpaka, for all backends

**Comment by bussmann** [comment]
CCing @bernhardmgruber

**Comment by j-stephan** [comment]
If I'm not mistaken this has been fixed by #1481. Feel free to reopen this issue if you feel otherwise.
