### ISSUE TITLE
Why is there a separate unit test for sincos

### ISSUE THREAD

**Issue by sbastrakov** [alpaka-group/alpaka#1454]
The separate test is in [this file](https://github.com/alpaka-group/alpaka/blob/develop/test/unit/math/src/sincos.cpp). However, `sincos` is already tested at the same place as other math functions, [here](https://github.com/alpaka-group/alpaka/blob/e7c29db42fba7bed03d3f6b8596e5b08d776be83/test/unit/math/src/math.cpp#L434-L436). Should we just remove the separate version?

**Comment by bernhardmgruber** [comment]
The ADL unit test for `sincos` is in `math.cpp`. All the other tests for `sincos` are in `sincos.cpp`. There should not be any redundancy.

**Comment by sbastrakov** [comment]
Thanks for explaining. So was a false alarm.
