### ISSUE TITLE
Use CMake's native HIP support

### ISSUE THREAD

**Issue by j-stephan** [alpaka-group/alpaka#1462]
CMake 3.21 [introduced native support for HIP](https://cmake.org/cmake/help/v3.21/release/3.21.html#id9). We should check this out as soon as we can migrate to a CMake version >= 3.21.

**Comment by j-stephan** [comment]
> as soon as we can migrate to a CMake version >= 3.21.

This will probably happen once Ubuntu 22.04, the next LTS version, is released.

**Comment by bernhardmgruber** [comment]
So, Ubuntu 22.04 is there for some time already. @j-stephan: Can this be addressed now?

**Comment by j-stephan** [comment]
Yes, we've been on CMake 3.22 for a while.

**Comment by SimeonEhrig** [comment]
done in #2215
