### ISSUE TITLE
Enable CPU Serial backup automatically if test or examples are enabled

### ISSUE THREAD

**Issue by SimeonEhrig** [alpaka-group/alpaka#1490]
In issue #1489 I saw a really common problem. The tests and example does not work and it crashes at compiling, if the CPU serial backend is not enable. I have the same case in vikunja, where the tests and examples requires the CPU serial backend. Therefore the backend is automatically enabled if I enable the tests and examples.

https://github.com/alpaka-group/vikunja/blob/master/CMakeLists.txt#L38-L40

I'm not sure, if we want to do the same in alpaka or at least throw a cmake error, if the backend is not enabled if tests and examples are enabled.

**Comment by bernhardmgruber** [comment]
IIRC, we enabled some of the backends automatically in the past, but this was disabled at some point so that the user cannot accidentially enable the wrong backend. You can try digging through the issue history, maybe we had the discussion somewhere here.

**Comment by SimeonEhrig** [comment]
I know that we don't want to enable backends by default that it cannot happen accidentally in the user code. The question is, if this is also required for tests and examples, which are no user code?

**Comment by bernhardmgruber** [comment]
Fine for me!
