### ISSUE TITLE
Use C++17 metaprogramming facilities.

### ISSUE THREAD

**Issue by j-stephan** [alpaka-group/alpaka#1494]
In the `meta` directory there are several files referencing their C++17 counterparts:

* `Metafunctions.hpp` (`std::conjunction`, `std::disjunction` and `std::negation`)
* `Void.hpp` (`std::void_t`)
* `ApplyTuple.hpp` (`std::invoke` and `std::apply`)

Now that we have made the switch to C++17 we should address this.

**Comment by sbastrakov** [comment]
Wow today is the parallel thinking day. See #1493

**Comment by j-stephan** [comment]
Looks like you just volunteered ;-)

**Comment by sbastrakov** [comment]
@j-stephan no, those were not used for our apply. I see that it is used somewhere else tho.

**Comment by sbastrakov** [comment]
Looks to have been auto-closed, however the other 2 PRs are still open
