### ISSUE TITLE
`delete` `rand::distribution::gpu::NormalReal`'s move constructor

### ISSUE THREAD

**Issue by j-stephan** [alpaka-group/alpaka#1496]
In `rand/RandDefault.hpp` we find the following move constructor for the `NormalReal` class:

```c++
//! The move ctor clears `m_cache` of source.
//! \todo This is to be deleted when moving to C++17
NormalReal(NormalReal&& o) : m_acc(o.m_acc), m_cache(o.m_cache)
{
    o.m_cache = std::numeric_limits<T>::quiet_NaN();
}
```

Time to delete this. @jkelling @sliwowitz Any volunteers?

**Comment by sliwowitz** [comment]
I'll do it

**Comment by jkelling** [comment]
Just to be sure: the title is a bit misleading: please do not just remove the c'tor, but explicitly delete it.

**Comment by bernhardmgruber** [comment]
Discussion was here:
https://github.com/alpaka-group/alpaka/pull/1444#pullrequestreview-799902845
https://github.com/alpaka-group/alpaka/pull/1444#pullrequestreview-799905832
