### ISSUE TITLE
add cuda kernel predicate voting operations

### ISSUE THREAD

**Issue by BenjaminW3** [alpaka-group/alpaka#15]
- [x] __all/__all_sync(predicate)
  Evaluate predicate for all active threads of the warp and return non-zero if and only if predicate evaluates to non-zero for all of them. Supported by devices of compute capability 1.2 and higher.
- [x] __any/__any_sync(predicate)
  Evaluate predicate for all active threads of the warp and return non-zero if and only if predicate evaluates to non-zero for any of them. Supported by devices of compute capability 1.2 and higher.
- [x] __ballot/__ballot_sync(predicate)
  Evaluate predicate for all active threads of the warp and return an integer whose Nth bit is set if and only if predicate evaluates to non-zero for the Nth thread of the warp and the Nth thread is active. Supported by devices of compute capability 2.0 and higher.

For each of these warp vote operations, the result excludes threads that are inactive (e.g., due to warp divergence). Inactive threads are represented by 0 bits in the value returned by __ballot() and are not considered in the reductions performed by __all() and __any().

**Comment by felicepantaleo** [comment]
just checking if there is any plan on this

**Comment by psychocoderHPC** [comment]
@felicepantaleo Thanks for triggering this issue gain. @alpaka-group/alpaka-maintainers we need to increase the priority to implement these intrinsics.

**Comment by sbastrakov** [comment]
As a note, CUDA has these operations on the warp level. Alpaka currently does not have any abstraction for it. So in case we want to make this in Alpaka, I think we should first define what is warp abstraction, or do it on the block level, or somehow else resolve this.

**Comment by psychocoderHPC** [comment]
> As a note, CUDA has these operations on the warp level. Alpaka currently does not have any abstraction for it. So in case we want to make this in Alpaka, I think we should first define what is warp abstraction, or do it on the block level, or somehow else resolve this.

If we implement it on block level all threads must be call this functions collectively so it is not possible to use this function when you have branches in the code.

**Comment by sbastrakov** [comment]
Ah, true. But does it essentially mean that to define such operations in Alpaka, it needs to define the warp abstraction first?

**Comment by BenjaminW3** [comment]
What we should do depends on the use case. Does the user really want Warp level operations or block level operations?

When the user wants Warp-level operations it is really easy to implement a basic version because on CPU devices our warp size could simply be 1 and so the operations would nearly get no-ops while we would have to expose the warp size and the real operations on the CUDA backend.
Later on we could think about increasing the Warp size in CPU backends. This may require some tricky code, have some performance penalty or may not even posible.

If the user wants block-level operations we would have to know more about the specific use case.
By enforcing the Warp size to be equal to the block size we could allow it to be called in code without branches. Furthermore we could also allow it in code with branches by asserting that the warp size is equal to the block size (even if this may not be a real world use case).

**Comment by psychocoderHPC** [comment]
> What we should do depends on the use case. Does the user really want Warp level operations or block level operations?
> 
> When the user wants Warp-level operations it is really easy to implement a basic version because on CPU devices our warp size could simply be 1 and so the operations would nearly get no-ops while we would have to expose the warp size and the real operations on the CUDA backend.
> Later on we could think about increasing the Warp size in CPU backends. This may require some tricky code, have some performance penalty or may not even posible.
> 
> If the user wants block-level operations we would have to know more about the specific use case.
> By enforcing the Warp size to be equal to the block size we could allow it to be called in code without branches. Furthermore we could also allow it in code with branches by asserting that the warp size is equal to the block size (even if this may not be a real world use case).

Defining the CPU warp size to one sounds good! This will solve many issue.
I would say the block level stuf should be implemented as `reduce`, `scan`, ... and differ from the intrinsics.

**Comment by sbastrakov** [comment]
I started implementing these voting operations as discussed above in #1003.

**Comment by sbastrakov** [comment]
This functionality is now merged. I will close the issue.
