### ISSUE TITLE
Raise required CMake version to 3.21

### ISSUE THREAD

**Issue by j-stephan** [alpaka-group/alpaka#1509]
Upgrading to CMake 3.21 would offer us the following advantages:

* Support for `CUDA_SEPARABLE_COMPILATION` for clang-cuda (CMake 3.19) (important for #1467)
* Platform support for Apple Silicon (CMake 3.19)
* A more flexible `FindCUDAToolkit` module (CMake 3.19)
* Support for C++23 mode (CMake 3.20)
* `nvc++` compiler support (CMake 3.20)
* Support for the oneAPI compiler toolchain (CMake 3.20) (nice to have for #789)
* Support for Visual Studio 2022 generators (CMake 3.21)
* HIP as first-class language (CMake 3.21)
* Support for the Fujitsu compiler toolchain (CMake 3.21)

**Comment by bernhardmgruber** [comment]
CMake 3.21 was released on Jul 14, 2021. That feels a bit too new to require, but I am not blocking you. I work on platforms where I can get the latest tools :)

**Comment by j-stephan** [comment]
CMake can easily be downloaded as a standalone tool (I'm doing this myself on some rather antique platforms I have to work with). So IMHO the relatively new release date shouldn't block this, but I'm open to criticism.

**Comment by sbastrakov** [comment]
However if it's not available out-of-the-box (on, say, a cluster), many users would struggle with it.

**Comment by j-stephan** [comment]
Why? It doesn't need to be installed (or compiled), it is just a matter of downloading & unpacking.

**Comment by sbastrakov** [comment]
Not all users are computer scientists / experienced with software. It's maybe less of an issue for alpaka, but i could imagine for derivative software like PIConGPU. Of course, if we have to update, then no way around it

**Comment by SimeonEhrig** [comment]
But we already don't care about, if the correct cmake is available out-of-the box on Linux: https://gitlab.kitware.com/cmake/community/-/wikis/CMake-Versions-on-Linux-Distros

Our main target systems are Ubuntu 20.04 LTS (cmake 3.16.3) and RHEL/CentOS 8 (3.11). If you would care about this, we have to downgrade the CMake version.

**Comment by psychocoderHPC** [comment]
It is not about what is shipped with the distribution. The question is which CMake versions you mostly find on HPC systems. 
I would only vote for increasing the version to the cutting edge CMake if it is impossible to get the relocatable compile working and even then I would think about supporting this feature only if cmake 3.21 is available and throwing an error else.
Supporting only one CMake version is IMO not good. 
What @sbastrakov said is also true, even if it is only one download it is sometimes hard for a user if he need to perform all the steps without a GUI. 
A short look to the [CMake binaries](https://cmake.org/download/) is not showing a binary for OpenPower and this would make the life for all of us and our users hard on summit (ORNL) or taurus (TUD-ZIH).

**Comment by j-stephan** [comment]
> A short look to the CMake binaries is not showing a binary for OpenPower and this would make the life for all of us and our users hard on summit (ORNL) or taurus (TUD-ZIH).

How is this handled with our current CMake requirement? There are also no POWER binaries available on cmake.org. I guess the Summit / Taurus admins have installed CMake 3.18 themselves?

> I would only vote for increasing the version to the cutting edge CMake if it is impossible to get the relocatable compile working

Not impossible, but very evil and hacky. I would need to force-override the linker executable.

> and even then I would think about supporting this feature only if cmake 3.21 is available and throwing an error else.

This might be a way worth exploring.

**Comment by psychocoderHPC** [comment]
> How is this handled with our current CMake requirement? There are also no POWER binaries available on cmake.org. I guess the Summit / Taurus admins have installed CMake 3.18 themselves?

Yes the system provider is typically building the packages. It is not easy to get such packages updated and took some time.
We should discuss this in today's developer meeting and write down the decision here.

**Comment by j-stephan** [comment]
In today's meeting we have decided to stay with CMake 3.18 for now. We will revisit this topic at a later time.

**Comment by j-stephan** [comment]
Ubuntu 22.04 will make CMake 3.22 available. I propose that we switch to this version, too (which would affect alpaka 0.10). Any objections @psychocoderHPC @SimeonEhrig?

**Comment by SimeonEhrig** [comment]
The release of version 0.10 is in the summer, or? Normally, it takes about a half year until a Ubuntu LTS version fully replace it's successor, because third party software and PPA needs to update to the new Ubuntu version. Therefore we should expect, that Ubuntu 20.04 is the mainly used Ubuntu version until the end of summer.

**Comment by j-stephan** [comment]
Yes, 0.10 will probably be around in June.

**Comment by SimeonEhrig** [comment]
Therefore, I would postpone it version 0.11, because I think Ubuntu 20.04 will be stay the mainly used Ubuntu version at the release of 0.10.

**Comment by psychocoderHPC** [comment]
> Ubuntu 22.04 will make CMake 3.22 available. I propose that we switch to this version, too (which would affect alpaka 0.10). Any objections @psychocoderHPC @SimeonEhrig?

We should not increase the required CMake version based on what Ubuntu is shipping, we do not depend on Ubuntu. We should increase the version **only** so avoid bugs or if a feature is required that blocks alpaka's development.

**Comment by SimeonEhrig** [comment]
> > Ubuntu 22.04 will make CMake 3.22 available. I propose that we switch to this version, too (which would affect alpaka 0.10). Any objections @psychocoderHPC @SimeonEhrig?
> 
> We should not increase the required CMake version based on what Ubuntu is shipping, we do not depend on Ubuntu. We should increase the version **only** so avoid bugs or if a feature is required that blocks alpaka's development.

CMake 3.21 brings us several feature, see first message of the issue. But we decide to not upgrade, because the new version is not available in Ubuntu 20.04 by default. By the way, Ubuntu is shipped with CMake 3.16. Therefore we already break it :sweat_smile: Okay, maybe we can already upgrade to CMake 3.21 with version 0.10.
