### ISSUE TITLE
Improve build system documentation

### ISSUE THREAD

**Issue by j-stephan** [alpaka-group/alpaka#1513]
We have received some questions regarding the usage of the CMake-based build system:

* How are back-ends enabled?
* How are test cases enabled?

We should document this better.

**Comment by j-stephan** [comment]
We have agreed that @tonydp03 will set up a developer documentation in the next year.

**Comment by SimeonEhrig** [comment]
Great. I have also the same problem with vikunja documentation and would be great, if I can simply link the documentation.

**Comment by tonydp03** [comment]
Sure. I'll dedicate part of my time to alpaka developments next year, in parallel with CMS developments as well.

**Comment by SimeonEhrig** [comment]
I opened a PR #1571

**Comment by tonydp03** [comment]
PRs #1571 and #1609 addressed this issue. Any other part of the documentation might get some improvements?

**Comment by j-stephan** [comment]
I think this can be closed since the initial questions presented here have been addressed. We can always open a follow up issue later if we find that the documentation is lacking elsewhere.
