### ISSUE TITLE
Avoid M_PI

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/alpaka#1553]
`alpaka/rand/RandDefault.hpp` uses `M_PI` which is a non-standard extension. Please replace the constant by e.g. `boost::math::constants::pi`.

**Comment by fwyzard** [comment]
Out of curiosity, which C library _does not_ define `M_PI` ?

**Comment by bernhardmgruber** [comment]
I primarily encountered it with MSVC 19.30 (VS 2022), where you need to explicitely ask for it with `_USE_MATH_DEFINES` before including `<cmath>`. For some reason we did not have that problem in the CI with VS 2019.

**Comment by j-stephan** [comment]
It sounds less intrusive to define another preprocessor flag rather than add yet another Boost dependency (see #481).

**Comment by sbastrakov** [comment]
An own variable template for pi is also an option i think. No ugly all caps name as a bonus

**Comment by bernhardmgruber** [comment]
> It sounds less intrusive to define another preprocessor flag rather than add yet another Boost dependency (see #481).

We already have a Boost dependency. There is no way around it. So why reinvent the wheel?
Plus: C++20 has `std::numbers::pi<T>`.

IMO the preprocessor flag adds more complexity, since it complicates the build system. And I think we have users, that don't use alpaka's CMake, so they would need to specify the flag manually each time.

**Comment by j-stephan** [comment]
> We already have a Boost dependency. There is no way around it. So why reinvent the wheel?

What are we reinventing? `_USE_MATH_DEFINES` is the official MSVC way: https://docs.microsoft.com/en-us/cpp/c-runtime-library/math-constants?view=msvc-170

> Plus: C++20 has std::numbers::pi<T>.

Then we can switch to that once C++20 is available to us.

> IMO the preprocessor flag adds more complexity, since it complicates the build system.

It is literally a one-liner in CMake. And we need to change the build system in Boost's case as well since we would need to check for the existence of `boost::math` and link to it (even more lines!).

> And I think we have users, that don't use alpaka's CMake, so they would need to specify the flag manually each time.

Those don't use MSVC anyway AFAIK.

**Comment by fwyzard** [comment]
> > And I think we have users, that don't use alpaka's CMake, so they would need to specify the flag manually each time.
> 
> Those don't use MSVC anyway AFAIK.

We don't use CMake, and we don't use MSVC, and have been using `M_PI` since... (checks)... well, technically "since ever" as far as CMSSW is concerned: the first (pre)release from 2005 was already using it.
