### ISSUE TITLE
Add nvcc 11.6 to CI

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/alpaka#1573]
CUDA Toolkit 11.6 has been released recently. Add tests for this version to the CI.

**Comment by SimeonEhrig** [comment]
Looks, like that Nvidia is silently releasing software :thinking: I got the current developer news on the 13. and there was nothing about the new CUDA version and the news was one day after the last update of the CUDA 11.6 documentation.

**Comment by j-stephan** [comment]
There is a blog post: https://developer.nvidia.com/blog/cuda-11-6-toolkit-new-release-revealed/

**Comment by BenjaminW3** [comment]
This version adds support for VS 2022, which I added support for in #1583
