### ISSUE TITLE
use constexpr in device function

### ISSUE THREAD

**Issue by s9105947** [alpaka-group/alpaka#1580]
Dear Maintainers,

when I refer to a C++ `constexpr` function from inside a (inline-) device function, should I mark the `constexpr` as a device function as well?

In a short discussion @j-stephan noted that this (probably) depends on the used compiler.

Apart from the question: Where/How should this be noted in the documentation?
I'd suggest a Notes/Misc/Q&A section, but I haven't found any.

**Comment by fwyzard** [comment]
`nvcc --expt-relaxed-constexpr` will consider any `constexpr` function as `__host__ __device__`

I'm not sure what clang does, nor if HIP has a similar flag.

**Comment by j-stephan** [comment]
As @fwyzard said CUDA allows this with an extra compiler flag. According to https://github.com/ROCm-Developer-Tools/HIP/issues/374 this is explicitly not supported for HIP.

So right now `constexpr` functions should also be marked as device functions.

**Comment by s9105947** [comment]
Copy-paste-able text for documentation (I don't know where to put it):

```
Using constexpr from device functions
-------------------------------------

When calling a ``constexpr`` function from inside a device function, also mark the called function as a device function, e.g. by prepending ``ALPAKA_FN_ACC``.

Note that some compilers do that by default, but not all.
For details please refer to `#1580 <https://github.com/alpaka-group/alpaka/issues/1580>`_ .
```
