### ISSUE TITLE
`getWarpSize()` should return a vector

### ISSUE THREAD

**Issue by j-stephan** [alpaka-group/alpaka#1595]
We currently assume that each device has exactly one supported warp size. This is true for CUDA GPUs and (to an extent) for AMD GPUs. On CPUs this is already questionable if we take vectorization into account but the current approach seems to work reasonably well.

As the SYCL back-end is nearing completion we can observe that this is no longer true: My laptop GPU (Ice Lake) reports that it can operate in sub-groups (the SYCL equivalent of warps) of size 8, 16 and 32. The exact size is chosen by the compiler depending on some heuristics but can also be enforced by the user through kernel attributes in C++ code (example: `[[sycl::reqd_sub_group_size(16)]]`). The SYCL runtime will claim all three are supported when queried.

`getWarpSize` should therefore be renamed to `getWarpSizes` and return a vector of supported sizes.

**Comment by tonydp03** [comment]
Should we just return vectors for all the backends (with size 1 in the other cases - CPU included for now) or maybe just change the SYCL trait specialization? I expect that some things for SYCL could be different in general - i.e. the device native handle is an `std::pair` instead of an `int` like in the other backends - so it could make sense if the function returns a vector only for the sycl backend.

**Comment by j-stephan** [comment]
This is needed at least for SYCL, but IMO it should also extend to the CPU back-ends. Having a vector for all back-ends makes this uniform, but I may be convinced otherwise if someone presents a counter argument.

**Comment by tonydp03** [comment]
At that point I would agree on having it for all the backends and users can eventually call `getWarpSizes()[0]` instead of just `getWarpSizes()` in case - i.e. - they only need it for CUDA or devices that only support one size.

**Comment by fwyzard** [comment]
From a user's perspective I find having a consistent interface preferable -- so I would suggest to always return a vector.
