### ISSUE TITLE
[RFC] Remove pitched allocations

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/alpaka#1597]
Some backends in alpaka insert padding after the rows for a 2D or higher dimensional buffer (notable CUDA/HIP with cudaMallocPitch and cudaMalloc3D). This additional padding is hardware dependent and selected by the implementation with the hope to provide faster memory access to the buffer inside a kernel. That concerns coalescing, the memory controller, number of memory transactions etc.

However, this additional padding, often also called row pitch, or just pitch, is a frequent source of bugs, even in alpaka. See e.g. #1549 or #1240. Furthermore, it is also a blocker for new abstractions like `std::mdspan`, see: #1482.

So I browsed the internet, trying to find what the actual performance gain of a pitched allocation is compared to a non-pitched one. Here are some results:
* [This presentation](http://www.quest-itn.org/events/1st-quest-workshop/1st-quest-workshop/programme/presentations/tuesday/GPU_tutorial.pdf) claims that a pitched allocations can give 75% (Tesla C1060) or 30-40% (GTX 480) performance improvements. Note that the listed GPUs are from 2009 and 2010.
* [This NVIDIA forum answer from 2018](https://forums.developer.nvidia.com/t/what-is-the-stream-ordered-equivalent-of-cudamallocpitch/189574/2) states that "pitched allocations should have been noticeably important in cc1.x GPUs. Those GPUs died out circa 2016.". The question was why there is no pitched allocation API for managed memory.
* [This Stackoverflow comment](https://stackoverflow.com/questions/29694627/cudamallocpitch-for-managed-memory#comment47699641_29694627) states that "GPU caches, in place since cc 2.0 devices appeared, have to some extent mitigated the performance impact of not using pitched allocations on the GPU."
* [This NVIDIA forum answer from 2017](https://forums.developer.nvidia.com/t/bad-performance-using-mallocpitch-and-memcpy2d/50203) states that "the pitched method may not give any better performance than the unpitched method. Pitched allocations were especially useful on early GPUs, but are of less significance on modern GPUs. Depending on your GPU, its possible that the overhead associated with pitch calculations in the kernel (especially for such a simple kernel) may outweigh any benefit from pitched access."
* [This example on Stackoverflow](https://stackoverflow.com/questions/30903380/cudamalloc-vs-cudamalloc3d-performance-for-a-2d-array) shows that cudaMalloc3D is 10% slower than cudaMalloc because of additional instruction overhead in the kernel.

And since such arguments are rather handwaivy, I patched the alpaka CUDA backend to use `cudaMalloc` for all dimensions and tested a few runs of `matMulTest`. The speedup refers to the improvement from `cudaMallocPitch` over `cudaMalloc`:

On an NVIDIA Titan Xp with sizes m:32013, n:39529, k:11547, speedup 1.005469178.
On an NVIDIA V100 with sizes m:32013, n:39529, k:11547, speedup 1.002338893.

Note that these numbers only measure the kernel runtime, not the memory transfer time, which I assume is way worse with `cudaMallocPitch'. The numbers are really small, small enough for me to start a discussion to remove pitched allocations altogether. What is your opinion on the subject?

If you have literature, examples or measurements of your own, please them with me share as well!

**Comment by fwyzard** [comment]
IMHO pitched allocations are only useful if they can be used consistently on all backends, so that one can allocate an N-dimensional buffer with a given pitch (_e.g._ 128 bytes) on any backend, then transfer the buffer as a whole and use it on any other backend.

Pitched *views* are useful for other purposes - for example, to take an N-dimensional buffer, fix one of the indices, and access it via an N-1-dimensional view.

That said, I don't think we need pitched allocations for the CMS uses cases:
  - for simple ones we just use 0-dimensional or 1-dimensional buffers;
  - for complex ones we are in the process of migrating flat 1-dimensional buffers of raw bytes, and then construct SoA structures inside them.

**Comment by bussmann** [comment]
Remove. Any specific memory layout should remain outside Alpaka. This is done by LLAMA.

**Comment by j-stephan** [comment]
If we're approaching this subject anyway we should also discuss the general need for n-dimensional buffers in alpaka. If we ditch pitched allocations, why not ditch 2D / 3D allocations entirely?

**Comment by bussmann** [comment]
Agreed. My view was always this is the job of an extra interface/library. May I recommend LLAMA?

**Comment by j-stephan** [comment]
One could argue that we should also remove the type from the buffer so that the user always receives a range of `std::byte`s and has to set up the actual interpretations on their own.

I always wanted to have an overarching concepts library in the ecosystem that defines the interaction between our libraries. The interfaces of memory interpretations might be a good start for that (we can probably extract the LLAMA concepts here and turn them into something general purpose with regard to the ecosystem).

alpaka would then define some fundamental interpretations (a user shouldn't have to use LLAMA for an array of `float`s) and leave everything more sophisticated to LLAMA.

**Comment by bernhardmgruber** [comment]
> IMHO pitched allocations are only useful if they can be used consistently on all backends, so that one can allocate an N-dimensional buffer with a given pitch (_e.g._ 128 bytes) on any backend, then transfer the buffer as a whole and use it on any other backend.

That is also something I have found browsing the internet, since a 2D memcopy with different source and destination buffer pitches is rather costly.

> Pitched _views_ are useful for other purposes - for example, to take an N-dimensional buffer, fix one of the indices, and access it via an N-1-dimensional view.

Fully agreed. `std::submdspan` can do that for example. They are called strided views there.

> That said, I don't think we need pitched allocations for the CMS uses cases:
> 
> * for simple ones we just use 0-dimensional or 1-dimensional buffers;
> * for complex ones we are in the process of migrating flat 1-dimensional buffers of raw bytes, and then construct SoA structures inside them.

The latter case is exactly what LLAMA is designed for. You provide a region of bytes, describe a memory layout, and a LLAMA view will then map your index space into that byte region.

> If we're approaching this subject anyway we should also discuss the general need for n-dimensional buffers in alpaka. If we ditch pitched allocations, why not ditch 2D / 3D allocations entirely?

> One could argue that we should also remove the type from the buffer so that the user always receives a range of std::bytes and has to set up the actual interpretations on their own.

Both of these suggestions seem a bit too drastic for me. For now I am just worried about the row pitches, since they inhibit us from using several great abstractions such as `std::mdspan`. But sure, we can discuss it at some point.

> alpaka would then define some fundamental interpretations (a user shouldn't have to use LLAMA for an array of floats) and leave everything more sophisticated to LLAMA.

This is important to me. LLAMA is a powerful library. It might be too flexibly for some simpler use cases though. Like a plain array of T, or a 2D array in row major storage order. Those should be supported directly in alpaka.

**Comment by bernhardmgruber** [comment]
Here are a few additional numbers on the V100, also including the time required for the memory copy:

![image](https://user-images.githubusercontent.com/1224051/154726536-ae3c10c8-6326-4228-87a5-4fec3e343566.png)

Apart from the insane jitter on the copy times (feel free to suggest improvements here: #1599), it also looks like we can win something on copies when the pitch is dropped.

**Comment by fwyzard** [comment]
> I patched the alpaka CUDA backend to use `cudaMalloc` for all dimensions and tested a few runs of `matMulTest`.

If I read the code correctly, the underlying type used in `matMulTest` is `std::uint32_t`, whose size is a divisor of 128 bytes.

What happens if the type used in the buffer has a size that is not a power of 2 ?
Would that make the pitched allocation more useful ?

**Comment by bernhardmgruber** [comment]
Here is another measurement (no serious benchmark) from my GeForce RTX 2060. First group is cudaMalloc, second group is cudaMallocPitch.
![image](https://user-images.githubusercontent.com/1224051/154947577-f7bd2718-996f-4d86-b0cd-16e4e0852498.png)
Here we get a 5% runtime improvement at roughly the same transfer time.

**Comment by bernhardmgruber** [comment]
The pitches used by my CUDA implementation on the GeForce and then the V100 are:

| matrix width in bytes | row pitch in bytes | padding | 
| -|-|-|
| 36988 | 37376 | 388 | 
| 126516 | 126976 | 460 | 
-- | -- | --
46196 | 46592 | 396
158108 | 158208 | 100

Note that I use different matrix sizes on the two cards.

> What happens if the type used in the buffer has a size that is not a power of 2 ?

If I make matMulTest use a type containing 3 `uint32_t` (thus the matrix element size is 12 bytes) and a smaller matrix:

| matrix width in bytes | row pitch in bytes | padding | 
| -|-|-|
| 37356 | 37376 | 20 | 
| 126744 | 126976 | 232 | 

So additional padding is inserted in all cases. Mind however, that the padding inserted for the 3 `uint32_t` struct is not a multiple of 12 bytes. ~~Thus, we could not represent such a row pitch as multiple of element sizes and thus `std::mdspan` could not be used here.~~ Such padding can be represented by `std::mdspan`.

**Comment by SimeonEhrig** [comment]
> One could argue that we should also remove the type from the buffer so that the user always receives a range of `std::byte`s and has to set up the actual interpretations on their own.
> 

I would not suggest this. It's make harder to use and is really error prone, like working with `void *`. Also we should think about our target group. There are not only well experienced developer. There are also scientist, which want to implement his algorithm in a HPC context, like the physicists, which develop the plugins for PIConGPU. 

I know, it is also possible to add an abstraction layer on top of alpaka, but to be honest I think it is not possible for each project because of lacking resources and I don't see enough advantages of the `std::byte` approach.

> I always wanted to have an overarching concepts library in the ecosystem that defines the interaction between our libraries. The interfaces of memory interpretations might be a good start for that (we can probably extract the LLAMA concepts here and turn them into something general purpose with regard to the ecosystem).
> 

This requires at least that we support package manager, like spack and conda. It is already hard enough to install alpaka for vikunja from source. Can you image, that somebody is starting with alpaka, see the complicated definition of the kernel and launch process and than he recognize, that he has to install an extra library for the memory management.

**Comment by fwyzard** [comment]
Following up to this morning meeting, I couldn't find how to query the pitch that would be used by `cudaMallocPitch()` and `cudaMalloc3D()` :-(

I found that there is a way to query the _maximum_ pitch for a device via `cudaDeviceGetAttribute`:
```
`cudaDevAttrMaxPitch`: Maximum pitch in bytes allowed by the memory copy functions that involve memory regions allocated through `cudaMallocPitch()`

```

Then, I found that the equivalent function to `cudaMallocPitch()` in _driver_ API takes an extra parameter:
```c++
CUresult cuMemAllocPitch ( CUdeviceptr* dptr, size_t* pPitch, size_t WidthInBytes, size_t Height, unsigned int  ElementSizeBytes ) 
```
  - `ElementSizeBytes` specifies the size of the largest reads and writes that will be performed on the memory range. `ElementSizeBytes` may be `4`, `8` or `16` (since coalesced memory transactions are not possible on other data sizes). If `ElementSizeBytes` is smaller than the actual read/write size of a kernel, the kernel will run correctly, but possibly at reduced speed.

So, it looks like the pitch could just be `16` (or `cudaDevAttrMaxPitch` if it's smaller) ?

**Comment by bernhardmgruber** [comment]
Thank you for pointing to `cuMemAllocPitch`. It's documentation further says:

> The byte alignment of the pitch returned by cuMemAllocPitch() is guaranteed to match or exceed the alignment requirement for texture binding with cuTexRefSetAddress2D().

Which then further mentions:

> It is required that dptr be aligned to the appropriate hardware-specific texture alignment. You can query this value using the device attribute CU_DEVICE_ATTRIBUTE_TEXTURE_ALIGNMENT.
> Pitch has to be aligned to the hardware-specific texture pitch alignment. This value can be queried using the device attribute CU_DEVICE_ATTRIBUTE_TEXTURE_PITCH_ALIGNMENT.

These values are 512 and 16 on my GeForce.

**Comment by psychocoderHPC** [comment]
> Remove. Any specific memory layout should remain outside Alpaka. This is done by LLAMA.

I disagree, the padding is set by CUDA/HIP and is device-specific. This does not mean that llama does not need this feature, llama should be able to handle padding but it is currently not clear if an emulated padding based on virtual dimension changes on a 1D memory chunk is equivalent to a native allocated n-D memory chunk.
A native n-D allocation function has several optimization possibilities e.g.
 - use padding based on the extents to fit memory pages
 - keep device specifics into account
Native created n-D memory could provide faster memory copies when a slice out of the n-D memory is copied e.g. with cudaMemcopy2D.

I redirected the question about the benefits of using cudaMalloc2d today to two NVIDIA dev's, additionally we will check the HIP code which optimizations are called if n-D memory is alloced.

**Comment by bernhardmgruber** [comment]
[This question on Stackoverflow](https://stackoverflow.com/questions/12550927/pitch-alignment-for-2d-textures) suggest that the pitch in cudaMallocPitch is honoring cudaDeviceProp::textureAlignment, which is 256 on older hardware, and 512 on newer. Textures require this alignment for their start address, and only texturePitchAlignment (usually 16) for each row.
Speculation: the row pitch is also chosen to be the textureAlignment, so you can bind a texture to a subregion of the 2D allocation.

**Comment by bernhardmgruber** [comment]
From looking at the HIP implementation (thx @psychocoderHPC) it seems that `hipMallocPitch` is related to textures/images. In fact, if the target device does not supported images, `hipMallocPitch` even fails to allocate.
Furthermore, `hipMalloc`, `hipMallocPitch` and `hipMalloc3D` all eventually call `amd::SvmBuffer::malloc`, so it seems there are no further specific optimizations.
See: https://github.com/ROCm-Developer-Tools/hipamd/blob/6d1262c56061cf63a44cde77c9205912e67c278d/src/hip_memory.cpp#L632-L673

**Comment by bernhardmgruber** [comment]
@psychocoderHPC and me discussed today as well, that it is probably impossible to proof that pitched allocations do not matter performance wise, because someone for sure can come up with an example where it matters.

For now, I have concluded to implement better support for arbitrary pitches in LLAMA and see where this goes.

**Comment by bernhardmgruber** [comment]
I think we kind of agreed to keep pitched allocations in alpaka. They can also be nicely abstracted by `std::mdspan`, see #1482. I will therefore close this issue since no action will be taken.
