### ISSUE TITLE
clang + libstdc++ 9.4 + nvcc broken

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/alpaka#1625]
Today our ubuntu containers updated from libstdc++ 9.3 to 9.4, which broke compilation with nvcc + clang as host compiler.

See e.g. this CI run from today at 11:00: https://gitlab.com/hzdr/crp/alpaka/-/pipelines/485977443
And this one from 13:00: https://gitlab.com/hzdr/crp/alpaka/-/pipelines/486110519

The error message starts with:
```
/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/ext/numeric_traits.h(70): error: qualified name is not allowed
/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/ext/numeric_traits.h(72): error: expected a "("
/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/ext/numeric_traits.h(72): error: expected a type specifier
/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/ext/numeric_traits.h(72): error: expected a ")"
/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/ext/numeric_traits.h(76): error: expected a "("
...
```
The problem is also referenced in this NVIDIA forum post: https://forums.developer.nvidia.com/t/clang12-is-not-able-to-compile-a-simple-test-program-with-cuda11-4-3-on-ubuntu20-04-3-lts-on-wsl/200000.

**Comment by j-stephan** [comment]
The issue on the NVIDIA forums is not the same since the user there makes use of libstdc++ 10. But it is similar, this issue often occurs when `nvcc` doesn't like the host compiler. I'm not sure we can currently do much other than force-installing libstdc++ 9.3 in the CI runners.

**Comment by j-stephan** [comment]
Judging by https://gitlab.com/hzdr/crp/alpaka/-/pipelines/486239694 it appears that the combination clang + nvcc + libstdc++ 9.4 is broken for CUDA versions 11.3, 11.4 and 11.5 (11.6 appears to work again). I guess we just have to disable these and update our `README.md`. I deem it unlikely that NVIDIA will fix older CUDA versions if the most recent one works.

**Comment by bernhardmgruber** [comment]
I tried to downgrade libstdc++ in the CI runners to by passing `g++-9=9.3.0-10ubuntu2` to `apt` when we install cuda (which in turn installs g++). However, then we get mixed up versions of the packages and dependencies. This is more messy than I though, so I will drop this idea.
