### ISSUE TITLE
[RFC] Remove support for `std::function` kernels.

### ISSUE THREAD

**Issue by j-stephan** [alpaka-group/alpaka#1634]
I propose to remove support for `std::function` kernels because of the following reasons:

1. Using a `std::function` as a kernel task is currently only supported for CPU back-ends. For CUDA and HIP this is explicitly disabled and with SYCL it is untested.
2. Since all back-ends support trivially copyable kernel arguments we should enforce that all arguments passed to the underlying back-end kernel are in fact trivially copyable, including the user-defined kernel task. 
3. I've never seen a `std::function` based alpaka kernel outside of our test cases.

**Comment by bernhardmgruber** [comment]
I also don´t see a big use case for passing kernels as `std::function`s. You have my support!

**Comment by psychocoderHPC** [comment]
I would avoid supporting std::function. The reason is that writing heterogenious code would be much harder if there are ways to spawn kernel which will not be supported by all backends.
