### ISSUE TITLE
A simple way to specify the ROCm installation directory ?

### ISSUE THREAD

**Issue by fwyzard** [alpaka-group/alpaka#1643]
Is there a simple way to tell CMake where to find the ROCm installation ?

The best I've managed so far is
```bash
ROCM_ROOT=/opt/rocm-5.0.2

cmake \
  -DCMAKE_C_COMPILER=${ROCM_ROOT}/llvm/bin/clang \
  -DCMAKE_CXX_COMPILER=${ROCM_ROOT}/llvm/bin/clang++ \
  -DCMAKE_PREFIX_PATH=$(echo $(find ${ROCM_ROOT}/ -type d -name cmake) | tr ' ' ';') \
  -DROCM_PATH=${ROCM_ROOT} \
  ... \
  -DALPAKA_ACC_GPU_HIP_ENABLE=ON \
  -DALPAKA_ACC_GPU_HIP_ONLY_MODE=OFF \
  -DGPU_TARGETS=gfx900 \
  ...
```

  - `CMAKE_C_COMPILER` and `CMAKE_CXX_COMPILER` are needed to choose the right compiler, otherwise CMake will use the system `gcc` and `g++`.
As @j-stephan suggests below, the same effect can be obtained setting the `CC` and `CXX` environment variables:
    ```bash
    CC=${ROCM_ROOT}/llvm/bin/clang CXX=${ROCM_ROOT}/llvm/bin/clang++ cmake ...
    ```

  - `CMAKE_PREFIX_PATH` with a `;`-separated list of all the `cmake` directories is needed to find the various `hip-config.cmake`, `AMDDeviceLibsConfig.cmake`, _etc._

  - `ROCM_PATH` may or may not be needed; I've set it because `/opt/rocm-5.0.2/hip/lib/cmake/hip/hip-config.cmake` sets it to `/opt/rocm`, and I don't want it to pick up the wrong ROCm installation.

**Comment by psychocoderHPC** [comment]
I always set `CMAKE_CXX_COMPILER` to the rocm clang and add rocm, hip, rocran and hiprand to `CMAKE_PREFIX_PATH`.

IMO your cmake command line looks good and I do not know another way.

**Comment by fwyzard** [comment]
OK, thanks.

**Comment by j-stephan** [comment]
Note that the first line should read `-DCMAKE_C_COMPILER`, not `-DCMAKE_CC_COMPILER`. Personally I find it easier to specify those in front:

```
CC=/path/to/clang CXX=/path/to/clang++ cmake <other vars> ..
```

**Comment by fwyzard** [comment]
> Note that the first line should read `-DCMAKE_C_COMPILER`, not `-DCMAKE_CC_COMPILER`.

Ah, thanks for the correction.
