### ISSUE TITLE
[RFC] Use SPDX license identifiers

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/alpaka#1679]
All alpaka headers use a license statement at the top. This adds a lot of noise and there is a more compact way to specify the license: SPDX license identifiers. More info here: https://spdx.dev/ids/

We basically replace the existing license preamble in header files by:
`// SPDX-License-Identifier: MPL-2.0`

Are there any concerns to such a change?

**Comment by j-stephan** [comment]
Yes: I don't see why that is immediately necessary. I rarely (if ever) spend much time reading the top few lines of a source file. IMO the time required to change this would be invested better elsewhere.

**Comment by sbastrakov** [comment]
I personally would prefer to not scroll through the licence when viewing or reviewing.

**Comment by j-stephan** [comment]
SPDX is an ISO standard. Since we are all about being standard-conforming and portable I support this.
