### ISSUE TITLE
Proposal: demangle type names

### ISSUE THREAD

**Issue by fwyzard** [alpaka-group/alpaka#1681]
There are a few places in the alpaka library and the test files where names and log messages use mangled type names:
https://github.com/alpaka-group/alpaka/blob/dacd3a2d955943b485b7fcc8eb3db7fd38a73df7/include/alpaka/acc/AccCpuSerial.hpp#L151

https://github.com/alpaka-group/alpaka/blob/dacd3a2d955943b485b7fcc8eb3db7fd38a73df7/include/alpaka/kernel/TaskKernelGpuUniformCudaHipRt.hpp#L293-L294

https://github.com/alpaka-group/alpaka/blob/dacd3a2d955943b485b7fcc8eb3db7fd38a73df7/test/unit/math/src/TestTemplate.hpp#L64-L66

_etc._

I think it would be a bit user-friendlier to demangle the type names.

It would be easy to do using Boost, just a matter of replacing `typeid(T).name()` with `boost::core::demangle(typeid(T).name())`.

We are using a similar approach in our code, but wrap it in a template constant to avoid repeated calls:
```c++
template <typename T>
inline const std::string demangle = boost::core::demangle(typeid(T).name());
```
and then use it simply as `demangle<T>`:
```c++
std::cout << demangle<T> << std::endl;
```

If the preference is to avoid the additional dependency on Boost by default, it could also be protected with an `#ifdef`:
```c++
#ifdef ALPAKA_DEMANGLE_TYPE_NAMES
template <typename T>
inline const std::string readableName = boost::core::demangle(typeid(T).name());
#else
template <typename T>
inline const std::string readableName = std::string(typeid(T).name());
#endif

...

std::cout << readableName<T> << std::endl;
```

**Comment by sbastrakov** [comment]
I like the idea. If implemented, we may also make use of it in PIConGPU to get more readable kernel names in exception messages or safety check macros that wrap kernel calls.

**Comment by bernhardmgruber** [comment]
I really love the variable template approach! What would be even better would be a constexpr `string_view` version. I would need that in LLAMA to also print type names in CUDA code from the `Trace` mapping.

**Comment by bernhardmgruber** [comment]
So I went down that rabbit hole and could actually get it done based on this trick with `__PRETTY_FUNCTION__`: https://bitwizeshift.github.io/posts/2021/03/09/getting-an-unmangled-type-name-at-compile-time/. Here is the changeset in LLAMA, which builds some stuff on top, like stripping namespace qualifiers: https://github.com/alpaka-group/llama/pull/521/files#diff-bab643414f6e6c3504a987eb2a1f653ada3d8cfa758c8b5a3d097815c4646005R10-R89

**Comment by tonydp03** [comment]
I guess here it depends on what we want to do, if something simple with not so many lines of code to add to alpaka (using `boost`), or having the `string_view` version (at this point maybe we could just write the alpaka version of what you already did for llama, and use that one in llama too? - I didn't go through the entire code but I saw that more or less follows the approach describe in the link that you posted)

**Comment by bernhardmgruber** [comment]
I think just using what @fwyzard suggested is totally fine! I was just curious if anyone knew a `constexpr` approach. I am also totally fine with:
```c++
template <typename T>
inline const std::string demangled = boost::core::demangle(typeid(T).name());
```
