### ISSUE TITLE
`alpaka::Complex<T>` and `std::complex<T>` are not layout compatible

### ISSUE THREAD

**Issue by j-stephan** [alpaka-group/alpaka#1720]
gcc-12 landed in my distro today and I gave the alpaka test suite a try (in C++20 mode). This triggered the following error:

```
[ 22%] Building CXX object test/unit/math/CMakeFiles/mathTest.dir/src/mathComplexDouble.cpp.o
In file included from /home/stepha27/workspace/caravan/alpaka/test/unit/math/src/TestTemplate.hpp:19,
                 from /home/stepha27/workspace/caravan/alpaka/test/unit/math/src/mathComplexDouble.cpp:11:
/home/stepha27/workspace/caravan/alpaka/test/unit/math/src/mathComplexDouble.cpp: In instantiation of 'void C_A_T_C_H_T_E_M_P_L_A_T_E_T_E_S_T_F_U_N_C_7() [with TestType = alpaka::AccCpuSerial<std::integral_constant<long unsigned int, 1>, long unsigned int>]':
/home/stepha27/workspace/caravan/alpaka/test/unit/math/src/mathComplexDouble.cpp:41:1:   required from 'void {anonymous}::ns_C_A_T_C_H_T_E_M_P_L_A_T_E_T_E_S_T_8::C_A_T_C_H_T_E_M_P_L_A_T_E_T_E_S_T_8<Types>::reg_tests() [with Types = {alpaka::AccCpuSerial<std::integral_constant<long unsigned int, 1>, long unsigned int>, alpaka::AccCpuThreads<std::integral_constant<long unsigned int, 1>, long unsigned int>, alpaka::AccCpuTbbBlocks<std::integral_constant<long unsigned int, 1>, long unsigned int>, alpaka::AccCpuOmp2Blocks<std::integral_constant<long unsigned int, 1>, long unsigned int>, alpaka::AccCpuOmp2Threads<std::integral_constant<long unsigned int, 1>, long unsigned int>}]'
/home/stepha27/workspace/caravan/alpaka/test/unit/math/src/mathComplexDouble.cpp:41:1:   required from here
/home/stepha27/workspace/caravan/alpaka/test/unit/math/src/mathComplexDouble.cpp:43:25: error: static assertion failed: std::is_layout_compatible_v<alpaka::Complex<double>, std::complex<double>>
   43 |     STATIC_REQUIRE(std::is_layout_compatible_v<alpaka::Complex<double>, std::complex<double>>);
      |                    ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/stepha27/workspace/caravan/alpaka/test/unit/math/src/mathComplexDouble.cpp:43:25: note: 'std::is_layout_compatible_v<alpaka::Complex<double>, std::complex<double> >' evaluates to false
```

If I do a parallel build the same issue appears for `float`. @sbastrakov

**Comment by sbastrakov** [comment]
Oh. Perhaps I misinterpreted what should be a guarantee for layout of complex types. What we need is `array-oriented access` as described [here](https://en.cppreference.com/w/cpp/numeric/complex). So perhaps the way it's checked via layout compatibility is not correct. We could instead check directly using how cppreference put it.

It could also be something got optimized or aligned at this gcc version and we should guard against it.

**Comment by j-stephan** [comment]
AFAIK we haven't enabled any C++20 tests in our CI. So this may affect more compilers than just gcc-12.

**Comment by sbastrakov** [comment]
The test is conditionally enabled not on C++20 standard, but on availability of this feature. But idk if it ran actually and on which configurations.

**Comment by j-stephan** [comment]
Okay, I just gave this a try with clang-13. And it seems to be a gcc(-12?) quirk because clang happily compiles this.

**Comment by sbastrakov** [comment]
Okay, i will have a look what's up with gcc 12 till the next alpaka meeting hopefully. Now finishing a large PIConGPU task.

**Comment by j-stephan** [comment]
Alright, gcc-12 is simply the first version to support `std::is_layout_compatible_v`. For some reason clang-13 never goes past the feature check macro although this should be a library feature. (libc++ doesn't have this yet, but clang should be able to use libstdc++-12).

MSVC with `/std:c++20` also fails at the static assertion. So I guess this is nothing gcc-related.

**Comment by j-stephan** [comment]
Okay, I'll stop digging now. I guess the error comes from how the standard libraries implement `std::complex`:

* MSVC STL internally uses an array with two elements
* libstdc++ uses C's `_Complex` type
* libc++ uses our approach

This is why `is_layout_compatible` fails. However, I'm not convinced we need this check at all. For array-oriented access it should be sufficient to check at runtime if the various `reinterpret_cast` requirements work.

**Comment by sbastrakov** [comment]
Yeah, it looks like we check a far more strict requirement than we should, and it's a bug in the test, not in complex implementation,

**Comment by j-stephan** [comment]
I'll submit a fix along with a general gcc-12 fix PR. Found some other smaller issues on the way.
