### ISSUE TITLE
`alpaka::Complex` is not packed

### ISSUE THREAD

**Issue by j-stephan** [alpaka-group/alpaka#1722]
From [cppreference.com](https://en.cppreference.com/w/cpp/numeric/complex):

> An implementation cannot declare additional non-static data members that would occupy storage disjoint from the real and imaginary components, **and must ensure that the class template specialization does not contain any padding**.

For our common use cases, `float` and `double`, this shouldn't be a problem on all common architectures. However, users might put a `long double` into it, which may have a weird size. We should guard against this by packing the structure (`[[gnu::packed]]`, `#pragma pack`, etc.).

@sbastrakov, no need to make this a priority, this is more from a legalese POV. #1721 introduces a compile-time check so our CI can catch this if something goes wrong in our implementation.

**Comment by bernhardmgruber** [comment]
I don't think packing would change anything, since there cannot be any padding between two types due to their natural alignment.

Can we not just forbid types other than `float` and `double`?

**Comment by sbastrakov** [comment]
Maybe we should, on GPUs we basically support only float and double math (not just for complex, but in general)

**Comment by sbastrakov** [comment]
Sorry, I forgot about this issue. So in case the changes are needed regarding it, someone else will have to do it. As I mentioned above, on CUDA and HIP we already basically only support `float` and `double`, same as other math stuff (arithmetic may work, but no more than that).

**Comment by j-stephan** [comment]
> Can we not just forbid types other than `float` and `double`?

No. alpaka allows users to extend our base API, so if they provide the necessary math functions they should be able to use `alpaka::Complex` with `long double`.

**Comment by bernhardmgruber** [comment]
Fine.

Still, packing is not the solution you need here. If the compiler introduces padding between two `T`s, they are usually right to do so ;) E.g. you define an odd `alpaka::Complex<Float3>`, You may have 4 bytes padding between those two, which may be required by some architectures, so forcing packing could violate alignment requirements.
 
Furthermore, I am sure the quote from cppreference does not concern anything else than `std::complex` for `float`, `double` and `long double`. And for those types we should also be safe in alpaka.

In that sense, I think this issue an be closed.
