### ISSUE TITLE
Allow temporary destination views in `alpaka::memcpy`

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/alpaka#1742]
Alpaka's memcpy is specified as:
```c++
template<typename TViewSrc, typename TViewDst, typename TQueue>
auto memcpy(TQueue& queue, TViewDst& viewDst, TViewSrc const& viewSrc) -> void;
```
Because the `viewDst` parameter is taken by reference, one cannot pass temporaries:
```c++
alpaka::memcpy(queue, alpaka::createView(dev, pointer, size), srcView); // compilation error
```
If we would take the destination parameter by forwarding reference instead, this would work, which is a nice usability improvement over:
```c++
auto dstView = alpaka::createView(dev, pointer, size);
alpaka::memcpy(queue, dstView, srcView); // works
```

**Comment by sbastrakov** [comment]
I think this change would be fine.

For the sake of experiment if instead of a forwarding reference one just made it a `const` reference for `viewDst`, would it also technically work? (Ofc it's not what we should do)

**Comment by bernhardmgruber** [comment]
> For the sake of experiment if instead of a forwarding reference one just made it a const reference for viewDst, would it also technically work

I would guess so, because alpaka buffers don't propagate their own constness to their content, as pointed out in: #1729.
