### ISSUE TITLE
Switch CMP0091 to NEW

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/alpaka#1744]
When I configure alpaka on Windows, I get this warning:
```
 CMake Deprecation Warning at CMakeLists.txt:16 (cmake_policy):
   The OLD behavior for policy CMP0091 will be removed from a future version
   of CMake.

   The cmake-policies(7) manual explains that the OLD behaviors of all
   policies are deprecated and that a policy should be set to OLD only under
   specific short-term circumstances.  Projects should be ported to the NEW
   behavior and not rely on setting a policy to OLD.
```
Because alpaka sets: `cmake_policy(SET CMP0091 OLD)`.

We should migrate to the new behavior of cmake and remove the line causing the warning.

**Comment by bernhardmgruber** [comment]
I removed the Windows label, because I actually get this error in WSL.

**Comment by j-stephan** [comment]
While the warning is triggered on all platforms this policy only affects MSVC. So the label was okay.

This also means that this should be worked on by a Windows user who can compile & run the test suite.
