### ISSUE TITLE
[RFC] Mark CATCH cmake variables as advanced

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/alpaka#1758]
I just noticed that we got a lot of cmake variables from Catch2 in the default view of `ccmake`:
![image](https://user-images.githubusercontent.com/1224051/176668711-0b9f836c-363d-438b-8d9e-1f1c48a7c4c5.png)

Since I don't think that we should tamper with these variables, I would like to mark them as advanced in cmake, so they are hidden by default.

**Comment by j-stephan** [comment]
I don't think this is the right approach. We should probably use `ExternalProject`(https://cmake.org/cmake/help/v3.18/module/ExternalProject.html) instead.

**Comment by bernhardmgruber** [comment]
If that gets rid of the `CATCH_*` cmake variables, I am all for it!

**Comment by bernhardmgruber** [comment]
@j-stephan are you going to do the thing with `ExternalProject`? If not, are you fine with my suggested approach? If not, then I would close the issue.

**Comment by j-stephan** [comment]
Not right now, but I'm still for trying out `ExternalProject`. Shouldn't be that hard I think.

**Comment by bernhardmgruber** [comment]
Ok then, go for it! :)

**Comment by j-stephan** [comment]
I just tried it with `FetchContent` which should be really similar to `ExternalProject`. The variables still show up in `ccmake` so feel free to try out your approach.
