### ISSUE TITLE
rename traits to trait

### ISSUE THREAD

**Issue by BenjaminW3** [alpaka-group/alpaka#179]
All namespaces within alpaka are singular to shorten the names and make the code clearer. The only exception violating the coding guide lines is the `traits` namespace. Therefore I suggest to rename it to `trait` and remove thousands of `s` from the code base.
This would make the trait call sites look more natural because it would be e.g. `stream::trait::Enqueue` instead of `stream::traits::Enqueue`.

**Comment by bernhardmgruber** [comment]
Since most traits are spelled in CamelCase and functions at least lower case, I would also be fine with removing the `traits` namespaces entirely. `alpaka::enqueue()` would be the functionality, and `alpaka::Enqueue` would be the customization point.
