### ISSUE TITLE
add special kernel methods

### ISSUE THREAD

**Issue by BenjaminW3** [alpaka-group/alpaka#18]
- [x] ~~clock_t clock();
  long long int clock64();~~
- [ ] T __ldg(const T\* address);
  The read-only data cache load function is only supported by devices of compute capability 3.5 and higher.
- [x] __shfl_sync, __shfl_up_sync, __shfl_down_sync, __shfl_xor_sync
  Exchange a variable between threads within a warp.

**Comment by felicepantaleo** [comment]
just checking if there is any plan on this

**Comment by psychocoderHPC** [comment]
> just checking if there is any plan on this

You increased the priority for this features by +1

**Comment by BenjaminW3** [comment]
Are you more interested in ldg or shfl?

**Comment by psychocoderHPC** [comment]
The request in our internal Mattermost was for `__ballot_sync()` and `__shfl_up_sync()`. I also see  shuffle as more important as `__ldg()`

Note: CUDA has `__ballot` (asynchronous) and `__ballot_sync()`

**Comment by j-stephan** [comment]
We will implement these intrinsics for alpaka 0.7.0.

* Implementing `__ldg` assigned to @j-stephan (as part of #38).
* Implementing `__shfl` assigned to @sbastrakov.

**Comment by sbastrakov** [comment]
The shuffle part was implemented in #1273 (not by me, but it's now in).

**Comment by j-stephan** [comment]
2/3 of the methods mentioned here have already been implemented. The remaining functionality will be tracked in #1312 (for easier project management).
