### ISSUE TITLE
Upgrade  linux_clang-9_cuda-9.2_debug_analysis CI check

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/alpaka#1802]
Because it emits this wrong diagnostic:
```
/home/runner/work/alpaka/alpaka/example/bufferCopy/src/bufferCopy.cpp:64:29: error: reference to __host__ function '<deduction guide for Vec><unsigned long, unsigned long, unsigned long>' in __host__ __device__ function
                            alpaka::Vec{z, y, x},
                            ^
/home/runner/work/alpaka/alpaka/include/alpaka/vec/Vec.hpp:440:5: note: '<deduction guide for Vec><unsigned long, unsigned long, unsigned long>' declared here
    Vec(TFirstIndex, TRestIndices...) -> Vec<DimInt<1 + sizeof...(TRestIndices)>, TFirstIndex>;
    ^
```
which is technically correct, since deduction guides are evaluated via a synthesized function template, but still wrong and not useful, since this function template would never be codegen-ed.

I propose to move to a newer clang and CUDA version.

**Comment by psychocoderHPC** [comment]
I support removing cuda.9.2 and therefore clang 9 support to reduce the maintenance overhead and avoid adding workarounds for this old compiler/CUDA version!

**Comment by SimeonEhrig** [comment]
I agree. CUDA 9.2 is over 4 years old and in the mean time, 10 versions released.

**Comment by j-stephan** [comment]
https://www.youtube.com/watch?v=BkIJsnLBA4c

**Comment by bernhardmgruber** [comment]
> https://www.youtube.com/watch?v=BkIJsnLBA4c

Haha, this is even better: https://www.youtube.com/watch?v=dQw4w9WgXcQ

**Comment by SimeonEhrig** [comment]
> > https://www.youtube.com/watch?v=BkIJsnLBA4c
> 
> Haha, this is even better: https://www.youtube.com/watch?v=dQw4w9WgXcQ

Luckily I open each posted youtube link in a private tab, otherwise my youtube prediction would be destroyed now :joy:

**Comment by j-stephan** [comment]
> I propose to move to a newer clang and CUDA version.

If I'm not mistaken we already test several clang-as-CUDA-compiler combinations in our CI. The only reason we kept this combination is because it supports C++17 and there was therefore no immediate reason to remove it. So I don't think we need to upgrade this job, we can just remove it.

**Comment by bernhardmgruber** [comment]
@j-stephan The job I am talking about is one of the analysis runs, for which we only have this one combination with clang/CUDA.

**Comment by j-stephan** [comment]
Ah, my bad then.
