### ISSUE TITLE
Unspecified Launch Failure

### ISSUE THREAD

**Issue by GNiendorf** [alpaka-group/alpaka#1806]
I'm trying to incorporate alpaka code into a project that is currently written with CUDA, with the hope of eventually rewriting it in alpaka completely. Right now I'm trying to run the "Hello World" example in one of my .cu files to verify that I can run alpaka code alongside my CUDA code. The code compiles fine, but I get a very obscure error when I try to run it:

terminate called after throwing an instance of 'std::runtime_error'
  what():  /alpaka_install/include/alpaka/queue/cuda_hip/QueueUniformCudaHipRtBase.hpp(172) 'cudaStreamSynchronize_ptsz(queue.m_spQueueImpl->m_UniformCudaHipQueue)' A previous API call (not this one) set the error  : 'cudaErrorLaunchFailure': 'unspecified launch failure'!

I tried using cuda-gdb to debug this, but I get another very strange error about breakpoints in a random .cu file for my project, even though I have no breakpoints in my code:

Thread 1 "sdl" received signal SIGTRAP, Trace/breakpoint trap.
[Switching focus to CUDA kernel 0, grid 1, block (0,0,0), thread (0,0,0), device 0, sm 0, warp 0, lane 0]
0x000000001700a2b0 in alpaka::uniform_cuda_hip::detail::uniformCudaHipKernel<alpaka::AccGpuCudaRt<std::integral_constant<unsigned long, 3ul>, unsigned long>, std::integral_constant<unsigned long, 3ul>, unsigned long, HelloWorldKernel><<<(1,1,1),(8,8,8)>>> () at /current_project/some_random_file.cu:188

If I run "continue" after I get this message from cuda-gdb, my code runs fine but I get no output from the Hello World kernel. See below for the alpaka debug output.

**Comment by GNiendorf** [comment]
Alpaka debug tool gives more info:

createTaskKernel workDiv: {gridBlockExtent: (1, 1, 1), blockThreadExtent: (8, 8, 8), threadElemExtent: (1, 1, 1)}, kernelFnObj: 16HelloWorldKernel
[+] enqueue
enqueuegridDim: 1 1 1
enqueueblockDim: 8 8 8
enqueue BlockSharedMemDynSizeBytes: 0 B
enqueue binaryVersion: 70 constSizeBytes: 72 B localSizeBytes: 0 B maxThreadsPerBlock: 1024 numRegs: 4 ptxVersion: 70 sharedSizeBytes: 0 B
/cvmfs/cms.cern.ch/slc7_amd64_gcc11/external/alpaka/0.7.0-d5ab0d4e08895a8cfa5d7cc754e926f9/include/alpaka/kernel/TaskKernelGpuUniformCudaHipRt.hpp(433) 'execution of kernel: '16HelloWorldKernel' failed with : 'cudaErrorLaunchFailure': 'unspecified launch failure'!

 *** Break *** illegal instruction

There was a crash.
This is the entire stack trace of all threads:

Thread 3 (Thread 0x7fb93e424700 (LWP 87442)):
#0  0x00007fb95789eccd in poll () from /lib64/libc.so.6
#1  0x00007fb940444b11 in ?? () from /lib64/libcuda.so.1
#2  0x00007fb9404ceb5a in ?? () from /lib64/libcuda.so.1
#3  0x00007fb940413f46 in ?? () from /lib64/libcuda.so.1
#4  0x00007fb957b80ea5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007fb9578a99fd in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x7fb93ec25700 (LWP 87441)):
#0  0x00007fb9578aae8f in accept4 () from /lib64/libc.so.6
#1  0x00007fb940444243 in ?? () from /lib64/libcuda.so.1
#2  0x00007fb940413f46 in ?? () from /lib64/libcuda.so.1
#3  0x00007fb957b80ea5 in start_thread () from /lib64/libpthread.so.0
#4  0x00007fb9578a99fd in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7fb954cb6600 (LWP 87207)):
#0  0x00007fb957870549 in waitpid () from /lib64/libc.so.6
#1  0x00007fb9577edfb2 in do_system () from /lib64/libc.so.6
#2  0x00007fb9577ee361 in system () from /lib64/libc.so.6
#3  0x00007fb95a661b85 in TUnixSystem::StackTrace() () from /cvmfs/cms.cern.ch/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_2_0_pre5/external/slc7_amd64_gcc900/lib/libCore.so
#4  0x00007fb95a65ebdc in TUnixSystem::DispatchSignals(ESignals) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_2_0_pre5/external/slc7_amd64_gcc900/lib/libCore.so
#5  <signal handler called>
#6  alpaka::uniform_cuda_hip::detail::rtCheck (error=
0x7ffc213ec71c: cudaErrorLaunchFailure, desc=0x21d87c90 "'execution of kernel: '16HelloWorldKernel' failed with", file=0x7fb95a86dba8 "/cvmfs/cms.cern.ch/slc7_amd64_gcc11/external/alpaka/0.7.0-d5ab0d4e08895a8cfa5d7cc754e926f9/include/alpaka/kernel/TaskKernelGpuUniformCudaHipRt.hpp", line=
0x7ffc213ec98c: 433) at /cvmfs/cms.cern.ch/slc7_amd64_gcc11/external/alpaka/0.7.0-d5ab0d4e08895a8cfa5d7cc754e926f9/include/alpaka/core/UniformCudaHip.hpp:64
#7  0x00007fb95a84b7b2 in alpaka::uniform_cuda_hip::detail::rtCheckLastError (desc=0x21d87c90 "'execution of kernel: '16HelloWorldKernel' failed with", file=0x7fb95a86dba8 "/cvmfs/cms.cern.ch/slc7_amd64_gcc11/external/alpaka/0.7.0-d5ab0d4e08895a8cfa5d7cc754e926f9/include/alpaka/kernel/TaskKernelGpuUniformCudaHipRt.hpp", line=
0x7ffc213ec98c: 433) at /cvmfs/cms.cern.ch/slc7_amd64_gcc11/external/alpaka/0.7.0-d5ab0d4e08895a8cfa5d7cc754e926f9/include/alpaka/core/UniformCudaHip.hpp:101
#8  0x00007fb95a85148e in alpaka::traits::Enqueue<alpaka::QueueUniformCudaHipRtBlocking, alpaka::TaskKernelGpuUniformCudaHipRt<alpaka::AccGpuCudaRt<std::integral_constant<unsigned long, 3ul>, unsigned long>, std::integral_constant<unsigned long, 3ul>, unsigned long, HelloWorldKernel>, void>::enqueue (queue=..., task=...) at /cvmfs/cms.cern.ch/slc7_amd64_gcc11/external/alpaka/0.7.0-d5ab0d4e08895a8cfa5d7cc754e926f9/include/alpaka/kernel/TaskKernelGpuUniformCudaHipRt.hpp:433
#9  0x00007fb95a84f458 in alpaka::enqueue<alpaka::QueueUniformCudaHipRtBlocking, alpaka::TaskKernelGpuUniformCudaHipRt<alpaka::AccGpuCudaRt<std::integral_constant<unsigned long, 3ul>, unsigned long>, std::integral_constant<unsigned long, 3ul>, unsigned long, HelloWorldKernel> > (queue=..., task=...) at /cvmfs/cms.cern.ch/slc7_amd64_gcc11/external/alpaka/0.7.0-d5ab0d4e08895a8cfa5d7cc754e926f9/include/alpaka/queue/Traits.hpp:48
#10 0x00007fb95a84dd1d in alpaka::exec<alpaka::AccGpuCudaRt<std::integral_constant<unsigned long, 3ul>, unsigned long>, alpaka::QueueUniformCudaHipRtBlocking, alpaka::WorkDivMembers<std::integral_constant<unsigned long, 3ul>, unsigned long>, HelloWorldKernel> (queue=..., workDiv=..., kernelFnObj=...) at /cvmfs/cms.cern.ch/slc7_amd64_gcc11/external/alpaka/0.7.0-d5ab0d4e08895a8cfa5d7cc754e926f9/include/alpaka/kernel/Traits.hpp:277

**Comment by psychocoderHPC** [comment]
@GNiendorf welcome to the alpaka community.
Could you please attach your alpaka hello world which is producing the error as zip to this issue?

**Comment by GNiendorf** [comment]
Sorry for the delay, I figured it out. I needed to add the following flags to my Makefile. I initially had the first two flags, but when I added the third flag everything worked perfectly.

-DALPAKA_ACC_GPU_CUDA_ENABLED -DALPAKA_ACC_GPU_CUDA_ONLY  --expt-relaxed-constexpr
