### ISSUE TITLE
OpenMP broken on MacOS

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/alpaka#1821]
A recent change to the GitHub MacOS runners seems to have broken compilation when OpenMP is needed. See for example: https://github.com/alpaka-group/alpaka/actions/runs/3351786152/jobs/5553478006#step:5:2386

```
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_CXX_FOUND) 
CMake Error at cmake/alpakaCommon.cmake:391 (message):
  Optional alpaka dependency OpenMP could not be found!
-- Configuring incomplete, errors occurred!
```

I have the same issue in LLAMA btw.

**Comment by psychocoderHPC** [comment]
similar to https://github.com/microsoft/LightGBM/issues/1898

**Comment by psychocoderHPC** [comment]
I removed the required flag for the macosx jobs. This means we run the CI for MACOSX but there is no need anymore that these jobs to pass.

**WARNING** This means we have no code coverage for MACOSX anymore!

**Comment by bernhardmgruber** [comment]
I fixed it in LLAMA btw, by installing `llvm` from homebrew and using their clang instead of AppleClang.

**Comment by psychocoderHPC** [comment]
I was on the way to increasing the CMake version for our MACOSX CI tests but I do not know how. It looks like CMake is pre-installed in the image or so.

**Comment by SimeonEhrig** [comment]
I think also. I didn't found a macos install path [install_cmake.sh](https://github.com/alpaka-group/alpaka/blob/develop/script/install_cmake.sh). Here is the tools list of the macos image: https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md

It contains already CMake 3.24.2, which is nearly the latest release (current 3.24.3). The patch notes does not name any openmp fix for openmp: https://cmake.org/cmake/help/v3.24/release/3.24.html#id2

**Comment by psychocoderHPC** [comment]
CMake should support the apple clang since 3.12 if I read this issue and the linked PRs correctly https://gitlab.kitware.com/cmake/cmake/-/issues/18520

**Comment by psychocoderHPC** [comment]
This is a suggested workaround :-( https://github.com/oneapi-src/oneDNN/issues/591#issuecomment-552293435

**Comment by psychocoderHPC** [comment]
Since #1840 was not solving the MACOSX CI issues I disabled the OpenMP backend in our CI for MACOSX tests #1840.

Switching to llvm is possible but until then we should accept #1840 to avoid that we run too long with failing tests.

**Comment by j-stephan** [comment]
Apparently we need to build `libomp` ourselves on macOS to make this work: https://github.com/actions/runner-images/issues/5555#issuecomment-1140192622

**Comment by bernhardmgruber** [comment]
> Apparently we need to build `libomp` ourselves on macOS to make this work: [actions/runner-images#5555 (comment)](https://github.com/actions/runner-images/issues/5555#issuecomment-1140192622)

I would rather just take clang from `brew` and limit support to the latest clang available there. That is good enough to develop on MacOS for those interested and limits our maintenance effort. Alternatively, we could consider ending support for MacOS.
