### ISSUE TITLE
No Hyperbolic Functions?

### ISSUE THREAD

**Issue by GNiendorf** [alpaka-group/alpaka#1827]
Does Alpaka have implementations of hyperbolic functions (cosh, sinh, acosh, asinh, etc.)? If not, are there any plans to support them or advice on how to get around this? I know CUDA has hyperbolic functions in their math library for example. My thought right now is to implement my own device function that calculates acosh(x) (the function I need) using the other alpaka math functions, but this probably isn't the best approach given that CUDA and others have direct implementations of these hyperbolic functions.

Thank you!

**Comment by psychocoderHPC** [comment]
At the moment we do not have hyperbolic math functions in alpaka.
Until now there was no plan to add these functions but the world looks different with your issue. 
We will discuss this issue in the next alpaka developer meeting.
You can find supported functions https://github.com/alpaka-group/alpaka/blob/develop/include/alpaka/math/Traits.hpp

**Comment by psychocoderHPC** [comment]
A PR should be ready today.

**Comment by psychocoderHPC** [comment]
I opened #1828 to add hyperbolic math functions.

**Comment by GNiendorf** [comment]
Thank you for the quick fix!
