### ISSUE TITLE
Possible to end up with no backend configured (CMake)

### ISSUE THREAD

**Issue by StewMH** [alpaka-group/alpaka#1836]
By running CMake twice:
```
cmake ../alpaka/ -DCMAKE_BUILD_TYPE=Release
cmake ../alpaka/ -Dalpaka_BUILD_EXAMPLES=ON -DCMAKE_BUILD_TYPE=Release
```
I managed to end up with no backend configured, and a lot of (initially) puzzling compiler errors:
```shell
In file included from alpaka/example/randomStrategies/src/randomStrategies.cpp:11:
alpaka/include/alpaka/example/ExampleDefaultAcc.hpp:60:6: warning: #warning "No supported backend selected." [-Wcpp]
   60 | #    warning "No supported backend selected."
```
```
In file included from alpaka/include/alpaka/acc/Traits.hpp:14,
                 from alpaka/include/alpaka/alpaka.hpp:35,
                 from alpaka/example/randomStrategies/src/randomStrategies.cpp:10:
alpaka/include/alpaka/core/Concepts.hpp: In instantiation of 'constexpr const auto alpaka::concepts::ImplementsConcept<alpaka::ConceptAcc, alpaka::ExampleDefaultAcc<std::integral_constant<long unsigned int, 1>, long unsigned int> >::
alpaka/include/alpaka/queue/Traits.hpp:69:11:   recursively required by substitution of 'template<class TAcc, class TProperty> struct alpaka::trait::QueueType<TAcc, TProperty, typename std::enable_if<alpaka::concepts::ImplementsConce
alpaka/include/alpaka/queue/Traits.hpp:69:11:   required by substitution of 'template<class TEnv, class TProperty> using Queue = typename alpaka::trait::QueueType<TEnv, TProperty>::type [with TEnv = alpaka::ExampleDefaultAcc<std::int
alpaka/example/randomStrategies/src/randomStrategies.cpp:42:54:   required from here
alpaka/include/alpaka/core/Concepts.hpp:31:58: error: invalid use of incomplete type 'class alpaka::ExampleDefaultAcc<std::integral_constant<long unsigned int, 1>, long unsigned int>'
   31 |         static constexpr auto value = decltype(implements(std::declval<TDerived&>()))::value;
```

I see that the serial backend is enabled if unset (for builds/tests):
```cmake
# the sequential accelerator is required for the tests and examples
if(NOT DEFINED alpaka_ACC_CPU_B_SEQ_T_SEQ_ENABLE AND (alpaka_BUILD_EXAMPLES OR BUILD_TESTING))
  option(alpaka_ACC_CPU_B_SEQ_T_SEQ_ENABLE "enable alpaka serial accelerator" ON)
endif()
```
https://github.com/alpaka-group/alpaka/blob/develop/CMakeLists.txt#L83

so perhaps the solution is to change this to:
```cmake
# the sequential accelerator is required for the tests and examples
if ((alpaka_BUILD_EXAMPLES OR BUILD_TESTING))
  message("Sequential accelerator is required for the tests and examples")
  option(alpaka_ACC_CPU_B_SEQ_T_SEQ_ENABLE "enable alpaka serial accelerator" ON)
endif()
```

but perhaps there is a usecase I am missing.

Best regards,

Stewart

**Comment by psychocoderHPC** [comment]
Thanks for the report.

I think your suggestion is valid. I would use WARNING for the message

```
message(WARNING "Sequential accelerator is required for the tests and examples")
```

@StewMH Do you like to open a PR with your suggestion?

**Comment by StewMH** [comment]
Sure, I will do this.

**Comment by StewMH** [comment]
OK, harder than I thought - once set, CMake options are immutable.

Two ways out:
1)exit with fatal error
```
# the sequential accelerator is required for the tests and examples
if(alpaka_BUILD_EXAMPLES OR BUILD_TESTING)
  if (NOT DEFINED alpaka_ACC_CPU_B_SEQ_T_SEQ_ENABLE)
    option(alpaka_ACC_CPU_B_SEQ_T_SEQ_ENABLE "enable alpaka serial accelerator" ON)
  elseif(NOT alpaka_ACC_CPU_B_SEQ_T_SEQ_ENABLE)
    message(FATAL_ERROR "Serial backend must be enabled for tests and examples: delete CMakeCache.txt and rerun CMake command")
  endif()
endif()
```

2)Use set() rather than option(), which goes against good CMake practice.

Could also leave as is.

**Comment by psychocoderHPC** [comment]
You can force change the CMake option with `option(alpaka_ACC_CPU_B_SEQ_T_SEQ_ENABLE "enable alpaka serial accelerator" ON FORCE)`

**Comment by StewMH** [comment]
This does not seem to work:
```
CMake Error at CMakeLists.txt:95 (option):
  option called with incorrect number of arguments:
  alpaka_ACC_CPU_B_SEQ_T_SEQ_ENABLE enable alpaka serial accelerator ON FORCE
```
I don't think FORCE is possible for option.

**Comment by psychocoderHPC** [comment]
> This does not seem to work:
> 
> ```
> CMake Error at CMakeLists.txt:95 (option):
>   option called with incorrect number of arguments:
>   alpaka_ACC_CPU_B_SEQ_T_SEQ_ENABLE enable alpaka serial accelerator ON FORCE
> ```
> 
> I don't think FORCE is possible for option.

Sry you are right I mixed it with `set`. In this case IMO our solution 1. https://github.com/alpaka-group/alpaka/issues/1836#issuecomment-1309074666 is better than keeping it as it is to avoid the ugly hard to understand error during compile time.

**Comment by bernhardmgruber** [comment]
Since I run into the same issue quite often (I successfully configure and then fail the build at some later point), can we just fail the cmake configure with a fatal error when no backend is selected? This would need to be a bit smarter, since it should be possible to configure and install without any backend selected. Maybe we could run this check when cmake runs `find_package(alpaka)`?

**Comment by StewMH** [comment]
@bernhardmgruber it's easy to require a backend, e.g.
```cmake
#Must enable at least one backend to proceed
if (NOT (alpaka_ACC_GPU_CUDA_ENABLE OR
         alpaka_ACC_GPU_HIP_ENABLE OR
         alpaka_ACC_CPU_B_SEQ_T_SEQ_ENABLE OR
         alpaka_ACC_CPU_B_SEQ_T_THREADS_ENABLE OR
         alpaka_ACC_CPU_B_SEQ_T_FIBERS_ENABLE OR
         alpaka_ACC_CPU_B_TBB_T_SEQ_ENABLE OR
         alpaka_ACC_CPU_B_OMP2_T_SEQ_ENABLE OR
         alpaka_ACC_CPU_B_SEQ_T_OMP2_ENABLE OR
         alpaka_ACC_ANY_BT_OMP5_ENABLE OR
         alpaka_ACC_ANY_BT_OACC_ENABLE OR
         alpaka_ACC_CPU_DISABLE_ATOMIC_REF OR
         alpaka_ACC_SYCL_ENABLE ) )
    message(FATAL_ERROR "No backend selected\n add e.g. '-Dalpaka_ACC_GPU_CUDA_ENABLE=ON' (CUDA) or '-Dalpaka_ACC_CPU_B_SEQ_T_SEQ_ENABLE=ON' (serial)\n to CMake command")
endif()
```
in `alpakaCommon.cmake`, but not clear to me how you would allow this in the configure + install case.

**Comment by bernhardmgruber** [comment]
> in alpakaCommon.cmake, but not clear to me how you would allow this in the configure + install case.

Exactly, because I still want to clone alpaka, configure and install without enabling an accelerator (which maybe needs more dependencies).

**Comment by StewMH** [comment]
Hi @bernhardmgruber, I didn't have any other bright ideas, so I opened a PR with a solution for not managing to build the tests/examples.

**Comment by bernhardmgruber** [comment]
@StewMH and that is totally fine! Let's discuss there!
