### ISSUE TITLE
check minimum dependencies e.g. boost in header

### ISSUE THREAD

**Issue by psychocoderHPC** [alpaka-group/alpaka#1856]
In cases, Cmake has not used the minimum required boost version is not checked in the code.
At least in cases where the stand alone headers are used the boost version should be checked.

see:  [CMake has not used](https://github.com/alpaka-group/alpaka/pull/1849#issuecomment-1333732481)

**Comment by bernhardmgruber** [comment]
Isn't this a duplicate of #1636?

**Comment by j-stephan** [comment]
Yes.
