### ISSUE TITLE
`ALPAKA_FN_INLINE` is weak on CPUs

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/alpaka#1859]
Alpaka's `ALPAKA_FN_INLINE` uses `__forceinline__` for CUDA and HIP, but only `inline` on CPU targets. This may result in unnecessary function calls. I propose to turn `ALPAKA_FN_INLINE` into a forced inline as well for CPU targets.

**Comment by j-stephan** [comment]
I was looking for a reason for why this wasn't done in the first place. The issues of eons past (see #183) tell us that the split between CUDA and CPU was inherited from alpaka's predecessor in PMacc. They don't mention why the CPU version wasn't as strong, though.

@psychocoderHPC is the only remaining developer from those times. Maybe he remembers a reason for not using `always_inline` on CPUs.

**Comment by psychocoderHPC** [comment]
I do not know why we do not use a force inline for CPU. IMO it was more because we was not aware that this exists for CPU too, for GPU we used `__forceinline__` since the beginning.

I suggest switching to force inline, here is what llama is doing and at least for PIConGPU it shows good results during tests @bernhardmgruber and I did yesterday with PIConGPU+llama.

https://github.com/alpaka-group/llama/blob/e1c2426de845ac7eb4f3e706f3287c67acbf7b31/include/llama/macros.hpp#L36-L48

**Comment by bernhardmgruber** [comment]
> I do not know why we do not use a force inline for CPU. IMO it was more because we was not aware that this exists for CPU too, for GPU we used `__forceinline__` since the beginning.
> 
> I suggest switching to force inline, here is what llama is doing and at least for PIConGPU it shows good results during tests @bernhardmgruber and I did yesterday with PIConGPU+llama.

I have to correct this statement slighly. Here are a few runs of picongpu `KHI_growthRate`:
```
Baseline
8.449 sec
8.661 sec
8.289 sec

Forceinline
8.665 sec
8.590 sec
8.425 sec
```
You can see that the results are a bit shaky and that there is no immediate gain from using forceinline. Now, if we add some SIMD into the code:
```
SIMD (normal alpaka inline, no force inline)
27.283 sec
27.327 sec
27.405 sec

SIMD + forceinline in alpaka:
13.360 sec
13.456 sec
13.429 sec

SIMD + forceinline in alpaka + and a lot of forceinline inside std::simd:
8.985 sec
9.054 sec
8.989 sec
```
(you can ignore the fact that SIMD made it slower)

Suddently, the forceinline in alpaka makes a dramatic difference. In this concrete case, it was not enough and we had to add more forceinlines into the `std::simd` headers.

So I think we should have forceinline in alpaka also for CPU targets, but we should not blindly apply it everywhere. I think it makes a lot of sense for device/kernel code, so maybe we could put the CPU forceinline where we would put a `__device__` for CUDA/HIP.
