### ISSUE TITLE
Changes to GitHub Ubuntu CI runners

### ISSUE THREAD

**Issue by j-stephan** [alpaka-group/alpaka#1866]
The GitHub Ubuntu CI runners will see some changes in the near future:

* Ubuntu 18.04 is deprecated - actions/runner-images/issues/6002
* `ubuntu-latest` will switch from Ubuntu 20.04 to Ubuntu 22.04 - actions/runner-images/issues/6399

Foreseeable changes for us when upgrading from 18.04 to 20.04:

* gcc 7, 8 will come from Ubuntu's `universe` repository. 8 appears outdated (latest version is 8.5 but `universe` only has 8.4). The [PPA](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test) we used for installing more recent GCC versions appears out of date. We should consider switching to [another PPA](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/ppa) but that one unfortunately doesn't have gcc 8 or older.
* clang 6, 7, 8 will come from Ubuntu's `universe` repository since there are no official LLVM packages for these versions. 6 and 8 seem to be up to date but 7 appears outdated (7.0.1 in `universe` vs 7.1.0 in LLVM's repository for Ubuntu 18.04).

Ubuntu 18.04 will be EOL in April 2023. My suggestion:

* Drop support for gcc 7 and 8.
* Drop support for clang 6, 7, 8.
* Drop support for CUDA 10.x since it is officially only supported on Ubuntu 18.04.

**Comment by psychocoderHPC** [comment]
I support dropping a  compiler and libs you have on the list. IMO we should not move the github runners to the new version and instead use the gitlab CI.
Github runners are a leftover from old times and should migrate to GitLab except the code style check, OSX and windows jobs.

**Comment by SimeonEhrig** [comment]
I agree. gcc and clang are no-brainer and CUDA 11.0 was released in July 2020. So it should be also no problem.

**Comment by bernhardmgruber** [comment]
Do it!

**Comment by j-stephan** [comment]
@fwyzard Do you depend on any of the compilers / CUDA versions we are considering to drop here?

**Comment by fwyzard** [comment]
No, we are using GCC 10 and CUDA 11.5, soon to be GCC 11 (or 12) and CUDA 12.
Thanks for asking !
