### ISSUE TITLE
Drop legacy ROCm version

### ISSUE THREAD

**Issue by SimeonEhrig** [alpaka-group/alpaka#1873]
Addition to PR #1872 we should discuss, if we also remove some old ROCm version. For example, I would drop ROCm 4.2 because at the moment no alpaka-group-container with ROCm 4.2 for testing exists. Therefore I need to build one but I see only a small benefit.

@psychocoderHPC Do know, what minimum ROCm version the people use?

**Comment by fwyzard** [comment]
We (plan to) use ROCm 5.0.x or later.

**Comment by psychocoderHPC** [comment]
Agree 5.X should stay, please keep in mind that with 5.0 the official support for AMD targets less gfx906 was dropped.

**Comment by psychocoderHPC** [comment]
Do not forget to update the minimal ROCm version in our common CMake file.
