### ISSUE TITLE
Compile error with nvcc 12 and gcc 12

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/alpaka#1877]
When I compile the unit tests with nvcc 12 and gcc 12 I get the following error:

```
/home/bgruber/dev/alpaka/include/alpaka/test/event/EventHostManualTrigger.hpp(383): error: identifier "CU_DEVICE_ATTRIBUTE_CAN_USE_STREAM_MEM_OPS" is undefined

1 error detected in the compilation of "/home/bgruber/dev/alpaka/test/unit/event/src/EventTest.cpp".
```
Maybe this constant has been removed or moved to a different header?

**Comment by j-stephan** [comment]
It was renamed to `CU_DEVICE_ATTRIBUTE_CAN_USE_STREAM_MEM_OPS_V1` and is now deprecated. A fix is in order.
