### ISSUE TITLE
[RFC] Reduce Windows CI

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/alpaka#1879]
To reduce the maintenance effort and CI load, I suggest to reduce the tested combinations for MSVC. I would even go as far as to only support the latest version of Visual Studio (2022) with and without the latest version of nvcc. That is good enough for developing and testing on Windows, since I don't believe users are actually using Windows in production.

**Comment by SimeonEhrig** [comment]
@bernhardmgruber I suggest to let it open until new year. If nobody is against it, we simply do it.

**Comment by j-stephan** [comment]
I don't see a reason for us to wait for the new year. We don't use MSVC for productive work, as do our (known) users. I'll submit a PR that drops MSVC 2019 and the CUDA versions that don't work with MSVC 2022.

**Comment by SimeonEhrig** [comment]
Is fine. Currently @bernhardmgruber has also a problem, which is solved by dropping the compiler. So let's start.
