### ISSUE TITLE
Intel oneAPI CI broken

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/alpaka#1882]
The Intel apt repository just updated from `intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic-2022.2.1` to 2023 and now the corresponding CI jobs are failing.

**Comment by psychocoderHPC** [comment]
Could you please link which test you mean, I working on a fix for icpx CI tests, do you mean these or other tests?

**Comment by psychocoderHPC** [comment]
The issue should be fixed with https://github.com/alpaka-group/alpaka/pull/1884

One of the problems is that we sue the latest ubuntu container as a base container for the CI, this can break the CI at any time.
IMO we should use fixed OS versions only.

**Comment by bernhardmgruber** [comment]
> One of the problems is that we sue the latest ubuntu container as a base container for the CI, this can break the CI at any time.

I don't think it's the Ubuntu version, since for oneAPI, we use Intel's apt repository and they also just update as they please.

**Comment by j-stephan** [comment]
Closed by #1884.
