### ISSUE TITLE
BUILD_TESTING enables tests when alpaka is built as an external

### ISSUE THREAD

**Issue by StewMH** [alpaka-group/alpaka#1888]
While starting to integrate Alpaka into [traccc](https://github.com/acts-project/traccc/) I found that the test suite was enabled when `traccc` sets BUILD_TESTING on.

As I understand it there are two options:
1)Change `BUILD_TESTING` to e.g. `alpaka_BUILD_TESTING`

2)Something like
```
if(CMAKE_PROJECT_NAME STREQUAL PROJECT_NAME)
    include(CTest)
endif()
```
to ensure that the tests are not built.

A workaround is also possible, as is done in traccc for Eigen:
https://github.com/acts-project/traccc/blob/main/extern/eigen3/CMakeLists.txt#L26
but this is a bit ugly.

My immediate preference is for 1) - it's just find and replace in a few files:

```
CMakeLists.txt
README_OACC.md
README_OMP5.md
README_SYCL.md
cmake/alpakaCommon.cmake
docs/source/advanced/cmake.rst
docs/source/basic/install.rst
docs/source/dev/backends.rst
docs/source/dev/test.rst
script/run_generate.sh
thirdParty/CMakeLists.txt
```
but happy to go with whatever is preferred by maintainers.

**Comment by SimeonEhrig** [comment]
I can confirm the bug in [vikunja](https://github.com/alpaka-group/vikunja). Normally I use the `find_package()` approach, therefore I didn't triggered the bug.

We will discuss the issue in the begin of the next year when everybody is back from holidays.

Just as side note, I believe we decided to use `BUILD_TESTING` instead `alpaka_BUILD_TESTING` because it is more convenient. But we was not aware of this problem.

**Comment by bernhardmgruber** [comment]
How are you consuming alpaka downstream? If you acquire an installed alpaka with `find_package`, there cannot be any unit tests, since those should not be installed. If you use alpaka via `add_subdirectory`, then you could try `EXCLUDE_FROM_ALL` as last argument. At least it removes alpaka from installing with your project, maybe it removes the tests as well.

**Comment by StewMH** [comment]
This is via [FetchContent](https://github.com/acts-project/traccc/blob/main/CMakeLists.txt) so we can build everything in one step.

```cmake

# CMake include(s).
cmake_minimum_required( VERSION 3.16 )
include( FetchContent )

# Silence FetchContent warnings with CMake >=3.24.
if( POLICY CMP0135 )
   cmake_policy( SET CMP0135 NEW )
endif()
# Declare where to get Alpaka from.
set( TRACCC_ALPAKA_SOURCE
   "URL;https://github.com/alpaka-group/alpaka/archive/refs/tags/0.9.0.tar.gz;URL_MD5;eebc14d31d55cc5474d2f9474a64b742"
   CACHE STRING "Source for Alpaka, when built as part of this project" )
mark_as_advanced( TRACCC_ALPAKA_SOURCE )
FetchContent_Declare( Alpaka ${TRACCC_ALPAKA_SOURCE} )

# Default options for the Alpaka build.
set( alpaka_ACC_CPU_B_SEQ_T_SEQ_ENABLE TRUE CACHE BOOL
   "Enable the serial backend of Alpaka" )

#Turn off build testing
if( DEFINED CACHE{BUILD_TESTING} )
   set( _buildTestingValue ${BUILD_TESTING} )
endif()
set( BUILD_TESTING FALSE CACHE INTERNAL "Forceful setting of BUILD_TESTING" )

# Get it into the current directory.
FetchContent_MakeAvailable( Alpaka )

# Reset the BUILD_TESTING variable.
if( DEFINED _buildTestingValue )
   set( BUILD_TESTING ${_buildTestingValue} CACHE BOOL "Turn tests on/off"
      FORCE )
   unset( _buildTestingValue )
else()
   unset( BUILD_TESTING CACHE )
endif()
```

**Comment by bernhardmgruber** [comment]
If I replace your cmake script with:
```cmake
include(FetchContent)

set( TRACCC_ALPAKA_SOURCE
   "URL;https://github.com/alpaka-group/alpaka/archive/refs/tags/0.9.0.tar.gz;URL_MD5;eebc14d31d55cc5474d2f9474a64b742"
   CACHE STRING "Source for Alpaka, when built as part of this project" )
mark_as_advanced( TRACCC_ALPAKA_SOURCE )
FetchContent_Declare( alpaka ${TRACCC_ALPAKA_SOURCE} )

# Default options for the Alpaka build.
set( alpaka_ACC_CPU_B_SEQ_T_SEQ_ENABLE TRUE CACHE BOOL
   "Enable the serial backend of Alpaka" )

FetchContent_GetProperties(alpaka)
if(NOT alpaka_POPULATED)
  FetchContent_Populate(alpaka)
  add_subdirectory(${alpaka_SOURCE_DIR} ${alpaka_BINARY_DIR} EXCLUDE_FROM_ALL)
endif()
```
then it works. The key is to replace `FetchContent_MakeAvailable` by `FetchContent_Populate` and `add_subdirectory` with `EXCLUDE_FROM_ALL`.

See also this discussion: https://discourse.cmake.org/t/how-to-use-fetchcontent-correctly-for-building-external-dependencies/3686

**Comment by bernhardmgruber** [comment]
@StewMH did my suggestions resolve your issue?

**Comment by StewMH** [comment]
Hi @bernhardmgruber, I think @krasznaa wanted to take a closer look at this. We should be able to conclude soon.
