### ISSUE TITLE
Clang as CUDA compiler requires CMake 3.19

### ISSUE THREAD

**Issue by SimeonEhrig** [alpaka-group/alpaka#1905]
CMake 3.18 has initial support for Clang as CUDA compiler but a bug causes an error, if `CMAKE_CUDA_ARCHITECTURES` is set. The bug is solved with CMake 3.19.

https://gitlab.com/hzdr/crp/alpaka/-/pipelines/749183469

I think we should handle the problem in the same way, like issue #1892

**Comment by j-stephan** [comment]
I wanted to raise the required CMake version for a while now: #1509. Maybe now we can consider this?

**Comment by SimeonEhrig** [comment]
I think, this makes sense. Now, we have Ubuntu 22.04 LTS with CMake 3.22 as current Ubuntu LTS.
