### ISSUE TITLE
Clang 15 as CUDA compiler does not work (at least for the test cases)

### ISSUE THREAD

**Issue by SimeonEhrig** [alpaka-group/alpaka#1906]
If Clang 15 is set as CUDA compiler, it fails at compiling Catch2.

https://gitlab.com/hzdr/crp/alpaka/-/jobs/3613272972

**Comment by bernhardmgruber** [comment]
clang-16 btw works fine as CUDA compiler. I have it in LLAMA since yesterday.

**Comment by j-stephan** [comment]
Is this still an issue?

**Comment by j-stephan** [comment]
It is. I just noticed that the clang-cuda-15 jobs linked here fail with the same error message as the clang-cuda-16 jobs in #1971. This is an issue in LLVM when compiling in debug mode: https://github.com/llvm/llvm-project/issues/58491

**Comment by SimeonEhrig** [comment]
Clang does not provide patch releases for older major releases, than the current release. If the bug will be fixed, it will requires at least the upcoming release of  Clang 17. Because our CI filter rule does not disable the debug build for up coming major releases, it will automatically test the debug build, if we add a new major version.

**Comment by j-stephan** [comment]
FYI, this has finally been fixed in LLVM: https://github.com/llvm/llvm-project/issues/58491#event-14791915581
