### ISSUE TITLE
Error When Putting Threads Along X Dimension?

### ISSUE THREAD

**Issue by GNiendorf** [alpaka-group/alpaka#1925]
I have a 3D grid/thread space that I am using. My grid/thread space only makes use of one axis though. If I try to put my threads along the X axis I get the following error shown below. If I instead put my threads along the Z axis everything runs fine. I noticed that the automatic workdiv finder also puts threads along the Z axis. Is there a reason why putting the threads along the X axis should throw this error? Thank you in advance!:

createTaskKernel workDiv: {gridBlockExtent: (80, 1, 1), blockThreadExtent: (256, 1, 1), threadElemExtent: (1, 1, 1)}, kernelFnObj: 13hitLoopKernel
[+] enqueue
enqueue gridDim: 80 1 1 blockDim: 256 1 1
[-] enqueue
[+] ~QueueUniformCudaHipRtImpl
terminate called after throwing an instance of 'std::runtime_error'
[-] ~QueueUniformCudaHipRtImpl
what(): The given work division is not valid or not supported by the device of type AccGpuUniformCudaHipRt<3,m>!

**Comment by fwyzard** [comment]
Hi Gavin,
for a 3D work division, the indices 0, 1, 2 correspond to the CUDA dimensions z, y, x - not x, y, z.

So a block size of (80, 1, 1) means x=1, y=1, z=80.

And I think that fails because CUDA supports only a block size up to 64 in the z dimension.

**Comment by GNiendorf** [comment]
Thank you!
