### ISSUE TITLE
BabelStream error

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/alpaka#1933]
Running Babelstream with a workingset of 6.4 GB on a V100 with 32GB memory produces the following error:
```
bash-4.2$ make babelstream && ./example/babelstream/babelstream -s 268435456
[100%] Built target babelstream
BabelStream
Version: 4.0
Implementation: alpaka
Running kernels 100 times
Precision: double
Array size: 2147.5 MB (=2.1 GB)
Total size: 6442.5 MB (=6.4 GB)
Using alpaka device Tesla V100-SXM2-32GB
terminate called after throwing an instance of 'std::runtime_error'
  what():  /home/bg143886/alpaka/include/alpaka/mem/buf/uniformCudaHip/Copy.hpp(161) 'TApi::memcpyAsync( m_dstMemNative, m_srcMemNative, static_cast<std::size_t>(m_extentWidthBytes), m_uniformMemCpyKind, queue.getNativeHandle())' returned error  : 'cudaErrorInvalidValue': 'invalid argument'!
Aborted
```
This seems odd, since the allocated memory is far less then what the GPU has available.

**Comment by bernhardmgruber** [comment]
I think I found the issue. The benchmark uses `int` to store the size of the array, `268435456` = `2^28`, which is fine to hold the number of elements, but the alpaka buffers also use `int` to deal with sizes in bytes. If the element type of the benchmark is `double`, the array size in bytes is `2^31`, which can no longer be represented in an `int`. I suggest to change the data type for array and buffer size to at least a 64bit data type.

**Comment by j-stephan** [comment]
I looked into our implementation of `memcpy` for CUDA devices. This is a bug in the `async` copy implementation: The amount of bytes is calculated first (possibly being of type `int`) and only casted to `size_t` afterwards.

**Comment by j-stephan** [comment]
@bernhardmgruber If you find the time please check whether #2056 fixes the issue.

**Comment by bernhardmgruber** [comment]
> @bernhardmgruber If you find the time please check whether #2056 fixes the issue.

Your changes fix the issue, thx!
