### ISSUE TITLE
Add SYCL compiler flags when backend is enabled

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/alpaka#1935]
Compiling with `dpcpp` and the SYCL backend enabled, I get the following warning, turned into an error:
`icpx: error: use of 'dpcpp' is deprecated and will be removed in a future release. Use 'icpx -fsycl' [-Werror,-Wdeprecated]`

If `dpcpp` is being deprecated, we should also react in our own cmake scripts and include `-fsycl` when the SYCL backend is enabled and `icpx` is used as compiler.

**Comment by j-stephan** [comment]
> If dpcpp is being deprecated, we should also react in our own cmake scripts and include -fsycl when the SYCL backend is enabled and icpx is used as compiler.

We already assume that the SYCL compiler is something based on `icpx`. `-fsycl` is always added when the SYCL back-end is enabled.

**Comment by j-stephan** [comment]
But since we are now using CMake 3.22 we should have native support for `IntelLLVM` inside CMake. This could reduce the amount of CMake flags required for SYCL a bit.
