### ISSUE TITLE
Using Shared Memory in Alpaka?

### ISSUE THREAD

**Issue by GNiendorf** [alpaka-group/alpaka#1940]
In CUDA you can use the prefix \_\_shared__ to initialize a variable in shared memory. Is there an analog for this in Alpaka? Sorry if this is a duplicate issue, but I could not seem to find an answer elsewhere. Thank you!

**Comment by fwyzard** [comment]
I think you can implement the equivalent of
```c++
__shared__ T t;
```
with
```c++
T& t = alpaka::declareSharedVar<T, __COUNTER__>(acc);
```

`__COUNTER__` is a macro that expands to an increasing index for each invocation, and is used to generate a unique identifier for each shared memory variable.

See https://alpaka.readthedocs.io/en/latest/dev/backends.html?highlight=shared#_CPPv4I0_NSt6size_tE0EN6alpaka16declareSharedVarEDaRK17TBlockSharedMemSt .
