### ISSUE TITLE
Memcpy to Particular Element of Array?

### ISSUE THREAD

**Issue by GNiendorf** [alpaka-group/alpaka#1953]
Is it possible to Memcpy to a particular element of an array in Alpaka? In CUDA this would look like:

`cudaMemcpy(&(segmentsInGPU->nSegments)[pixelModuleIndex], &size, sizeof(int), cudaMemcpyHostToDevice);`

In Alpaka though I'm not sure how I would accomplish this.

**Comment by fwyzard** [comment]
hi @GNiendorf,
from the question I assume that `segmentsInGPU` is a structure like
```c++
struct Segments {
    // dynamic array of int in device memory
    int* nSegments;
    // more fields
};
```
and that `size` is an `int`.

With Alpaka, you may have a structure like
```c++
struct Segments {
    // device buffer of int
    alpaka::BufCudaRt<int, alpaka::DimInt<1u>, size_t> nSegments;
    // more fields
};
```

and we can assume that your inputs are something like
```c++
  // assume that the gpu buffer is something like
  segmentsInGPU->nSegments = alpaka::allocBuf<int, size_t>(device, (size_t) 100u);

  // and that is will be index with something like
  size_t pixelModuleIndex = 10;

  // assume that the source scalar on the host is something like
  int size = 42;
```

To copy a single value, you can create a pair of Views for the source and destination, then use the `alpaka::memcpy` function:
```c++
  // create a source view 
  auto src_view = alpaka::createView(host, &size, (size_t) 1u);

  // create a target view for the element pixelModuleIndex inside segmentsInGPU->nSegments
  auto dst_view = alpaka::createSubView(segmentsInGPU->nSegments, (size_t) 1u, pixelModuleIndex);

  // copy a single value from the host to the gpu buffer
  alpaka::memcpy(queue, dst_view, src_view);
```

**Comment by GNiendorf** [comment]
Awesome, thank you for your help!
