### ISSUE TITLE
autogenerate a single header file for the whole alpaka library

### ISSUE THREAD

**Issue by fwyzard** [alpaka-group/alpaka#1954]
Hi,

while playing with Godbolt's Compiler Explorer, I realised that it would be nice to have a version of Alpaka packaged as a single header, that could be included with
```c++
#include <https://raw.githubusercontent.com/alpaka-group/alpaka/develop/include/alpaka.hpp>
```

This does not work because the system cannot resolve remote includes (the other `#include` inside `alpaka.hpp`).

Maybe the CI could be extended with a post-merge hook that
  - merges all Alpaka includes locally, keeping all the preprocessor directives intact
  - generates a single, equivalent, header file
  - commits and push it to a separate repository (or a separate branch of the main repository)

?

**Comment by bernhardmgruber** [comment]
I have this in llama and it is fairly easy to do from the CI. I can make this happen.

**Comment by bernhardmgruber** [comment]
Well, it's not so easy if the amalgamation script runs out of memory :D

See downstream issue here: https://github.com/shrpnsld/amalgamate/issues/2

**Comment by bernhardmgruber** [comment]
New branch is here: https://github.com/alpaka-group/alpaka/tree/single-header

**Comment by fwyzard** [comment]
hi @bernhardmgruber, would it make sense to move it to `include/alpaka/alpaka.hpp`, to match the standard include file name ?

**Comment by bernhardmgruber** [comment]
I don't mind. I just picked the shortest possible path.

**Comment by bernhardmgruber** [comment]
> hi @bernhardmgruber, would it make sense to move it to `include/alpaka/alpaka.hpp`, to match the standard include file name ?

Renamed in PR #1956 and on the branch.

**Comment by bernhardmgruber** [comment]
> Well, it's not so easy if the amalgamation script runs out of memory :D

> See downstream issue here: https://github.com/shrpnsld/amalgamate/issues/2

Fixed upstream.
