### ISSUE TITLE
Validity check of workDiv for TaskKernelCpuSerial

### ISSUE THREAD

**Issue by jkelling** [alpaka-group/alpaka#1994]
The CPU serial task checks the validity of the work div only at the start of kernel execution, throwing an exception if the check fails:
https://github.com/alpaka-group/alpaka/blob/375f4f0e161839caa47efa3342f815be1181c5aa/include/alpaka/kernel/TaskKernelCpuSerial.hpp#L82
In conjunction with the non-blocking CPU queue, such an exception is stored away in a TaskPkg, with no apparent way for the calling code/user to check for it:
https://github.com/alpaka-group/alpaka/blob/375f4f0e161839caa47efa3342f815be1181c5aa/include/alpaka/core/ConcurrentExecPool.hpp#L75-L82
This leads to kernels with invalid workdiv to *silently* no be executed, presenting a major stumbling block for new users.
[`TaskKernelCpuOmp2Blocks`](https://github.com/alpaka-group/alpaka/blob/375f4f0e161839caa47efa3342f815be1181c5aa/include/alpaka/kernel/TaskKernelCpuOmp2Blocks.hpp#L827-L830) implements the same behavior.

For [`TaskKernelGpuUniformCudaHipRt`](https://github.com/alpaka-group/alpaka/blob/375f4f0e161839caa47efa3342f815be1181c5aa/include/alpaka/kernel/TaskKernelGpuUniformCudaHipRt.hpp#L212) the queue's Enqueue trait is specialized to perform the check at enqueue-time.

**Comment by bernhardmgruber** [comment]
I think `ConcurrentExecPool` should just be simplified, since it's now only needed as a thread pool for running kernels. The custom task types could be replaced by something simpler. Also, tasks should be all awaited at the thread pool destruction. That should resolve the issue as well.
