### ISSUE TITLE
No type named 'type'

### ISSUE THREAD

**Issue by GNiendorf** [alpaka-group/alpaka#2009]
I have code that runs fine with the CUDA backend, and now I am trying to get it to run on the CPU by compiling with g++ and the -DALPAKA_ACC_CPU_B_SEQ_T_SEQ_ENABLED flag. However, I get a bunch of errors from my kernels saying, "no type named 'type' in ..." that I'm not sure how to solve. Any suggestions would be greatly appreciated! Here are some example error messages I get:

`/cvmfs/cms.cern.ch/el8_amd64_gcc10/external/gcc/10.3.0-84898dea653199466402e67d73657f10/include/c++/10.3.0/type_traits:2957:11: error: no type named 'type' in 'struct std::invoke_result<SDL::hitLoopKernel, const alpaka::AccCpuSerial<std::integral_constant<long unsigned int, 3>, long unsigned int>&, const SDL::SubDet&, const SDL::ModuleType&, const short unsigned int&, const unsigned int&, unsigned int* const&, float* const&, const SDL::modules&, const SDL::hits&, const unsigned int&>'
 2957 |     using invoke_result_t = typename invoke_result<_Fn, _Args...>::type;`
 
 `/cvmfs/cms.cern.ch/el8_amd64_gcc10/external/gcc/10.3.0-84898dea653199466402e67d73657f10/include/c++/10.3.0/type_traits:2957:11: error: no type named 'type' in 'struct std::invoke_result<SDL::moduleRangesKernel, const alpaka::AccCpuSerial<std::integral_constant<long unsigned int, 3>, long unsigned int>&, const SDL::modules&, const SDL::hits&, const short unsigned int&>'`
 
Could the error be caused by how we're passing in the structs to each kernel? Should we be passing in the pointer rather than dereferencing it like how it's done in the code now? 

Edit: It seems like this is the issue actually. I just fixed it for one kernel and the errors for that kernel have gone away. Why is this an issue for the CPU backend but not for the CUDA backend?

 For reference, here's what the moduleRangesKernel looks like:
![Screenshot 2023-07-23 at 2 40 11 PM](https://github.com/alpaka-group/alpaka/assets/25272611/1b06b223-8884-4704-aa88-b462fd219ec5)

 And here's how I'm calling the kernel.
![Screenshot 2023-07-23 at 2 42 03 PM](https://github.com/alpaka-group/alpaka/assets/25272611/53e5f4e2-e8c3-4f73-9a5c-95026bd3dbd9)

**Comment by fwyzard** [comment]
Hi @GNiendorf, it's not possible to pass arguments to a kernel by reference, they must be passed by value.

Can you try changing the definition of `operator()` to take its arguments (except for the `acc`) by value ?

**Comment by GNiendorf** [comment]
Awesome, got it to run. Thank you @fwyzard!
