### ISSUE TITLE
Add Copysign to Alpaka

### ISSUE THREAD

**Issue by GNiendorf** [alpaka-group/alpaka#2044]
Hello, I was hoping you could add copysign to Alpaka. This is the last math function in our code that is not natively supported by Alpaka at the moment. Thank you for your help.

**Comment by fwyzard** [comment]
Let me look into that.

**Comment by fwyzard** [comment]
Fixed by #2050.

**Comment by GNiendorf** [comment]
Thank you @fwyzard!
