### ISSUE TITLE
CI is not running any tests with mdspan enabled

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/alpaka#2049]
The CI is not runnign any tests that enable the use of `alpaka::experimental::mdspan`. The corresponding examples are not compiling at the moment because previous changes forgot to update those examples. We should add corresponding CI runs that include mdspan.

**Comment by bernhardmgruber** [comment]
Just having a few CI runs that set `alpaka_USE_MDSPAN` to `FETCH` should be enough.

**Comment by SimeonEhrig** [comment]
Is there any reason to disable the mdspan tests for a test job and can we run all test with mdspan?

**Comment by fwyzard** [comment]
We currently do not enable or use mdspan, so I would prefer to run at least some of the tests without it.

I'd be happy with just a recent GCC/CUDA version, and maybe one HIP version.

**Comment by SimeonEhrig** [comment]
Sure, I add mdspan to the job generator. Therefore it will generate tests with and without mdspan for all compiler.

**Comment by bernhardmgruber** [comment]
> Sure, I add mdspan to the job generator. Therefore it will generate tests with and without mdspan for all compiler.

You are great, thx a lot!
