### ISSUE TITLE
CUDA/HIP device wait for an event is wrong working

### ISSUE THREAD

**Issue by psychocoderHPC** [alpaka-group/alpaka#2060]
alpaka is providing the functionality that all streams of a device can be dependent on an event. This is nothing CUDA is providing via an API call.
alpaka is implementing it by using the stream `zero`

https://github.com/alpaka-group/alpaka/blob/ac7b41daf2be8d34cb2212535b866b3e41e16ce7/include/alpaka/event/EventUniformCudaHipRt.hpp#L218-L232

alpaka is creating the streams so that they do not wait for the legacy blocking stream zero.

https://github.com/alpaka-group/alpaka/blob/ac7b41daf2be8d34cb2212535b866b3e41e16ce7/include/alpaka/queue/cuda_hip/QueueUniformCudaHipRt.hpp#L58

Therefore our implementation is wrong because there will be no synchronization.

A solution is to implement it the same way we do it for other backends. Da device must track a list with all stream/queues and in the implementation call `alpaka::wait(queue, event)` for all queues of the device.

**Comment by bernhardmgruber** [comment]
Do we actually need this feature? Or can we just ask users to just keep a list of queues around for themselves? What's the use case of this feature?

**Comment by fwyzard** [comment]
> alpaka is providing the functionality that all streams of a device can be dependent on an event. This is nothing CUDA is providing via an API call.

@psychocoderHPC, I do not understand what you mean :-(

Could you give an example of how this would be used ?

**Comment by j-stephan** [comment]
In short: alpaka provides the functionality to make an entire device (= all queues attached to it) wait for a single event. A possible use case would be that you have some kernels enqueued which are independent of each other but dependent on the result of a previous kernel (possibly running on another device).

**Comment by fwyzard** [comment]
Thanks for the explanation!
What is the syntax for that?

**Comment by j-stephan** [comment]
It currently is

```c++
alpaka::wait(device, event);
```

@psychocoderHPC and I thought about renaming it to `let_wait` to make it clear that it doesn't block the host thread.

**Comment by fwyzard** [comment]
Ah ok, so it behaves like
```
alpaka::wait(queue, event);
```
but for all the queues in `device` ?

**Comment by j-stephan** [comment]
Yes, exactly. We have the concept of `Waiter` in alpaka which can wait for one or more `Awaitable`s. At the moment `Waiter` concept is implemented for queues and devices and `Awaitable` only for events.

**Comment by j-stephan** [comment]
@psychocoderHPC Is this something we want for 1.0.0?

**Comment by psychocoderHPC** [comment]
Mhhh normally yes because this is an obvious bug :-(

**Comment by bernhardmgruber** [comment]
> Mhhh normally yes because this is an obvious bug :-(

Thank you for volunteering! :)

**Comment by psychocoderHPC** [comment]
I tried to avoid it but started to fix it before you wrote.

**Comment by psychocoderHPC** [comment]
fixed with #2108
