### ISSUE TITLE
`allocMappedBufIfSupported` silently accepts non-platform types as TPlatform

### ISSUE THREAD

**Issue by chaever** [alpaka-group/alpaka#2065]
[`alpaka::allocMappedBufIfSupported`](https://github.com/alpaka-group/alpaka/blob/develop/include/alpaka/mem/buf/Traits.hpp#L159-L188) currently does not directly check if TPlatform is an actual platform type (`alpaka::isPlatform<TPlatform>`).

This can lead to cases where an inexperienced user can pass the device type instead of the platform type as TPlatform to `alpaka::allocMappedBufIfSupported`. Since `alpaka::hasMappedBufSupport` is [false by default](https://github.com/alpaka-group/alpaka/blob/develop/include/alpaka/mem/buf/Traits.hpp#L43) for every type, the [second if-branch within allocMappedBufIfSupported](https://github.com/alpaka-group/alpaka/blob/develop/include/alpaka/mem/buf/Traits.hpp#L183-L185) is chosen, and non-Managed memory is returned even when managed memory would be available. All this happens silently, without giving the user a warning that TPlatform is not a Platform, which can be very confusing.

To prevent this, [this implementation](https://github.com/chaever/alpaka/blob/check_TPltf_when_allocating_device_memory/include/alpaka/mem/buf/Traits.hpp#L178) includes a `static_assert` to notify the user in this case.

**Comment by j-stephan** [comment]
Thanks for reporting this!

**Comment by fwyzard** [comment]
We could also change
```c++
        if constexpr(hasMappedBufSupport<TPlatform>)
        {
            return allocMappedBuf<TPlatform, TElem, TIdx>(host, platform, extent);
        }
```
to
```c++
        using Platform = alpaka::Platform<TPlatform>;
        if constexpr(hasMappedBufSupport<Platform>)
        {
            return allocMappedBuf<Platform, TElem, TIdx>(host, platform, extent);
        }
```
so that passing a `Device` or `Accelerator` instead of a `Platform` would still work.

**Comment by chaever** [comment]
> We could also change
> 
> ```c++
>         if constexpr(hasMappedBufSupport<TPlatform>)
>         {
>             return allocMappedBuf<TPlatform, TElem, TIdx>(host, platform, extent);
>         }
> ```
> 
> to
> 
> ```c++
>         using Platform = alpaka::Platform<TPlatform>;
>         if constexpr(hasMappedBufSupport<Platform>)
>         {
>             return allocMappedBuf<Platform, TElem, TIdx>(host, platform, extent);
>         }
> ```
> 
> so that passing a `Device` or `Accelerator` instead of a `Platform` would still work.

This has the added benefit that the `Platform<>`-Traits default implementation [is empty](https://github.com/alpaka-group/alpaka/blob/develop/include/alpaka/platform/Traits.hpp#L28-L30), meaning only the specializations have a [`::type`](https://github.com/alpaka-group/alpaka/blob/develop/include/alpaka/platform/Traits.hpp#L37). Passing invalid types, e.g. `int` would result in `Platform<int>` asking for [`trait::PlatformType<T>::type`](https://github.com/alpaka-group/alpaka/blob/develop/include/alpaka/platform/Traits.hpp#L51) which doesnt exist (because [`int` does not fulfill the platform-concept](https://github.com/alpaka-group/alpaka/blob/develop/include/alpaka/platform/Traits.hpp#L35), making `PlatformType<int>` empty) , and thus in a compile error (which means the static_assert proposed above is no longer strictly neccessary).
