### ISSUE TITLE
memFence and atomics

### ISSUE THREAD

**Issue by AuroraPerego** [alpaka-group/alpaka#2069]
Today during the meeting we have discussed about the way fences work and how they are implemented in alpaka.
[According to the c++ standard](https://en.cppreference.com/w/cpp/atomic/atomic_thread_fence), they should be used together with atomics to be meaningful and the SYCL standard behaves in the same way. For this reason both in the serial and in the SYCL back-end the fences have been surrounded with atomics.
However, if a user needs a fence in his code this means that he is already using atomics, therefore adding another one in alpaka should not be necessary.
Considering this, the proposal is to [drop the atomics](https://github.com/AuroraPerego/alpaka/commit/5b70b353de2ef5f2c9d6915313a59f13a970fbb8) in the fences and to document properly their usage in the documentation.

FYI @fwyzard

**Comment by j-stephan** [comment]
As stated yesterday: We agree with the proposal and are looking forward to reviewing your PR :-)

**Comment by j-stephan** [comment]
Fixed by #2071.
