### ISSUE TITLE
Update clang-format

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/alpaka#2077]
Alpaka currently uses clang-format-14. clang-format-17 is about to be released shortly, so I think we should upgrade to version 15, or even 16.

**Comment by j-stephan** [comment]
This will require voting on the new rules introduced in clang-format-16 and -17. I'll look into it.

**Comment by j-stephan** [comment]
I have created a PR for all changes up to clang-format-16. See [here](https://github.com/ComputationalRadiationPhysics/contributing/pull/66).

**Comment by bernhardmgruber** [comment]
So it turns out that due to the bad formatting introduces in PR #2080, nvcc (or the host compiler?) yield a LOT of warnings and the compilation errors are not visible anymore in the CI, because the log exceeds a limit:) See e.g.: https://gitlab.com/hzdr/crp/alpaka/-/jobs/4929025306.

We discussed in the VC yesterday that we may want to delay the clang-format upgrade until the last moment before the next release. But given the problem I see now in the CI, it may be worthwhile to upgrade sooner.

**Comment by j-stephan** [comment]
No, those have been present before. They come from us adding `-pedantic` in our test warnings which clashes with nvcc's internal source reformatting before the CUDA compilation pass.

**Comment by bernhardmgruber** [comment]
> No, those have been present before. They come from us adding `-pedantic` in our test warnings which clashes with nvcc's internal source reformatting before the CUDA compilation pass.

Oh really? I have only observed this now after #2080 was merged. In that case though, can we suppress that warning? As I said, I can no longer read the error messages, because the log explodes :)
