### ISSUE TITLE
Squash extent/offset/pitch traits

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/alpaka#2079]
Alpaka's extent traits take the requested dimension as template argument:
```c++
auto e = getExtent<1>(buffer);
```
This creates unnecessary friction as dealing with template paramters is less convenient in user code than ordinary function parameters:
```c++
auto e = getExtent(1, buffer);
```
Arguably, the latter should be similarly efficient than the first version, since the compiler still sees the constant and `getExtent` can be fully inlined.

Furthermore, since extents are not huge objects, just returning all extents as an array could just squash a whole set of APIs into one:
```c++
auto e = getExtents(buffer)[1];
auto es = getExtents(); // all extents
auto [depth, height, width] = getExtents(); // how beautiful!
```
The latter function already exists as `getExtentsVec`, but is not a trait. It just builds upon `getExtent<I>(...)`.

I propose to replace all extent functions by a single, customizable (trait) `getExtents(thing) -> Vec/Array`.

The same logic can be applied to offset and pitch traits as well.

**Comment by j-stephan** [comment]
I support this. And while we're at it maybe we can get rid of the `(depth, height, width)` order in favour of `(width, height, depth)`.

**Comment by fwyzard** [comment]
> maybe we can get rid of the `(depth, height, width)` order in favour of `(width, height, depth)`

Wait, what ?

**Comment by j-stephan** [comment]
For a 3D buffer the extents are arranged as `(z, y, x)`. So if you want to query the extent for the x dimension, you have to call `alpaka::getExtent<2>(buf);` instead of the (IMO) more intuitive `alpaka::getExtent<0>(buf)`. Since that is complicated and even us core developers tend to forget this detail we have the `get{Width,Height,Depth}(buf)` functions which do this calculation internally.

**Comment by fwyzard** [comment]
OK... how does it compare with the order of the indices used in a 3D accelerator ?

**Comment by fwyzard** [comment]
Also, sorry, I'm not familiar with multi-dimensional buffers in general... when you write `x`, `y` and `z` - which of the coordinates correspond to elements that are contiguous in memory, and which one to those that are furthers apart ?

**Comment by j-stephan** [comment]
> OK... how does it compare with the order of the indices used in a 3D accelerator ?

The same as for buffers. So for a 3D CUDA accelerator all of the following are `true`:

```cuda
auto idx = getIdx<Grid, Blocks>(acc);
blockIdx.x == idx[2];
blockIdx.y == idx[1];
blockIdx.z == idx[0];
```

> when you write `x`, `y` and `z` - which of the coordinates correspond to elements that are contiguous in memory, and which one to those that are furthers apart ?

`x` is the contiguous index. So a coordinate `(z, y, x)` is internally mapped to the linear index (omitting a row pitch for clarity):

```c++
auto linearIdx = z * dimY * dimX
                 + y * dimX
                 + x;
```

**Comment by fwyzard** [comment]
ok, so
```c++
auto linearIdx = idx[0] * extent[1] * extent[2]
               + idx[1] * extent[2]
               + idx[2];
```
?

And for a 2D buffer
```c++
auto linearIdx = idx[0] * extent[1]
               + idx[1];
```
?

So the order of the indices matches the one used by OpenCL and SYCL, and it's kind of the opposite of the one used by CUDA and HIP, right ?

I don't mind if you decide to switch the ordering - but please keep it consistent between buffers and accelerators !

**Comment by fwyzard** [comment]
(also, this is _definitely_ an API breaking change...)

**Comment by bernhardmgruber** [comment]
> I support this. And while we're at it maybe we can get rid of the `(depth, height, width)` order in favour of `(width, height, depth)`.

> (also, this is _definitely_ an API breaking change...)

Which is why I don't intend to change the order.

**Comment by j-stephan** [comment]
Well, I just like `idx[0]` always referring to `x` no matter the dimension. But I'll bow to the majority here :-)

**Comment by bernhardmgruber** [comment]
> Well, I just like `idx[0]` always referring to `x` no matter the dimension. But I'll bow to the majority here :-)

We can certainly have that discussion in a separate issue, although I would be too afraid of such a silent API change.
