### ISSUE TITLE
`static_assert(Dim<TExtent>::value >= 1)` fails in pixeltrack

### ISSUE THREAD

**Issue by AuroraPerego** [alpaka-group/alpaka#2132]
Since [this commit](https://github.com/alpaka-group/alpaka/commit/5af1f41849c4733bbf88fd84592e2b8b4b2fa178) pixeltrack-standalone fails to compile because of:
```bash
/afs/cern.ch/user/a/aperego/public/pixeltrack-standalone/external/alpaka/include/alpaka/extent/Traits.hpp(92): error: static assertion failed
          detected during:
            instantiation of "auto alpaka::getWidth(const TExtent &)->alpaka::Idx<TExtent> [with TExtent=alpaka_common::Scalar]"
/afs/cern.ch/user/a/aperego/public/pixeltrack-standalone/src/alpaka/AlpakaCore/CachedBufAlloc.h(66): here
            instantiation of "auto cms::alpakatools::traits::CachedBufAlloc<TElem, TDim, TIdx, alpaka::DevCudaRt, TQueue, void>::allocCachedBuf(const alpaka::DevCudaRt &, TQueue, const TExtent &)->alpaka::BufCudaRt<TElem, TDim, TIdx> [with TElem=ZVertexSoA, TDim=alpaka_common::Dim0D, TIdx=alpaka_common::Idx, TQueue=alpaka_cuda_async::Queue, TExtent=alpaka_common::Scalar]"
/afs/cern.ch/user/a/aperego/public/pixeltrack-standalone/src/alpaka/AlpakaCore/memory.h(193): here
            instantiation of "std::enable_if_t<<expression>, cms::alpakatools::device_buffer<alpaka::Dev<TQueue>, T>> cms::alpakatools::make_device_buffer<T,TQueue>(const TQueue &) [with T=ZVertexSoA, TQueue=alpaka_cuda_async::Queue]"
/afs/cern.ch/user/a/aperego/public/pixeltrack-standalone/src/alpaka/plugin-PixelVertexFinding/alpaka/gpuVertexFinder.cc(113): here
```
to reproduce:
```bash
git clone https://github.com/AuroraPerego/pixeltrack-standalone.git -b newBuf
cd pixeltrack-standalone && git checkout 9956d02bc3bbfc0acdd06849fbbbda997863538b
make environment
. env.sh
make alpaka
```
FYI @bernhardmgruber

**Comment by bernhardmgruber** [comment]
So, this issue is caused by a new requirement I added [here](https://github.com/alpaka-group/alpaka/commit/5af1f41849c4733bbf88fd84592e2b8b4b2fa178#diff-dc1cf1cc59a1fc0f421217556628b87002e843913c35a74e772b48c23f219a61R96). `getWidth(extent)` for a zero-dimensional extent no longer returns `1`, but statically asserts. The intention was that a "width" is only meaningful for one- or higher-dimensional views.

Let's discuss the possibilities:
* We are fine with the new reality and a zero-dimensional view/buffer/extent does not have a width (current behavior). @AuroraPerego needs to fix their code.
* Or, we define that a zero-dimensional view/buffer/extent always has a "width" of `1`.

Please also keep in mind the consistency with `getExtents`, which currently returns Vecs containing:
```
getExtents(zeroDim) -> []
getExtents(oneDim) -> [width]
getExtents(twoDim) -> [height, width]
getExtents(threeDim) -> [depth, height, width]
```
And this consistency: `Dim<decltype(getExtent(extent))>::value == Dim<decltype(extent)>::value`

If `getWidth(zeroDim)` would return `1`, should `getExtents(zeroDim)` return `[1]` then, or stay returning `[]`? Would we want to break  `Dim<decltype(getExtent(zeroDim))>::value == Dim<decltype(zeroDim)>::value` (1 != 0)?

**Comment by AuroraPerego** [comment]
As suggested by Bernhard, [this](https://github.com/AuroraPerego/pixeltrack-standalone/commit/3b1299cc853cebe8d15ec3602258251b604307a2) could be the fix for pixeltrack if we do not change anything in alpaka

**Comment by bernhardmgruber** [comment]
> As suggested by Bernhard, [this](https://github.com/AuroraPerego/pixeltrack-standalone/commit/3b1299cc853cebe8d15ec3602258251b604307a2) could be the fix for pixeltrack if we do not change anything in alpaka

I am glad it turned out to be a small fix on your side! I prefer to keep the static assert in alpaka, mostly for consistency with the remaining API. Unless you can find a better mental model :)

**Comment by j-stephan** [comment]
@AuroraPerego Do you want to keep this issue open on alpaka's side? Or will your fix land in pixeltrack eventually?

**Comment by AuroraPerego** [comment]
I opened it because Bernhard wanted to start a discussion on this topic, but if the choice is to not change alpaka I'm fine with it and we can close the issue

**Comment by j-stephan** [comment]
I see. I'll let @bernhardmgruber decide on how to proceed then.

**Comment by bernhardmgruber** [comment]
Well, noone has commented on whether `getWidth(zeroDim)` should be valid or not. Can I take this as: everybody is fine that the static assert in alpaka is justified? Because then this issue is resolved and no changes are required.

**Comment by j-stephan** [comment]
IMO the current behaviour makes sense. And since it is apparently easy to fix on CMS' side I vote for not changing alpaka.

**Comment by fwyzard** [comment]
I think `getWidth(zeroDim)` should return `[]`, but `getExtentProduct(zeroDim)` should return `1`.

**Comment by bernhardmgruber** [comment]
> I think `getWidth(zeroDim)` should return `[]`

`getWidth(anything)` currently returns `Idx<decltype(anything)>`, which is usually a scalar. What do you mean with `[]`? An empty `Vec`? That would be weird :S

> , but `getExtentProduct(zeroDim)` should return `1`.

I think this is already the case.

**Comment by fwyzard** [comment]
Well, I though it was returning the sizes, not the dimensionality.

If it returns the dimensionality (_i.e._ a scalar) there is no reason to have an assert - just make it return `0`.

**Comment by j-stephan** [comment]
@fwyzard, are you maybe confusing `getWidth` (which has always returned a scalar) with `getExtents` (returns a `Vec`)?

**Comment by fwyzard** [comment]
Yep, possible.

So:
  - `getWidth(zeroDimBuffer)` should return `0`
  - `getExtents(zeroDimBuffer)` should return `[]`
  - `getExtentProduct(zeroDimBuffer)` should return `1`

Does this make sense ?

**Comment by bernhardmgruber** [comment]
> * `getWidth(zeroDimBuffer)` should return `0`

Alright, so for the sake of consistency, what should those return then:

```c++
getHeight(zeroDimBuffer);
getHeight(oneDimBuffer);
```

**Comment by fwyzard** [comment]
I guess I keep being confused.

Can you explain what getWidth, getHeight, etc. are supposed to return ?

**Comment by j-stephan** [comment]
> > * `getWidth(zeroDimBuffer)` should return `0`
> 
> Alright, so for the sake of consistency, what should those return then:
> 
> ```c++
> getHeight(zeroDimBuffer);
> getHeight(oneDimBuffer);
> ```

Also 0 for both cases IMO.

@fwyzard Given a 3D buffer with the extent vector `[z, y, x]`:

* `getWidth` returns `x` as a scalar
* `getHeight` returns `y` as a scalar
* `getDepth` returns `z` as a scalar
* `getExtents` returns `[z, y, x]` as a vector

So now the question arises what `getDepth` should return if there is no `z` component (and similar for the other scalar getters). I'd vote for `0` here.

**Comment by fwyzard** [comment]
Ah, then I misunderstood, sorry.

So the question is whether a missing dimension should be considered as having size `1` or `0` or not be defined at all ?

**Comment by fwyzard** [comment]
I guess I prefer either `1` or undefined.

**Comment by bernhardmgruber** [comment]
Alright, the status quo is a static assertion, which I assume corresponds to your "undefined"? I assume this is fine then.

I can also see returning `1` as a good option, though. So if you or anyone else wants to go for that change, please go ahead.

Otherwise, I consider this issue resolved then.

**Comment by j-stephan** [comment]
IMO a `static_assert` isn't the ideal way to go here. It breaks user code and makes generic programming more difficult. What do you think of the following interface for `get{Width,Height,Depth}`? It wouldn't break current user code and offers more customization points.

```c++
ALPAKA_NO_HOST_ACC_WARNING
template<typename TExtent, bool assertDim = false>
ALPAKA_FN_HOST_ACC auto getWidth(TExtent const& extent = TExtent(),
                                 Idx<TExtent> voidValue = Idx<TExtent>(0)) -> Idx<TExtent>
{
    if constexpr(assertDim)
        static_assert(Dim<TExtent>::value >= 1);

    if constexpr(Dim<TExtent>::value < 1)
        return voidValue;

    return getExtents(extent)[Dim<TExtent>::value - 1u];
}
```

**Comment by AuroraPerego** [comment]
mmh the assert is triggered when `Dim<TExtent>::value`==0, so how is `getExtents(extent)[-1u]` defined?
Maybe when `assertDim` is `false` we could just `return 1;`

**Comment by j-stephan** [comment]
> so how is `getExtents(extent)[-1u]` defined?

`alpaka::Vec` internally `assert`s that only values >= 0 are accepted.

**Comment by AuroraPerego** [comment]
Ah ok, thanks for the clarification

**Comment by bernhardmgruber** [comment]
> IMO a `static_assert` isn't the ideal way to go here. It breaks user code and makes generic programming more difficult. What do you think of the following interface for `get{Width,Height,Depth}`? It wouldn't break current user code and offers more customization points.
> 
> ```c++
> ALPAKA_NO_HOST_ACC_WARNING
> template<typename TExtent, bool assertDim = false>
> ALPAKA_FN_HOST_ACC auto getWidth(TExtent const& extent = TExtent(),
>                                  Idx<TExtent> voidValue = Idx<TExtent>(0)) -> Idx<TExtent>
> {
>     if constexpr(assertDim)
>         static_assert(Dim<TExtent>::value >= 1);
> 
>     if constexpr(Dim<TExtent>::value < 1)
>         return voidValue;
> 
>     return getExtents(extent)[Dim<TExtent>::value - 1u];
> }
> ```
This is a really complex API. I'd rather have simplier behavior and less customizations.

**Comment by bernhardmgruber** [comment]
@AuroraPerego feel free to revert your fixes in pixeltrack, since `getWidth` should now work again as previously.
