### ISSUE TITLE
Add support for clang-17

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/alpaka#2169]
LLVM 17 was just released: https://discourse.llvm.org/t/llvm-17-0-1-released/73549

Let's add support for clang-17 to the CI.

**Comment by SimeonEhrig** [comment]
Wow, faster than the web server of llvm.org :joy:

**Comment by bernhardmgruber** [comment]
> Wow, faster than the web server of llvm.org 😂

I just received the notification from the mailing list :)
