### ISSUE TITLE
OpenMP backend fails to compile with clang-17

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/alpaka#2170]
When compiling the unit tests with clang-17, enabling the `ACC_CPU_B_SEQ_T_OMP2` backend, the following failure is reported:
```
/home/bgruber/dev/alpaka/include/alpaka/atomic/AtomicOmpBuiltIn.hpp:190:50: error: the statement for 'atomic compare capture' must be a compound statement of form '{v = x; cond-up-stmt}', ''{cond-up-stmt v = x;}', '{if(x == e) {x = d;} else {v = x;}}', '{r = x == e; if(r) {x = d;}}', or '{r = x == e; if(r) {x = d;} else {v = x;}}', where 'cond-update-stmt' can have one of the following forms: 'if(expr ordop x) {x = expr;}', 'if(x ordop expr) {x = expr;}', 'if(x == e) {x = d;}', or 'if(e == x) {x = d;}' where 'x', 'r', and 'v' are lvalue expressions with scalar type, 'expr', 'e', and 'd' are expressions with scalar type, and 'ordop' is one of '<' or '>'.
  190 |                     ref = (ref <= value) ? ref : value;
      |                                                  ^~~~~
```

**Comment by j-stephan** [comment]
@jkelling, does the OpenMP standard forbid the `?` operator? That would be an interesting design choice...

**Comment by j-stephan** [comment]
I don't see clang-17 making it into alpaka 1.0, though. I'm not sure we should fix this for the current release.

**Comment by bernhardmgruber** [comment]
> @jkelling, does the OpenMP standard forbid the `?` operator? That would be an interesting design choice...

No, in this case it is really an incomplete implementation in clang. The implementation fo atomicInc though is really wrong in alpaka:
```c++
#        pragma omp atomic capture compare
                {
                    old = ref;
                    ref = (ref >= value) ? 0 : (ref + 1);
                }
```
This is not any of the allowed forms from the OpenMP 5.1 specification: https://www.openmp.org/spec-html/5.1/openmpsu105.html#x138-1480002.19.7

Interestingly, there is also the following paper mentioning that CUDA's `atomicInc` is not generally implementable in OpenMP 5.1, only by detecting target architectures and using intrinsics: https://www.researchgate.net/publication/352209452_Experience_Report_Writing_A_Portable_GPU_Runtime_with_OpenMP_51
