### ISSUE TITLE
`AccDevProps` should include global memory available

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/alpaka#2194]
I was looking for the available global memory of a device and was disappointed that `AccDevProps` does not offer a corresponding data member. The shared memory size is available. Please consider including an additional member for global memory.

**Comment by psychocoderHPC** [comment]
Are you searching for this?

https://github.com/alpaka-group/alpaka/blob/8d042651cd25d3c7eec95ca95f2061b5940b4f6a/include/alpaka/dev/Traits.hpp#L88-L94

**Comment by bernhardmgruber** [comment]
I totally was, thank you! :D

Nevertheless, could still think about providing it as well as part of the AccDevProps, since for some backends, e.g. CUDA, the information is available anyway.

**Comment by psychocoderHPC** [comment]
So it should maybe be implemented with https://github.com/alpaka-group/alpaka/issues/2192
