### ISSUE TITLE
Support ROCm 6.0

### ISSUE THREAD

**Issue by fwyzard** [alpaka-group/alpaka#2206]
ROCm 6.0 was release a couple of days ago: https://rocm.docs.amd.com/en/docs-6.0.0/about/release-notes.html .

**Comment by fwyzard** [comment]
Can we add ROCm 5.6.1, 5.7.1 and 6.0.0 to the CI ?

Do the CI job run on bare metal or in a container ? 
If it's a container, what version of ROCm is installed on the host OS ?  What kernel driver does it use ?

According to https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/user-kernel-space-compat-matrix.html , ROCm is a lot less flexible than CUDA with respect to backward and forward compatibility.

**Comment by psychocoderHPC** [comment]
We build on own container build on top of the original ROCm container.
The reason is that we need pre-build some dependencies to reduce the CI time.

I opened an issue in the container repo that we need ROCm 6. 

https://codebase.helmholtz.cloud/crp/alpaka-group-container/-/issues/36

**Comment by psychocoderHPC** [comment]
> If it's a container, what version of ROCm is installed on the host OS ? What kernel driver does it use ?

That's hard to say because we do not maintain the host OS. We ask from time to time that the admins should update the driver.
I will do it next year, if I trigger this week an update it could end in a broken CI for the next weeks.

**Comment by SimeonEhrig** [comment]
The containers should be not a problem. We use it only for caching. If a container with a specific ROCm version is not available, the CI will use another container and install ROCm each time, if the test is started.

Actual you need only add the version numbers to the `version.py` and the CI will generate the test. In the case of ROCm, there is something special. You need to add the clang version of each SDK version here: https://github.com/alpaka-group/alpaka/blob/8d042651cd25d3c7eec95ca95f2061b5940b4f6a/script/job_generator/generate_job_yaml.py#L335

I will open a PR and add the tests. But if a test fails, I have not time to fix it at the moment.

**Comment by SimeonEhrig** [comment]
The PR is open: https://github.com/alpaka-group/alpaka/pull/2207
