### ISSUE TITLE
Compilation errors with single-source branch and clang

### ISSUE THREAD

**Issue by StewMH** [alpaka-group/alpaka#2276]
Compiling with clang and the single source file included gives me these errors:
```
In file included from <source>:4:
/app/raw.githubusercontent.com/alpaka-group/alpaka/single-header/include/alpaka/alpaka.hpp:26621:67: error: template template argument has different template parameters than its corresponding template template parameter
 26621 |             using EnabledAccTags = alpaka::meta::Filter<AccTags, alpaka::AccIsEnabled>;
       |                                                                          ^
/app/raw.githubusercontent.com/alpaka-group/alpaka/single-header/include/alpaka/alpaka.hpp:26610:6: note: too many template parameters in template template argument
 26610 |             template<typename TTag, typename = void>
       |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/app/raw.githubusercontent.com/alpaka-group/alpaka/single-header/include/alpaka/alpaka.hpp:26596:32: note: previous template template parameter is here
 26596 |                     template<typename TList, template<typename> class TPred>
       |                                              ^~~~~~~~~~~~~~~~~~
1 error generated.
Compiler returned: 1
```
https://godbolt.org/z/9ffdPPKzj

I could not find a clang version that it worked for.

**Comment by StewMH** [comment]
~~I think this is the offending commit:~~
https://github.com/alpaka-group/alpaka/commit/eae316fce543c28ed0f04e967c02a8f7887cdd3f
Just confusing myself now, ignore this. Haven't figured out where it fails.

**Comment by SimeonEhrig** [comment]
The reason is, that we use a C++17 feature, which is disable by default until Clang 18. Clang 19 will enable it by default. Please set the compiler flag `-frelaxed-template-template-args`.

For more details, see here:
https://github.com/alpaka-group/alpaka/blob/887aee9304669331b9fc756132ef81aa61f4c349/cmake/alpakaCommon.cmake#L197-L202

**Comment by psychocoderHPC** [comment]
We added `-frelaxed-template-template-args` to alpaka with https://github.com/alpaka-group/alpaka/pull/2267

The provided godbolt example works fine when adding `-frelaxed-template-template-args`, therefor I will close this issue.
