### ISSUE TITLE
alignment of CUDA/HIP shared memory ?

### ISSUE THREAD

**Issue by fwyzard** [alpaka-group/alpaka#2277]
`GetDynSharedMem<T, BlockSharedMemDynUniformCudaHipBuiltIn>::getMem(acc)` is defined as:

https://github.com/alpaka-group/alpaka/blob/9b15e664d103c581020aa5285171b67483eb5c59/include/alpaka/block/shared/dyn/BlockSharedMemDynUniformCudaHipBuiltIn.hpp#L38-L46

1. if the concern is that the memory may not be aligned enough for `T`, why not declare it as
```c++
extern __shared__ T shMem[];
```
?

2. if the concern is that the memory may not be aligned enough for any type, why not declare it as
```c++
extern __shared__ __attribute__((aligned(16))) char shMem[];
```
?

3. do you think it could be helpful to declare this alignment, with
```c++
__device__ static auto getMem(BlockSharedMemDynUniformCudaHipBuiltIn const&) __attribute__((assume_aligned(16)))
 -> T*
```
?

**Comment by psychocoderHPC** [comment]
The reason that `aligned(16)` or `alignas(16)` is not used is that this code is 9 years old and from pre C++11 times.

I am not sure ` __attribute__((assume_aligned(16)))` is helping because an attribute at all can be ignored by the compiler.
The keyword `assume_aligned` is C++20. I do not have enough experience with `assume_aligned` to have a strong opinion on it.

**Comment by fwyzard** [comment]
> I am not sure ` __attribute__((assume_aligned(16)))` is helping because an attribute at all can be ignored by the compiler.
> The keyword `assume_aligned` is C++20. I do not have enough experience with `assume_aligned` to have a strong opinion on it.

`__attribute__((assume_aligned(16)))` is supported by both [GCC](https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#index-assume_005faligned-function-attribute) and [clang](https://clang.llvm.org/docs/AttributeReference.html#assume-aligned).

It's supposed to be used on a function that returns a pointer, so this seems the right use case, and I expect the compiler can use it to enable further optimisations - for example, generating instructions for aligned memory access.

I don't have experience with it, either. If you are interested, I could try adding it to the CMS software to see if it has any impact.

**Comment by fwyzard** [comment]
> The reason that `aligned(16)` or `alignas(16)` is not used is that this code is 9 years old and from pre C++11 times.

OK.

What do you think could be a good approach with today's c++17 ?

**Comment by psychocoderHPC** [comment]
We should at least use `alignas(16)` because this is standard C++.
I am free for other changes too but as I said do not have experience with `__attribute__((assume_aligned(16)))`

**Comment by fwyzard** [comment]
I've tried to look into the guaranteed alignment of dynamic shared memory, and I couldn't find anything in the [CUDA](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#shared) and [ROCm documentation](https://rocm.docs.amd.com/projects/HIP/en/latest/reference/kernel_language.html#shared).

The CUDA documentation does not explicitly give any guarantees, other than the alignment of the type used to declared the `extern __shared__` pointer.

The ROCm documentation is even more terse.

Compiling some simple code and inspecting the generated PTX, I noticed that
```c++
extern __shared__ double buffer[];
```
results in
```ptx
.extern .shared .align 8 .b8 buffer[];
```
while using a type with smaller alignment like
```c++
extern __shared__ char buffer[];
```
results in
```ptx
.extern .shared .align 1 .b8 buffer[];
```

So the alignment is important, and is probably not guaranteed to be a multiple of 16, unless it is required by the type.

**Comment by fwyzard** [comment]
Can anybody think of any issues with using simply
```c++
template <typename T>
__device__ static auto getMem(BlockSharedMemDynUniformCudaHipBuiltIn const&) -> T* 
{ 
    extern __shared__ T shMem[]; 
    return shMem; 
} 
```
?

**Comment by fwyzard** [comment]
Implemented in https://github.com/alpaka-group/alpaka/pull/2286 .

**Comment by fwyzard** [comment]
OK, that doesn't work, because
  - alpaka uses the same name for all dynamic shared memory variables
  - CUDA requires dynamic shared memory variables to be declared as `extern`
  - C/C++ (reasonably so) does not allow the redefinition of `extern` variables with different types

The same issue happens in regular CUDA if one writes two kernels with dynamic shared memoery variables with the same name and different types:
```c++
__global__
void kernel() {
    extern __shared__ float buffer[];
    // ...
}

__global__
void other() {
    extern __shared__ int buffer[];
    // ...
}
```
results in:
> ```
> <source>(25): error: declaration is incompatible with previous "buffer" (declared at line 19)
>       extern __attribute__((shared)) int buffer[];
> ```

**Comment by fwyzard** [comment]
OK, so for now let's go with
```c++
    extern __shared__ std::byte shMem[] alignas(16);
    return reinterpret_cast<T*>(shMem);
```

**Comment by fwyzard** [comment]
Instead, about `__attribute__((assume_aligned(16)))`, it looks like it is only allowed on a function declaration:
```c++
template <typename T>
__device__ T* dynamic() __attribute__((assume_aligned(16)));
```
and not on a function definition:
```c++
template <typename T>
__device__ T* dynamic() __attribute__((assume_aligned(16)))
{
    // ...
}
```
that results in:
> ```
> <source>:4:11: error: attributes are not allowed on a function-definition
> ```


Which maybe makes sense, since if the compiler can see the body of the function, it can infer the alignment without the need for the attribute.

**Comment by fwyzard** [comment]
Implemented (again) in https://github.com/alpaka-group/alpaka/pull/2286 .
