### ISSUE TITLE
CI is failing for ROCm 5.7 and 6.0

### ISSUE THREAD

**Issue by psychocoderHPC** [alpaka-group/alpaka#2282]
Since 27.05.2024 our CI is failing for HIP/ROCm 5.7 and 6.0 

https://gitlab.com/hzdr/crp/alpaka/-/jobs/6986700373

```
48:   /builds/hzdr/crp/alpaka/include/alpaka/dev/DevUniformCudaHipRt.hpp(138)
48:   'TApi::memGetInfo(&freeInternal, &totalInternal)' returned error  :
48:   'hipErrorInvalidValue': 'invalid argument'!
```

The latest dev branch shows this error where the last PR merged to dev does not had any issues.
There was an gitlab update on the CI runner on 27.05.

I am investigating with the CI what could happen to our AMD CI runner.

**Comment by fwyzard** [comment]
Possibly a change in the AMD kernel drivers ?

**Comment by psychocoderHPC** [comment]
Yes most likly. I forced the admins to reinstall the AMD driver and now all is working again. The strange behaviour was that ROCm <5.7 was still working.

**Comment by fwyzard** [comment]
Just curious, do you know what version of the driver they are using ?

In theory you need 5.6 or later to support ROCm 6.0 .

If ROCm 5.7 and later broke, maybe they installed the driver from 5.4.

**Comment by psychocoderHPC** [comment]
It was ROCm 6.0+ driver before because we know that our tests with ROCm 6.0 worked before but I do not have any information about the exact version.

> If ROCm 5.7 and later broke, maybe they installed the driver from 5.4.

This could be, I do not have inside on how they updated the system, maybe say installed an old version of the driver with the update.

**Comment by AuroraPerego** [comment]
It's happening again :(

**Comment by psychocoderHPC** [comment]
End of last week the it reinstalled the ROCm driver , all should work now again. @AuroraPerego I restarted the failing jobs.
