### ISSUE TITLE
Add Boost Compute Backend via C++ OpenCL API

### ISSUE THREAD

**Issue by bussmann** [alpaka-group/alpaka#231]
Boost now includes Boost Compute which provides a thin OpenCL API that should be matchable to the Alpaka parallel hierarchy:

http://www.boost.org/doc/libs/1_61_0/libs/compute/doc/html/boost_compute/porting_guide.html#boost_compute.porting_guide.opencl_api

An Alpaka Boost Compute Backend would allow for using OpenCL within Alpaka.

**Comment by erikzenker** [comment]
The Boost Compute kernel are not C++11 but still C99 like it is used in OpenCL( [see here](http://www.boost.org/doc/libs/1_61_0/libs/compute/doc/html/boost_compute/faq.html#boost_compute.faq.is_it_possible_to_use_ordinary_c___functions_functors_or_c__11__lambdas_with_boost_compute_)). Boost Compute only provides a nice interface to OpenCL functions. Thus, from my point of view Boost Compute won`t be useable as Alpaka back-end.

**Comment by bussmann** [comment]
But it says that lambdas are transformed to C99. Would it require pure C99 in an Alpaka kernel or would it never work by default? I need a better understanding of the backend.  We need a paper on Alpaka backends.

**Comment by bussmann** [comment]
See e.g. here
http://boostorg.github.io/compute/boost_compute/advanced_topics.html#boost_compute.advanced_topics.lambda_expressions

**Comment by j-stephan** [comment]
Is a Boost.Compute backend something we still want? @alpaka-group/alpaka-developers

**Comment by bernhardmgruber** [comment]
I don't want it :D Mostly because I have the feeling that Boost.Compute is not strongly maintained. IMO it also offers no real advantage to the backends we alreay have.

OpenCL also seems like it is being phased out. NVIDIA was always lagging behind in OpenCL support and AMD seems to bet a lot on HIP. It's a shame though, I think OpenCL (including the C++ wrapper from Khronos) is a great API!

**Comment by BenjaminW3** [comment]
I also do not think that we should add this anymore. I will close the ticket. Feel free to re-open if you still want this.
