### ISSUE TITLE
Documentation already points to latest

### ISSUE THREAD

**Issue by chillenzer** [alpaka-group/alpaka#2345]
The doc's front page says "The online version of this document is versioned and shows by default the manual of the last stable version of alpaka. If you are looking for the latest development version, [click here](https://alpaka.readthedocs.io/en/latest/)." (referring the reader to `latest`) but then again, the default `https://alpaka.readthedocs.io` (as is, for example, linked as the website in the GH repo) returns already the content of `latest`. From what I tried, `stable` is only ever reached from explicitly typing that address or using the small version menu at the bottom.

We should either point the default to `stable` as is written or remove that paragraph.

**Comment by psychocoderHPC** [comment]
I changed the default in readTheDocs to `stable`

**Comment by chillenzer** [comment]
Seems to have worked!
