### ISSUE TITLE
Organize Repo for Install

### ISSUE THREAD

**Issue by ax3l** [alpaka-group/alpaka#366]
In order to easier install the library (with and without compiled examples or tests) it would be probably helpful if we re-organize some of the files in the repo close to how an installed install in a prefix would look like.

Assuming a user *could* decide to install into `/usr`, we should make sure that CMake files/modules are also [well-placed](https://cmake.org/cmake/help/v3.0/command/find_package.html) in either `lib/cmake` or `share/cmake` (Unix). See the link for more details. We can also have the files in the same structure inside the repo to reduce the complexity in the logic of install targets.

Likewise, files that are currently in [`_ALPAKA_FILES_OTHER`](https://github.com/ComputationalRadiationPhysics/alpaka/blob/655eb708ff0157b492d73d50727de151b60f6ee6/alpakaConfig.cmake#L483-L484) should either not be installed (`.gitignore`, CI yaml files, ...) or be moved to `share/doc/alpaka/` (README, COPYING, CHANGELOG, ...) ([example](https://packages.debian.org/stretch/amd64/grep/filelist)).

The logic in `alpakaConfig.cmake` should go in the root `CMakeLists.txt` and a very minimal `alpakaConfig.cmake` gets generated at install time. We [install this file](https://cmake.org/cmake/help/v3.0/command/find_package.html) to `lib/cmake/alpakaConfig.cmake` together with generated version files on unix and to `cmake/alpakaConfig.cmake` on windows.

In-project ("third-party source") usage of alpaka can use the CMake functionality `add_subdirectory` to talk to the root `CMakeLists.txt` which defines the same targets.

**Comment by BenjaminW3** [comment]
I am not the right person to make those changes because I am not an expert regarding (different) unix install types and their requirements. Please create Pull Requests for the movement as well as for the CMake install rules after discussions about different portions has reached a consensus.

**Comment by BenjaminW3** [comment]
The gitignore and CI files should not be installed. The ReadMe and the license (COPYING) should be installed but should not be moved within the repository because the current location is the standard.

**Comment by ax3l** [comment]
Agreed to all of the above, but the README / COPYING need to be moved to a share folder, one can't place them in the install prefix (messy, un-associated & conflicts).

This does not mean they can't stay in the root of the repo, just not in the same structure of the installed package (but that's not too complicated to change in the logic).

**Comment by j-stephan** [comment]
@ax3l Do you feel that this is still an issue? We have had installation support in our build system for quite a while now.

**Comment by ax3l** [comment]
I think we can close this, thank you @j-stephan :sparkles:
