### ISSUE TITLE
add allocators

### ISSUE THREAD

**Issue by BenjaminW3** [alpaka-group/alpaka#37]
Add support for allocation inside the kernel and multiple allocators for kernel external allocation.

DevCuda:
- [x] AllocatorCuda (cudaMalloc, malloc when inside kernel)
- [ ] ScatterAlloc

DevCpu:
- [ ] AllocatorMalloc
- [x] AllocatorNew
- [x] AllocatorAligned (Boost.Align)
- [ ] AllocatorPageAligned

**Comment by BenjaminW3** [comment]
We could use [mallocMC](https://github.com/ComputationalRadiationPhysics/mallocMC) for this.

**Comment by erikzenker** [comment]
I stumpled upon the same Problem. Is there some allocator already available ?

**Comment by erikzenker** [comment]
I just still wonder on how to use the trait `alpaka::mem::alloc`. I tried the following on a OMP thread accelerator:

    alpaka::mem::alloc::alloc<char, T_Acc>(acc, nThreads);

and receive the error:

    /home/erik/projects/alpaka-examples/alpaka/include/alpaka/mem/alloc/Traits.hpp:72:29: error: implicit instantiation of undefined template
      'alpaka::mem::alloc::traits::Alloc<char, alpaka::acc::AccCpuThreads<std::integral_constant<unsigned long, 3>, unsigned long>, void>'
                    traits::Alloc<

When I understand your approach correctly, then the accelerator has to derive from an alloc trait implementation e.g. `AllocCpuNew`, right ?

So could I solve the problem by adding the allocator the the accelerator like this:

        class AccCpuOmp2Threads final :
            public workdiv::WorkDivMembers<TDim, TSize>,
            public idx::gb::IdxGbRef<TDim, TSize>,
            public idx::bt::IdxBtOmp<TDim, TSize>,
            public atomic::AtomicOmpCritSec,
            public math::MathStl,
            public block::shared::BlockSharedAllocMasterSync,
            public block::sync::BlockSyncOmpBarrier,
            public rand::RandStl,
            public public mem::alloc::AllocCpuNew <--- New Line !!!

        { ...

        };

**Comment by BenjaminW3** [comment]
Currently the allocators are only used from the host side within the Buffers.
Dynamic allocation within the kernel is currently not accelerator dependent. You are free to call `new`/`delete` on all platforms or use a MallocMC version that can be used on all platforms.

However, as you have correctly written, it would be good to use an allocator defined by the acceleraotr because it is not clear if new/delete will be possible on all platforms.
The way of inheritance is correct.
However, currently there is missing a AllocGpuCudaNew allocator that should be implemented similar to the AllocCpuNew as well as a important part of ther inheritance specialization forwarding mechanism.
I will have a look at this.

**Comment by j-stephan** [comment]
In today's meeting we discussed this issue. We all feel that this has been solved by [mallocMC](https://github.com/alpaka-group/mallocMC). Feel free to reopen this issue if you disagree.
