### ISSUE TITLE
do not create new std::thread for each registered CUDA stream callback

### ISSUE THREAD

**Issue by BenjaminW3** [alpaka-group/alpaka#391]
Currently, for each registered CUDA stream callback a new std::thread is created. This can be very time/resource demanding when many callbacks are registered.
The most flexible solution would be a thread pool with a queue of ready callbacks. If there is only one thread, the latency would be highest but the resource usage would be least. If there are multiple threads, the latency/resource tradeoff could be adapted per use case.

**Comment by psychocoderHPC** [comment]
Note: It is also possible to use a self growing thread pool which always create a new thread if there is no free thread available but never shrinks (remove threads). Than we will reach a maximum number of created threads depending of the concurrency within the program.

**Comment by j-stephan** [comment]
@fwyzard @felicepantaleo @waredjeb @tonydp03 I suppose this is what you encountered in the alpaka port of pixeltrack-standalone. We'll discuss this in our next internal meeting.

**Comment by j-stephan** [comment]
I think we can solve this through a new policy / trait. By default use the current behaviour, but allow users to override it with an alpaka-provided thread pool policy (or their own).

**Comment by j-stephan** [comment]
As @bernhardmgruber kindly pointed out, `cudaStreamAddCallback` is deprecated and will be removed in a future CUDA release. We should take a look at this sooner rather than later.

**Comment by fwyzard** [comment]
The [latest documentation](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__STREAM.html#group__CUDART__STREAM_1g74aa9f4b1c2f12d994bf13876a5a2498) says that

> This function is slated for _eventual deprecation and removal_. If you do not require the callback to execute in case of a device error, consider using `cudaLaunchHostFunc`. Additionally, this function is not supported with `cudaStreamBeginCapture` and `cudaStreamEndCapture`, unlike `cudaLaunchHostFunc`.
