### ISSUE TITLE
Replace alpaka metaprogramming parts with boost-1.66 mp11

### ISSUE THREAD

**Issue by BenjaminW3** [alpaka-group/alpaka#459]
The boost-1.66 library mp11 should be able to replace the alpaka metaprogramming utilities completely (because the alpaka ones have been implemented based on the same blog posts leading to mp11).
This would increase the required boost version to at least boost-1.66.

**Comment by psychocoderHPC** [comment]
Note: We are currently testing `mp11` together with `nvcc` from CUDA 9.1. 
As soon as `#include <boost/mp11.hpp>` is used in a CUDA program it will not compile.

@theZiz

**Comment by BenjaminW3** [comment]
This is really bad news.
Are you trying to break it down to the header/construct that causes the compiler error? If it is something we do not need, we may be lucky and use only the working sub-headers.

**Comment by psychocoderHPC** [comment]
Currently it looks like mp11 works with cuda 8 but not with cuda 9. Alex is creating a issue in the mp11 repro and for CUDA.

**Comment by psychocoderHPC** [comment]
It looks like CUDA 8 is working but not CUDA 9. Alex creates an issue for CUDA and for mp11 directly.

**Comment by theZiz** [comment]
This is what I figured out and wrote to Nvidia:

I am trying to port my application to use the recently added boost::mp11 C++11 metaprogramming library. However just including the template library using nvcc 9.1 without even using it at all fails to compile with the error:

boost/mp11/utility.hpp:141:184: error: expansion pattern ‘boost::mp11::detail::mp_no_type’ contains no argument packs.

Line 141 in boost/mp11/utility.hpp looks like this:

135: // mp_quote
136: template<template<class...> class F> struct mp_quote
137: {
138:     // the indirection through mp_defer works around the language inability
139:     // to expand T... into a fixed parameter list of an alias template
140:
141:     template<class... T> using fn = typename mp_defer<F, T...>::type;
142: };

The test application looks like this:

#include <boost/mp11.hpp>
int main() {}

It is compiled wiht "-std=c++11"; I also tried c++14, but it doesn't make any difference.

"nvcc -v --keep" shows, that the error happens while compiling the host code:

gcc -std=c++11 -D__CUDA_ARCH__=300 -c -x c++  -DCUDA_DOUBLE_MATH_FUNCTIONS -I"/home/alexander/develop/work/boost_1_66_0/install/include" -m64 -o "test.o" "test.cudafe1.cpp"

When I try to explicitly call this command by hand the same error happens, but "mp_quote" now looks like this in test.cudafe1.cpp:

# 136
template< template< class ...>  class F> struct mp_quote {
# 141
template< class ...T> using fn = typename detail::mp_if_c_impl< static_cast< bool>(detail::mp_valid_impl< F, T...> ::type::value), detail::mp_defer_impl< F, T...> , detail::mp_no_type...> ::type::type;
# 142
};

which explains the error as "detail::mp_no_type..." does not make much sense.

With Cuda 8 the code compiles without failes and "mp_quote" looks like this:

# 136
template< template< class ...>  class F> struct mp_quote {
# 141
template< class ...T> using fn = typename detail::mp_if_c_impl< static_cast< bool>(detail::mp_valid_impl< F, T...> ::type::value), detail::mp_defer_impl< F, T...> , detail::mp_no_type> ::type::type;
# 142
};

So the "..." for "detail::mp_no_type" is missing (as it should be). The rest of "mp_quote" looks the same.

I am using "Cuda compilation tools, release 9.1, V9.1.85" shipped with Debian testing for Cuda 9 tests and "Cuda compilation tools, release 8.0, V8.0.44" of our in house GPU cluster's module system.

**Comment by ax3l** [comment]
Can you please add your nvidia bug report number for documentation?

**Comment by ax3l** [comment]
Please also check how compiles with `clang -x cuda` and CUDA 8/9.0/9.1 behave.

**Comment by ax3l** [comment]
cc @sbastrakov

**Comment by theZiz** [comment]
I directly wrote a mail as I got Ajax errors while reporting the bug :roll_eyes: 
However they did not react yet so I opened a meta ticket to have the bug submission bug fixed before. :grin: 

I did check `clang -x cuda`: The same error happens – but even with cuda 8. :open_mouth:

**Comment by ax3l** [comment]
> I directly wrote a mail as I got Ajax errors while reporting the bug
> [...] However they did not react

I understand your frustration. Nevertheless, you might want to re-submit it via the official channel they have, maybe from a different computer. To my experience, that's to most reliable way to get feedback/improvement while other communications can get lost.

**Comment by ax3l** [comment]
> I did check clang -x cuda: The same error happens – but even with cuda 8.

That's weird, they don't use the same splitter: https://llvm.org/docs/CompileCudaWithLLVM.html#compilation-models

**Comment by theZiz** [comment]
![Shrug](https://m.popkey.co/dd9973/G01Ye_s-200x150.gif)

Le'me just retest, maybe I did something wrong.

**Comment by ax3l** [comment]
@theZiz please also report (& link) the issue in mp11 in Boot's `trac` issue tracker.

**Comment by theZiz** [comment]
@ax3l Will do so (mp11 trac)

>I understand your frustration. Nevertheless, you might want to re-submit it via the official channel they have, maybe from a different computer. To my experience, that's to most reliable way to get feedback/improvement while other communications can get lost (and did a lot in the past).

Well, I just tried with different browsers and slightly different details, but it failed again. I will maybe try at home, maybe our network is blacklisted? But a TU Dresden VPN connection does not work, too... :confused:

**Comment by ax3l** [comment]
Let's see how you meta-issue on the tracker works out for this one ;-) Just wanted to warn you that this is the most reliable channel to get things changed :)

**Comment by theZiz** [comment]
If I don't get a respone until next week, I will ask you or @psychocoderHPC  to submit the bug for me if it is working for you. :roll_eyes:

**Comment by ax3l** [comment]
There's also a `>>>` in rene's last report...

**Comment by theZiz** [comment]
The problem is, as mentioned in my bug report, that the nvidia preprocessor generates invalid code, so it's not the tokenizer of the compiler itself. I guess it's some hacky half perl script half lex and yacc failing here. :laughing: However I will try to add spaces, would be great, if this would solve the problem...

**Comment by ax3l** [comment]
We tested if offline: if you refactor the `>>>` to `> > >` clang works. Occurs on multiple occasions and only with `-x cuda`, needs to be reported upstream.

**Comment by ax3l** [comment]
I could imagine `nvcc` is suffering similar issues, simply because it's in the end the same LLVM codebase...

**Comment by theZiz** [comment]
Nope, I tested replacing `>>>` with cuda 9 and it still fails with the same error.

**Comment by ax3l** [comment]
Clang issue [reported upstream](https://bugs.llvm.org/show_bug.cgi?id=37013) and unrelated, at least for CUDA 8. Unclear if clang 7 + CUDA 9 would work.

**Comment by theZiz** [comment]
Okay, I guess I found a work around for boost::mp11.

The problem occurs on code like this:
```
template<template<class...> class F, class... T>
using mp_defer = mp_if<mp_valid<F, T...>, detail::mp_defer_impl<F, T...>, detail::mp_no_type>;
```
Everytime `mp_if` is used, the `nvcc` preprocessor tries to be "smart" and starts recursively replacing stuff so that in the end `detail::mp_no_type...`is given to the compiler.

I figured out I can prevent `nvcc` from doing this with invoking another struct inbetween like this:
```
template<template<class...> class F, class... T>
struct cuda_workaround
{
    using type = mp_if<mp_valid<F, T...>, detail::mp_defer_impl<F, T...>, detail::mp_no_type>;
};

template<template<class...> class F, class... T>
using mp_defer = typename cuda_workaround< F, T... >::type;
```

This occurs on 5 places in the boost mp11 code. I added an intermediate struct for every one and now my code compiles with `gcc-5` and `nvcc` 9.

But tbh, I still need to check whether the code is also correct. :rofl: But it looks promising! :+1:

**Comment by ax3l** [comment]
for the `>>>` issue with clang: I also opened a PR to `mp11` in case they accept it as a valid work-around: https://github.com/boostorg/mp11/pull/20

**Comment by theZiz** [comment]
I created an issue in the boost `trac` bug tracker but mp11 is not even listed as part of boost there :open_mouth: , so I guess I will just create a PR for my work around, too. :wink:

**Comment by ax3l** [comment]
Cool, just open a PR on github as well, link the trac in it and link the PR in trac :)

**Comment by theZiz** [comment]
It's the plan. :)

**Comment by ax3l** [comment]
The `>>>` issue with tokenizing CUDA vs. template code in clang is now fixed (potentially in clang 9+?):
https://bugs.llvm.org/show_bug.cgi?id=37013
https://reviews.llvm.org/D61396

**Comment by BenjaminW3** [comment]
I will close this ticket.
More and more meta programming constructs get integrated into the c++ standard and our goal is to get rid of dependencies (especially boost) instead of adding new dependencies.
