### ISSUE TITLE
Destructors should not throw

### ISSUE THREAD

**Issue by theZiz** [alpaka-group/alpaka#468]
Colleagues from the DLR using Alpaka run into a problem while using Alpaka together with a singleton pattern, in which a single global class handles the program environment.

Independently whether one should use this pattern or not, CUDA has problems with global variables as the may destruct after the cuda driver is already shut down: https://stackoverflow.com/questions/40979060/cudaerrorcudartunloading-error-29-due-to-driver-shutting-down

So in the end `ALPAKA_CUDA_RT_CHECK` fails with an unhandled exception: https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/include/alpaka/stream/StreamCudaRtSync.hpp#L103

As it is not possible to catch these exceptions destructors should normally not throw, but the class should have explicit finishinig / closing methods which can be checked for errors (if wanted), see https://stackoverflow.com/questions/130117/throwing-exceptions-out-of-a-destructor .

So I suggest to make every destructor of Alpaka non-throwing, e.g. by catching all exceptions inside the destructor so that error messages from `ALPAKA_CUDA_RT_CHECK` still appear.

**Comment by BenjaminW3** [comment]
The easiest solution should be to add `try`-`catch` blocks for all CUDA object wrapper destructors. I think this should be ok.

**Comment by psychocoderHPC** [comment]
In PIConGPU and Cupla we have a Singleton which load something like a parallel environment. This is the first singleton which is initialized and therefore also the last which will be destroyed. This class initialize and destroy the accelerator context.

**Comment by ax3l** [comment]
Note: we recently just introduced non-throwing, stderr-only-writing equivalents for those macros in PIConGPU. As a quick-fix that might be good as well. Nevertheless, clean functors and environment/device control that does not depend on destructor-order is the thing we should impl on the long run.

**Comment by sbastrakov** [comment]
> As a quick-fix that might be good as well

I agree with that. However, I think even the "new" approach in PIConGPU is not that good. Now the throwing versions of the check macros do both reporting (e.g., prints to stderr) and exception generation. And these two have actually nothing to do with one another and so are better be decoupled. C++ exceptions generally offer that: in case errors are reported as exceptions (so e.g., everywhere on the host side except in destructors), and the latter proparaged properly throughout the code, the reporting could be done somewhere way outside the place an exception is generated. Then a place which does the actual reporting could have more flexibility of how it's implemented and could have access to more context.

**Comment by ax3l** [comment]
Yes, fully agree. Nevertheless, we cant throw in noexcept contexts such as constructors, where we still have to log.

Of course, the throwing contexts should not also clutter stderr, but additional (well directed) logging is still fine.

**Comment by j-stephan** [comment]
Adding this to our to-do list since outside users have started to encounter this.

**Comment by ericcano** [comment]
I encountered this issue in a test validating a range checking feature. In CUDA kernels, when out of range, the kernel fails (crash on purpose in the absence of exceptions support). Once this has happened, we do get a exception when calling `aplaka::wait()` on the queue (this is totally fine), but in addition, both buffer and queue destructors fail with the following exceptions (and should not). I hacked the deleter/destructor to print out the `what()` from the exceptions instead of throwing:
```
In alpaka::traits::BufAlloc::deleter: ..../alpaka/include/alpaka/mem/buf/BufUniformCudaHipRt.hpp(256) 'cudaFree(reinterpret_cast<void*>(ptr))' returned error  : 'cudaErrorLaunchFailure': 'unspecified launch failure'!
In alpaka::uniform_cuda_hip::detail::QueueUniformCudaHipRtImpl::~QueueUniformCudaHipRtImpl: .../alpaka/include/alpaka/queue/cuda_hip/QueueUniformCudaHipRtBase.hpp(70) 'cudaStreamDestroy(m_UniformCudaHipQueue)' returned error  : 'cudaErrorLaunchFailure': 'unspecified launch failure'!
```

**Comment by j-stephan** [comment]
I looked into this today.

### Easy fix

Affected classes:

* `EventHostManualTriggerCudaImpl`
* `EventHostManualTriggerHipImpl`
* `EventUniformCudaHipImpl`
* `QueueUniformCudaHipRtImpl`

All of these make use of `ALPAKA_UNIFORM_CUDA_HIP_RT_CHECK` in the destructor. The macro generates an exception if the CUDA/HIP API call fails. I propose to introduce a `ALPAKA_UNIFORM_CUDA_HIP_RT_CHECK_NOEXCEPT` macro which just prints an error instead.

### Hard fix

Affects `BufCpu`.

If CUDA/HIP are enabled the destructor will call the top-level `alpaka::unpin` function which in turn makes use of `ALPAKA_UNIFORM_CUDA_HIP_RT_CHECK` internally. I'm not sure what the best way to proceed is.

### Won't fix

Affected classes:

* `ConcurrentExecPool`
* `ScopeLogStdOut`
* `QueueGenericSyclImpl`

These can theoretically throw if

* `std::cout` / `std::cerr` throw an exception
* `std::thread` (or other user defined threads) fail upon `join()`
* `std::queue` throws an exception on `pop()` and/or `front()` despite not being empty.

I'm quite certain we cannot recover from these in a meaningful way so we might as well just terminate.
