### ISSUE TITLE
Test Intel ICC compiler in CI

### ISSUE THREAD

**Issue by BenjaminW3** [alpaka-group/alpaka#493]
Intel allows [OpenSource-Contributors](https://software.intel.com/en-us/articles/open-source-contributor-faq) to [register for licenses](https://registrationcenter.intel.com/en/forms/?programid=OPNSRC&productid=2908) for it`s compiler which are valid for 1 year (you have to reapply each year to get a new license).
This license key has to be stored in a [secure environment variable in Travis](https://docs.travis-ci.com/user/encryption-keys/).
There is also a [project](https://github.com/nemequ/icc-travis) that installs icc but there may be others as well.
[This project](https://github.com/LLNL/RAJA/pull/259/files) already got it to work.

**Comment by ax3l** [comment]
Note: The problem with secure env variables in travis is, that we will only be able to run those on already merged PRs, but not inside PRs itself.

**Comment by chuckatkins** [comment]
I know this is an old thread but I'm currently trying to explicitly resolve this license issue with Intel.  The problem with the Open Source license they have is that it also falls under the terms of their Non-Commercial license, which essentially means that your use is only covered if it's on your own free time.  If you're doing the work in any capacity as a paid developer then the non-commercial license no longer applies, regardless of whether or not the resulting product is open source.

Even with a paid license though I'm not sure how this can work so I'm trying to get explicit clarification from Intel on how to do it.

https://software.intel.com/en-us/forums/intel-c-compiler/topic/831427

**Comment by ax3l** [comment]
Thank you for the information and following up on that, Chuck!

I think I remember that @jeffhammond mentioned in the past that one can use `icc` (NC) on Travis, https://github.com/nemequ/icc-travis . That repo also reads `NO LONGER WORKS due to changes in Intel license management`. Do you have any recommendations?

**Comment by chuckatkins** [comment]
> I think I remember that @jeffhammond mentioned in the past that one can use `icc` (NC) on Travis

There's "can" as in technically possible and "can" as in license-legal.  The first is easy as you can use the open source contributor license to make it work.  The second is much trickier though, and that's what I'm trying to get a specific answer on from Intel right now.  I think I have a "loophole" that I can use but I need to get confirmation from them first that it's okay.

**Comment by jeffhammond** [comment]
Send me an email (it’s easy to find) and we can work on this. There are multiple ways to solve it.

**Comment by ax3l** [comment]
ICC (`icpc`/`icc`) and DPCC (`dpcpp`/`fpcpp`) are now available as apt packages and docker images :tada: 

See here:
- https://github.com/rscohn2/oneapi-ci
- https://gitlab.com/rscohn2/oneapi-ci
- https://software.intel.com/en-us/articles/oneapi-repo-instructions
- https://github.com/openPMD/openPMD-api/commit/93646a3a302106590000ad60add1446720ff79be
- https://github.com/ECP-WarpX/WarpX/blob/27376e25415950018d4be93dfccb44d122e68f36/.github/workflows/ubuntu.yml

If you are really adventurous, you can even try to use the SYCL/DPC++ frontend with the LLVM PTX backend ("SYCL CUDA backend").

**Comment by j-stephan** [comment]
We have had a ICPC CI job for a while now.
