### ISSUE TITLE
non-uniform thread block size

### ISSUE THREAD

**Issue by BenjaminW3** [alpaka-group/alpaka#58]
Support for non-uniform thread block sizes would broaden the future adaptability to possible non-heterogeneous devices.

**Comment by bussmann** [comment]
I fully agree!

**Comment by j-stephan** [comment]
Six years later there is still no device or platform on the horizon which supports non-uniform block sizes. Is this still something we are interested in?

**Comment by j-stephan** [comment]
Closing for now. If there ever is a device with these capabilities we can reopen the issue.
