### ISSUE TITLE
BOOST_LANG_CUDA relies on cmake's __CUDACC__ workaround

### ISSUE THREAD

**Issue by tdd11235813** [alpaka-group/alpaka#611]
Currently, [we have](https://github.com/ComputationalRadiationPhysics/alpaka/pull/606):
```C
#if defined(__CUDA__) || defined(__CUDACC__)
      #include <cuda.h>
      #define BOOST_LANG_CUDA BOOST_PREDEF_MAKE_10_VVRRP(CUDA_VERSION)
  #else
      #define BOOST_LANG_CUDA BOOST_VERSION_NUMBER_NOT_AVAILABLE
  #endif
```
As example we take a common check:
```C
#ifdef ALPAKA_ACC_GPU_CUDA_ENABLED
#include <alpaka/core/Common.hpp> 
#if !BOOST_LANG_CUDA
    #error If ALPAKA_ACC_GPU_CUDA_ENABLED is set, the compiler has to support CUDA!
#endif
```
One consequence is, that this would fail, if cmake would not have a workaround for `__CUDACC__`.
When I use `make VERBOSE=1 rand` and take the commands without that workaround, I get an error (I actually had that issue with HIP(nvcc), where there is no workaround by cmake, and `__HIPCC__` which is not supposed to be defined by compiler):
> /alpaka/include/alpaka/pltf/PltfCudaRt.hpp:29:6: error: #error If ALPAKA_ACC_GPU_CUDA_ENABLED is set, the compiler has to support CUDA!
     #error If ALPAKA_ACC_GPU_CUDA_ENABLED is set, the compiler has to support CUDA!

cmake adds a definition of `__CUDACC__` and `NVCC` to nvcc (=> `nvcc -M -D__CUDACC__ ... -DNVCC ...`), so the host compiler called by nvcc also sees `__CUDACC__`. 
CMake source: See [cmake's run_nvcc.cmake here](https://github.com/Kitware/CMake/blob/master/Modules/FindCUDA/run_nvcc.cmake#L192) and [here](https://github.com/Kitware/CMake/blob/master/Modules/FindCUDA/run_nvcc.cmake#L206):

```cmake
# nvcc doesn't define __CUDACC__ for some reason when generating dependency files.  This
# can cause incorrect dependencies when #including files based on this macro which is
# defined in the generating passes of nvcc invocation.  We will go ahead and manually
# define this for now until a future version fixes this bug.
set(CUDACC_DEFINE -D__CUDACC__)
```

We probably could place an own define (even `BOOST_LANG_CUDA` or `BOOST_LANG_HIP`?) into the `NVCC_FLAGS` and `HIPCC_FLAGS`, to detect that the host compiler has been called by nvcc or hipcc. Or maybe there is a more portable solution, and I don't see it at the moment.

**Comment by ax3l** [comment]
Fun fact, on generation of dependencies (`nvcc -M`), NVCC also does not set `__NVCC__`. But here, CMake sets (same link as yours) `-DNVCC` instead of `-D__NVCC__` -.-

**Comment by sbastrakov** [comment]
I believe I have the same problem `If ALPAKA_ACC_GPU_CUDA_ENABLED is set, the compiler has to support CUDA!` when compiling for CUDA and MSVS with `-DALPAKA_ACC_GPU_CUDA_ONLY_MODE=ON`. And when I try to compile for both CUDA and OpenMP there seem to be even more issue, but that would make sense to investigate after CUDA-only works.
