### ISSUE TITLE
ViewPlainPtr doesn't work as promised

### ISSUE THREAD

**Issue by krzikalla** [alpaka-group/alpaka#655]
ViewPlainPtr has a 

`auto operator=(ViewPlainPtr &&) -> ViewPlainPtr & = default;`

However, since there are some const members in ViewPlainPtr , this operator will never work. 
Also, why is 

`auto operator=(ViewPlainPtr const &) -> ViewPlainPtr & = delete;`

Compared with the other line I don't see a reason for the deletion here.

**Comment by BenjaminW3** [comment]
Let's first think about the constructors.
* copy constructor: `ViewPlainPtr(ViewPlainPtr const &) = delete` is wrong. You should be able to create a copy of the View. I will fix this.
* move constructor: There is nothing to move in this class, the members are all simple types which have to be copied anyway. If we want to keep the const members, we could fix this constructor by implementing it by hand doing copies on the members.

I am still undecided about the assignment operators. I clearly see the benefit of const members but I also see why you would want to assign the views.

**Comment by BenjaminW3** [comment]
Both constructors (copy and move) now work as expected. As written above I will have a look at the assignment.
