### ISSUE TITLE
Boost 1.69.0 beta 1

### ISSUE THREAD

**Issue by ax3l** [alpaka-group/alpaka#706]
Boost 1.69.0 beta 1 is released, shall we give it a try before the main release? :)

**Comment by BenjaminW3** [comment]
I created a branch to test it. Let's see.

**Comment by BenjaminW3** [comment]
boost.test can not be found. No time at the moment to look into this: https://travis-ci.org/BenjaminW3/alpaka/builds/462096169

**Comment by ax3l** [comment]
Hm, they improved the install somehow which probably breaks the CMake `FindBoost` module.
https://www.boost.org/doc/libs/1_69_0_beta1/libs/test/doc/html/boost_test/change_log.html

**Comment by BenjaminW3** [comment]
Thanks for the hint! I will try out the newly documented header-only-mode. Maybe this solves our problem and also removes the necessity to build and link the lib.

**Comment by BenjaminW3** [comment]
The build is getting green now.

**Comment by BenjaminW3** [comment]
Tested since #717
