### ISSUE TITLE
PGI Community Docker Images

### ISSUE THREAD

**Issue by ax3l** [alpaka-group/alpaka#707]
The latest [PGI Community release](https://www.pgroup.com/products/community.htm) has made docker images available for usage in cloud environments (via the [Nvidia NGC registry](https://ngc.nvidia.com/catalog/containers/hpc%2Fpgi-compilers)).

We can check if we could use them for testing:
https://www.pgroup.com/products/new-features.htm

**Comment by j-stephan** [comment]
We have been using a NVHPC CI runner for a while now which uses a NVIDIA-supplied docker image under the hood.
