### ISSUE TITLE
GCC 5.5 in Release Mode with NVCC 9.X

### ISSUE THREAD

**Issue by ax3l** [alpaka-group/alpaka#720]
We can't compile the tests in `Release` mode for the combination of NVCC 9.X and GCC 5.5 since this hits for two of our build entries in the CI matrix the following bugs:
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=76731
- https://github.com/tensorflow/tensorflow/issues/10220

CI example link:
- https://travis-ci.org/ComputationalRadiationPhysics/alpaka/builds/474378136

Current work-around in CI:
- https://github.com/ComputationalRadiationPhysics/alpaka/blob/4688e49b18424e8c5f978fe5464ffbf9c884ec78/script/travis/before_install.sh#L98

Original comment:
- https://github.com/ComputationalRadiationPhysics/alpaka/pull/718#issuecomment-451067138

**Comment by j-stephan** [comment]
We no longer support GCC 5.
