### ISSUE TITLE
Abstraction of complex numbers

### ISSUE THREAD

**Issue by DerWaldschrat** [alpaka-group/alpaka#734]
As I am working on the second project by now that requires the use of complex numbers in an alpaka kernel, I agreed with @psychocoderHPC , @tdd11235813 and @sbastrakov that it probably is a good idea to provide some abstractions for using complex numbers in alpaka.
This is due to the following. By now, there is a standardized interface for complex numbers in `std::complex<RealType>` which ships with abs, exp and trigonometric functions. Unfortunately, the STL version of std::complex is not usable in CUDA code as all its functionality is not marked as a `__device__` function. However, in [thrust/complex.h][thrust-complex], there exists an implementation which is suitable for all accelerators and furthermore binary compatible to the `std::complex` implementations (and other complex types like `cuComplex/cuDoubleComplex`). The only problem is that this is only available by default when CUDA is enabled. So, it is not possible to use this directly when only relying on alpaka by now.
To solve this, there are two potential solutions:
* Provide a copy of a modified [thrust/complex.h][thrust-complex] wrapped in alpaka. This is the preferable solution we agreed on initially, but I inspected it and found out that it is not a mere copy of std::complex with `__device__` added, but a complete reimplementation of all the functions including the trigonometric ones. So this might be problematic due to license issues.
* Provide an easy solution to switch between `std::complex` and `thrust::complex`. This would look like some trait deciding which one to use depending on the accelerator accompanied by complex math functions like they already exist in the form of `alpaka::math`. This is possible as the classes std::complex and thrust::complex share the same interface. But, this might fail for future accelerators as there might be platforms where none of the above implementations is available.

Feel free to add some other solutions.
I have already implemented the second for a small project, but it is very incomplete as I only needed the base functionality of the complex class itself, two functions and two accelerator types.
What do you think?

[thrust-complex]: https://github.com/thrust/thrust/blob/master/thrust/complex.h

**Comment by sbastrakov** [comment]
@DerWaldschrat if possible, could you please put a link to the small project with your initial implementation of the second approach?

**Comment by sbastrakov** [comment]
Btw with the first approach in terms of licencing I think with their Apache 2 code it is not impossible. In that case, we could have a derived work and just would need to state what we modified, which in this case I guess is not difficult (mostly rename namespaces and replace `__host__ __device__` with alpaka macros). This however seems more convenient to do with a standalone library which alpaka also uses, but that may somewhat defeat the purpose of having support for complex out of the box.

**Comment by ax3l** [comment]
Actually the second approach, which just uses `thrust::complex` when available, which comes bundled in the CUDA sdk anyway, to specialize our `complex` math is a viable way to go.

Side note: might improve in the future :) https://github.com/ogiroux/freestanding/issues/2

**Comment by tdd11235813** [comment]
keep in mind, that required math functions still have to be redefined in alpaka depending on the accelerator type. Same case like alpaka::math for integral types. I do not see a real benefit from using thrust. We can define our own binary-compatible complex type that supports all worlds. 
[LiFFT](https://github.com/ComputationalRadiationPhysics/liFFT/blob/master/include/libLiFFT/types/Complex.hpp) does the same to offer an abstraction for the FFT library specific complex types.
What do you think?

(the repository is currently private, but ~~[open](https://github.com/ComputationalRadiationPhysics/primitive-api)~~ [open](https://github.com/ComputationalRadiationPhysics/ElectronBunchReconstruction/tree/master/include/vikunja/complex) to alpaka developers)

Edit: fixed link to repo (thanks @DerWaldschrat)

**Comment by ax3l** [comment]
What I mean is: we define math interfaces supporting std::complex, but for the CUDA backend we only provide them when thrust is found. Indeed, that's not ideal.

> We can define our own binary-compatible complex type that supports all worlds.

Yes, that's option one that I also prefer, @DerWaldschrat just mentioned that it looks more than he expected initially. I think we should just re-implement it similar to LiFFT's solution for now.

**Comment by DerWaldschrat** [comment]
@tdd11235813 That is not the repo I mentioned in the second version. The code is in the [ElectronBunchReconstruction](https://github.com/ComputationalRadiationPhysics/ElectronBunchReconstruction/tree/master/include/vikunja/complex) repo, which is unfortunately private as well.

**Comment by BenjaminW3** [comment]
I do not think that we should add a complex number library directly into core alpaka.
Alpaka is build as abstraction layer over the hardware and provides basic primitives (mathematical as well as other things) which can be used to build higher level things. For now I would prefer to see such higher level primitives separated from the main library. This could be an external repository in the first version but it could also be a separate folder within apaka.

**Comment by ax3l** [comment]
Sure, we just need to ship it by default with alpaka but can implement it in a general way, that just allows (like llama) to pass alpaka-controlled macros for device annotations. But it's actually not that large that one can not also keep it as a simple alpaka implementation detail.

**Comment by j-stephan** [comment]
We discussed this in today's meeting. We will implement this for alpaka 0.7.0.

Assigned to @sbastrakov.
