### ISSUE TITLE
Potential implementation of some metafunctions without recursion

### ISSUE THREAD

**Issue by sbastrakov** [alpaka-group/alpaka#738]
This is not a bug or a defect really, but I've just stumbled upon a piece of code, which could be used to implement functions like `meta::Conjunction` without recursive instantiation of templates. [SO answer](https://stackoverflow.com/a/36934374).

Applied for conjunction would be as follows (saw it [here](https://www.fluentcpp.com/2019/01/25/variadic-number-function-parameters-type/)):
```C++
template<bool...> struct bool_pack{};
template<class... Ts>
using conjunction = std::is_same<bool_pack<true,Ts::value...>, bool_pack<Ts::value..., true>>;
```

Ofc it is more or less just an improvement in elegance, and potentially slightly in compile time, so really not necessary to do at all. (But anyways the trick is cute).

**Comment by BenjaminW3** [comment]
Simply create a PR if this works ;-)

I would still prefer to replace the whole metaprogramming part by a library but most of them are not supported by CUDA.

**Comment by sbastrakov** [comment]
It does work in a logical sense. However, maybe I got over excited about this trick and in reality it is not worth implementing. The current implementation seems to be based on cppreference and thus follows all requirements for [`std::conjunction` in C++17](https://en.cppreference.com/w/cpp/types/conjunction). If we replace with the proposed implementation, there are two differences:

1. The resulting type is always derived from `std::integral_constant`, and not from `B1`.
2. It is not short-circuiting, which affects both compile time and, more importantly, the behaviour in case some types are ill-formed.

**Comment by BenjaminW3** [comment]
You are right, this might not be 100% standard conformant. Therefore I would keep the current version.
