### ISSUE TITLE
Add OMP to OSX CI tests

### ISSUE THREAD

**Issue by BenjaminW3** [alpaka-group/alpaka#740]

**Comment by ax3l** [comment]
Just a note:

It would be good if the OSX tests can compile with `clang` as well.
AppleClang is the default compiler (with XCode) on OSX and by default it builds with an older `libc++`.

**Comment by BenjaminW3** [comment]
TBB added with #742 #746

**Comment by BenjaminW3** [comment]
Without a real mac it is not easy to get the OpenMP backends working.
Installing it via `brew install libomp` (next to `brew install tbb`) works but then the build fails.
Coud someone with a mac try to get this working? @ax3l?

**Comment by ax3l** [comment]
I also just have an old mac at home that is not really my own :D
Can you link the branch and CI build you currently work on?

**Comment by BenjaminW3** [comment]
It is the `topic-osx-omp` branch on my fork. You probably have to revert the changes I did to the `alpakaConfig.cmake` file.

**Comment by q-p** [comment]
I was using a homebrew-installed gcc@7 (or 8) successfully on a Mac to compile alpaka-using software.

Note that the system compiler (Apple-customized clang) unfortunately doesn't include OpenMP support. :(

Note that libgomp (gcc's OpenMP support library) is really quite slow on Mac, same as anything else that build pthreads on the system (e.g. std::mutex, etc.). You can link against Intel's OpenMP runtime (libiomp IIRC) for a decent speed-up, as that provides libgomp-compatible symbols. The Intel OpenMP runtime can be used from homebrew's llvm / clang (by manually linking against it instead of using `-fopenmp`), for example.

**Comment by j-stephan** [comment]
@tonydp03 Could you maybe take a look at this once you have finished the atomic tests?

**Comment by tonydp03** [comment]
Yes, sure I'll give it a try.

**Comment by tonydp03** [comment]
Locally on my macbook pro 2017 (MacOs Monterey 12.0.1, Apple clang version 13.0.0 (clang-1300.0.29.3)), using the latest develop branch, tests are built and run successfully if selecting the backend `ALPAKA_ACC_CPU_B_OMP2_T_SEQ_ENABLE` or `ALPAKA_ACC_CPU_B_SEQ_T_OMP2_ENABLE`. Build fails if selecting the backend `ALPAKA_ACC_ANY_BT_OMP5_ENABLE` with the following error:
```
[  2%] Linking CXX executable axpyTest
Undefined symbols for architecture x86_64:
  "_omp_target_alloc", referenced from:
      void ____C_A_T_C_H____T_E_M_P_L_A_T_E____T_E_S_T____F_U_N_C____0<alpaka::AccOmp5<std::__1::integral_constant<unsigned long, 1ul>, unsigned long> >() in axpy.cpp.o
  "_omp_target_free", referenced from:
      alpaka::omp5::detail::DevOmp5Impl::~DevOmp5Impl() in axpy.cpp.o
      std::__1::__shared_ptr_emplace<alpaka::detail::BufOmp5Impl<float, std::__1::integral_constant<unsigned long, 1ul>, unsigned long>, std::__1::allocator<alpaka::detail::BufOmp5Impl<float, std::__1::integral_constant<unsigned long, 1ul>, unsigned long> > >::__on_zero_shared() in axpy.cpp.o
  "_omp_target_memcpy", referenced from:
      void ____C_A_T_C_H____T_E_M_P_L_A_T_E____T_E_S_T____F_U_N_C____0<alpaka::AccOmp5<std::__1::integral_constant<unsigned long, 1ul>, unsigned long> >() in axpy.cpp.o
      void alpaka::memcpy<alpaka::Vec<std::__1::integral_constant<unsigned long, 1ul>, unsigned long>, alpaka::BufCpu<float, std::__1::integral_constant<unsigned long, 1ul>, unsigned long>, alpaka::BufOmp5<float, std::__1::integral_constant<unsigned long, 1ul>, unsigned long>, alpaka::QueueGenericThreadsBlocking<alpaka::DevOmp5> >(alpaka::QueueGenericThreadsBlocking<alpaka::DevOmp5>&, alpaka::BufOmp5<float, std::__1::integral_constant<unsigned long, 1ul>, unsigned long>&, alpaka::BufCpu<float, std::__1::integral_constant<unsigned long, 1ul>, unsigned long> const&, alpaka::Vec<std::__1::integral_constant<unsigned long, 1ul>, unsigned long> const&) in axpy.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [test/integ/axpy/axpyTest] Error 1
make[1]: *** [test/integ/axpy/CMakeFiles/axpyTest.dir/all] Error 2
```

**Comment by psychocoderHPC** [comment]
IMO it is not a problem that `ALPAKA_ACC_ANY_BT_OMP5_ENABLE` is failing on MacOSX. @jkelling is MacOSX supporting OpenMP 5?

**Comment by j-stephan** [comment]
IMO this should be caught by CMake since it checks for the OpenMP version. Apparently CMake believes that OpenMP 5 is supported but fails to properly link the library.
