### ISSUE TITLE
Fix bash variable existance checks on OSX

### ISSUE THREAD

**Issue by BenjaminW3** [alpaka-group/alpaka#741]
All of the `[ -v Variable ]` tests fail because it is not supported on osx. Those errors seem to be ignored but this leads to wrong arguments to cmake (none of the variables are passed to cmake) and therefore all defaults are used.

**Comment by ax3l** [comment]
Maybe just `[ -z ${bashVar+x} ]`? [ref: SO](https://stackoverflow.com/questions/3601515/how-to-check-if-a-variable-is-set-in-bash)

Maybe the bash on OSX is just too old
> The '-v' argument to the 'test' builtin was added in bash 4.2

or actually not a bash but another shell (iirc, by default it's a `zsh` on OSX). So let's just avoid too fancy bashism for CI and helper scripts to be maximum compatible (to `sh` or at least zsh/csh/dash/bash).

**Comment by BenjaminW3** [comment]
Yes, I already tried updating the bash used on osx via homebrew but it did not help.
The -z or -n version would probably help but then we would have to remove set -o which finds usages of undefined variables.

**Comment by ax3l** [comment]
Actually works as is in that context from my tests, thanks to the `+x` [parameter expansion](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_02). You can keep the strict settings for good :)

> Yes, I already tried updating the bash used on osx via homebrew but it did not help.

Did you also prepend the `PATH` and changed into a fresh bash process? But anyway, just progress as suggested above for compatibility with OSX desktop users.

**Comment by BenjaminW3** [comment]
Yes, I verified that the new bash version was used. I also prefer a platform independant version because those scripts will often be used as template for local development as well.

I meant set -u not -o

**Comment by ax3l** [comment]
Yes, set -u should still work. I took the current options for testing :)
