### ISSUE TITLE
Add support for CUDA 10.1

### ISSUE THREAD

**Issue by BenjaminW3** [alpaka-group/alpaka#758]
* [x] fix compilation errors

**Comment by MarkusVelten** [comment]
For my application, simply changing `auto currentTaskPackage(std::shared_ptr<ITaskPkg>{nullptr});` to `auto currentTaskPackage = std::shared_ptr<ITaskPkg>{nullptr};` in `include/alpaka/core/ConcurrentExecPool.hpp` in lines 342, 429, 550, 642 did the trick. Compilation with CUDA 10.1 and gcc-8 works for me with those changes. I don´t know whether or not this fixes all compilation errors for all use cases/tests, but it might help.

**Comment by BenjaminW3** [comment]
Thanks, I will try this!

**Comment by BenjaminW3** [comment]
Works, thanks!
