### ISSUE TITLE
internal compiler error with gcc 7.3.0 and CUDA 10.0.130

### ISSUE THREAD

**Issue by jthies** [alpaka-group/alpaka#765]
Alpaka version 0.3.5

Alpaka seems to build fine, but compiling the application leads to an internal compiler error (see 
[build-log.txt](https://github.com/ComputationalRadiationPhysics/alpaka/files/2967156/build-log.txt))

I have a successful build with gcc 5.4.0 and CUDA 9.0.176

**Comment by sbastrakov** [comment]
Thanks for your report. 

I investigated on Hemera with alpaka 0.3.5 and modules boost, gcc/7.3.0 and cuda/10.0, and using the Omp2Threads accelerator (same that caused issue in the attached log) in our vectorAdd example. Alpaka cmake has requirement only for C++11 and then it all built fine for me. However, in the attached log there is C++14 and setting this manually in our cmake leads to same error at the same place (include/alpaka/exec/ExecCpuOmp2Threads.hpp:211:1).

Behavior looks like [this issue](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=882855).

**Comment by sbastrakov** [comment]
The same issue is also present for the current `develop` branch with the same configuration: gcc 7.3.0, C++14 (changed from default C++11), Omp2Threads accelerator with internal compiler error [here](https://github.com/ComputationalRadiationPhysics/alpaka/blob/5d1b40156268763248e81f2cab88d9469d2932c1/include/alpaka/kernel/TaskKernelCpuOmp2Threads.hpp#L169), [full build log](https://github.com/alpaka-group/alpaka/files/2967502/build_log_develop.txt)

**Comment by jthies** [comment]
thanks for the quick reply, I'm glad you can so readily reproduce the issue

**Comment by sbastrakov** [comment]
So there seem to be the following ways to avoid the issue. Each of the following should be individually enough:

- Patch the code manually, it is a single line change. For version 0.3.5 change [this line](https://github.com/alpaka-group/alpaka/blob/b5c66c2a48e097e06bf1c69fb2c83b99d96d70b0/include/alpaka/exec/ExecCpuOmp2Threads.hpp#L194) to `#if (!BOOST_COMP_GNUC) || (BOOST_COMP_GNUC < BOOST_VERSION_NUMBER(5, 0, 0)) || (BOOST_COMP_GNUC >= BOOST_VERSION_NUMBER(6, 0, 0)) && (BOOST_COMP_GNUC != BOOST_VERSION_NUMBER(7, 3, 0))` to exclude the failing gcc 7.3.0 version. (For `develop` I guess a similar fix would work, but to a different line.)
- Use `Omp2Blocks` accelerator instead of `Omp2Threads` - whether it is viable depends on the application, however we normally prefer `Omp2Blocks` as the OpenMP backend.
- Use C++11 and not C++14 if the application allows it.
- In case it is actually [the gcc issue linked above](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=882855) (looks like, but not 100% sure), updating the compiler might help.

**Comment by sbastrakov** [comment]
@jthies just wondering, did any of my suggestions help?

**Comment by jthies** [comment]
Hi @sbastrakov, yes - sorry - thanks for the advice. We can't switch to std=c++11, so that one's out. But the simple patch will do for us for the moment. I can't confirm wether it's specific for gcc 7.3.0, though, because I only tested with this one (CUDA 10 doesn't support gcc 8). You may want to keep the issue open, though, because I think it's not really resolved and others may run into it.

**Comment by krzikalla** [comment]
I couldn't resolve it in Alpaka 0.4.0 using just the small patch. Thus, for now I have to give up migrating to 0.4.0 since the other options don't work for us.

**Comment by krzikalla** [comment]
In version 0.4.1. I have to conditionally comment out the whole omp single nowait block starting at 
TaskKernelCpuOmp2Threads.hpp:164 with 

#if (!BOOST_COMP_GNUC) || (BOOST_COMP_GNUC >= BOOST_VERSION_NUMBER(8, 1, 0))

According to the internet gcc >= 8.1. fixes the issue. OTOH I question that omp single nowait block  at all. It is there for debugging purposes only and the "omp single nowait" clause might cause performance issues. Has the block ever thrown?

**Comment by BenjaminW3** [comment]
Yes, the block has thrown.
Years ago I had some problems with OMP environment variables enforcing lower thread counts. This may or may not be an issue anymore.
However, this check found a regression in the Microsoft compiler where omp got broken.

If we have some benchmark numbers where this block has some reasonable influence, we could hide it by surrounding it with `#if ALPAKA_DEBUG >= ALPAKA_DEBUG_MINIMAL`. This would add the risk of wrong results without the user knowing that something went wrong.

**Comment by krzikalla** [comment]
What is the state of the issue? We still have to add the line

#if (!BOOST_COMP_GNUC) || (BOOST_COMP_GNUC >= BOOST_VERSION_NUMBER(8, 1, 0))

(see above)

in alpaka 0.5.0. Will it be fixed?

**Comment by sbastrakov** [comment]
Hello @krzikalla .

Sorry for a potentially stupid question. Does this kind of #if guard patch work for you with alpaka 0.5.0? Earlier in the issue you [wrote](https://github.com/alpaka-group/alpaka/issues/765#issuecomment-534074216) that it does not work for 0.4.0 (and I don't think this part is different in 0.5.0), or am I misunderstanding?

Edit: ah, I missed your next message for 0.4.1, sorry.

**Comment by krzikalla** [comment]
This [one](https://github.com/alpaka-group/alpaka/issues/765#issuecomment-623407674) explains the proper patch.

**Comment by sbastrakov** [comment]
I think we could add this workaround to alpaka, what do you think @BenjaminW3 @psychocoderHPC ?

**Comment by psychocoderHPC** [comment]
@krzikalla Offline discussed with @sbastrakov he will port the suggested fix into the development mainline.

**Comment by sbastrakov** [comment]
@krzikalla I made a PR #1063 with your suggestion, if I understood it right. However, the original problem does not reproduce for me on Hemera with fresh alpaka (I guess no surprise that internal compiler bugs are not always stable). So could you check that PR?
