### ISSUE TITLE
Passing kernel arguments by value/&/const &/&&

### ISSUE THREAD

**Issue by BenjaminW3** [alpaka-group/alpaka#772]
This is the follow up to an offline discussion. It is not yet a real issue.

Alpaka enforces that kernel arguments are either taken by `value` or by `const &`.

* `&&` would not work because the ownership of the parameters can not be transferred because this would result in an owenership transfer to the first thread that is executed. The arguments have to be accessible by all threads so this is not possible.
* `&` would be possible but is currently not allowed because the CPU backends take a shortcut and never make a copy of the original parameters but simply pass a reference to those arguments to the kernel. You either copy them and you can edit them or you use `const &` and get a immutable reference because changing the original parameter would be visible by all other threads.
* `value` (copy) behaves differently than it does for CUDA `__global__` kernels. In CUDA the parameters are copied for each thread, but it is a simple memcpy so the copy-consturctor is NOT called. With alpaka, the `__global__` kernel is hidden and there is a copy from the alpaka internal `__global__` function into the user provided `__device__` kernel function which invokes the real copy-consturctor of those objects. This is different to what a native CUDA kernel is doing.

**Comment by j-stephan** [comment]
alpaka now enforces that kernel arguments are trivially copyable. So option 3 is what we went for. I don't think the documentation has been updated accordingly, though.

**Comment by bernhardmgruber** [comment]
So the only thing left in this issue is to upate the documentation? Nothing else is asked for?

**Comment by j-stephan** [comment]
Yes. The requirement of trivially copyable kernel arguments needs to be documented. Otherwise the issue is done.
