### ISSUE TITLE
How do I handle multithreaded queues? 

### ISSUE THREAD

**Issue by krzikalla** [alpaka-group/alpaka#783]
The following code shall synchronize dest with the content of src. It shall work with all types of queues (asynchronous and synchronous) and it shall work multithreaded.

```
enum { OUT_OF_SYNC, SYNCING, IN_SYNC };
std::atomic<int> state = OUT_OF_SYNC;

template<class T>
void StartSynchronize(T& queue)
{
  int expected = OUT_OF_SYNC;
  if (state.compare_exchange_strong(expected, SYNCING))
  {
    alpaka::mem::view::copy(queue, dest, src, size);
  }
}

template<class T>
void WaitSynchronize(T& queue)
{
  alpaka::wait::wait(queue);
  int expected = SYNCING;
  state.compare_exchange_strong(expected, IN_SYNC);
}  
```

The problem is, that QueueCpuSync::waitForThread is a noop and hence doesn't wait for the copy, which might be running in another thread. 
Is there a way to do the above with Alpaka means and independent of the particular queue type?

**Comment by BenjaminW3** [comment]
If I understand this ticket and #768 correctly they are the same issue. Could you please answer my question I already gave you in the other ticket?

**Comment by krzikalla** [comment]
OK, so we have to distinguish between asynchronous and synchronous queues:

```
template<class T>
void StartSynchronize(T& queue)
{
  int expected = OUT_OF_SYNC;
  if (state.compare_exchange_strong(expected, SYNCING))
  {
    alpaka::mem::view::copy(queue, dest, src, size);
    if (queue is synchron)
    { 
       state = IN_SYNC;
    }      
  }
}

template<class T>
void WaitSynchronize(T& queue)
{
  if (queue is synchron)
  { 
     while (state != IN_SYNC) {}
  }
  else
  {
    if (state != IN_SYNC)
    {
      alpaka::wait::wait(queue);
      state = IN_SYNC;
    }
  }
}  
```

How do I tell, if a queue is synchron? And am I allowed to call alpaka::wait::wait from multiple threads?

**Comment by BenjaminW3** [comment]
> OK, so we have to distinguish between asynchronous and synchronous queues

This is not the goal of alpaka and if this is currently necessary e have to fix this.

> am I allowed to call alpaka::wait::wait from multiple threads?

I can not tell this for sure but by looking at the code this should work.

**Comment by psychocoderHPC** [comment]
> > OK, so we have to distinguish between asynchronous and synchronous queues
> 
> This is not the goal of alpaka and if this is currently necessary e have to fix this.

We should evaluate if such a behavior is required. @krzikalla do you have special workflows where you must mix synchronous and asynchronous queues?

**Comment by krzikalla** [comment]
I don't want to mix synchronous and asynchronous queues. I just like to write my code so, that it works for synchronous and asynchronous queues. 
Currently the same code is executed for StreamCudaRtSync and StreamCpuSync, but this will be extended to StreamCudaRtASync later on.
Currently I have alpaka::wait::wait directly after alpaka::mem::view::copy. This doesn't do any harm and would work with StreamCudaRtASync too. However it would also counter the idea of an asynchronous stream. Thus I am looking for another position of alpaka::wait::wait, which works under my preconditions (multiple threads, different streams) too. I guess, currently there is no simple alpaka solution. Would be good to have one.

**Comment by BenjaminW3** [comment]
> I don't want to mix synchronous and asynchronous queues. I just like to write my code so, that it works for synchronous and asynchronous queues.

This is what the change in #786 achieved. Now it should not matter anymore if it is a blocking or non-blocking queue. 

Generally I discourage the usage of `alpaka::wait::wait(queue)`. There are much more direct ways to achieve the same behaviour in most cases. `Event`s should be used to express inter-queue dependencies and queue callbacks can be used when you need direct feedback from a queue on the CPU.

**Comment by BenjaminW3** [comment]
I will close this for now because the original issue of this ticket has been fixed now that wait also works for blocking queues (called from a different thread).
Feel free to open a new issue if we could not address other issues.
