### ISSUE TITLE
Add unit tests for math functions

### ISSUE THREAD

**Issue by tdd11235813** [alpaka-group/alpaka#785]
Add unit tests for the operators in alpaka math. 
- use compile-time list of operators and std:: pendant to validate result copied from device
- for floats one can use the device-compatible function `almost_equal()` in sincos #755 PR, or you can use [catch2 matchers](https://github.com/catchorg/Catch2/blob/master/docs/matchers.md#floating-point-matchers) because results are compared on the host side only
- sincos validation also could follow that (instead of comparing results on the device side)
- fix double/single precision CUDA functions ( sin, sinf, ...)
- long int -> long long int in `include/alpaka/math/round/RoundStdLib.hpp`

Edit: added single/double precision fix request
Edit: added long int issue
Edit: -> #847

**Comment by BenjaminW3** [comment]
Implemented by #847
