### ISSUE TITLE
Create an upgrade guide?

### ISSUE THREAD

**Issue by sbastrakov** [alpaka-group/alpaka#790]
As discussed offline at the meeting yesterday, with the upcoming new release of alpaka it might make sense to add a short summary of how to change a client code to switch to the new version (e.g. streams become queues, etc.). Maybe smth like [what openPMD-api uses](https://github.com/openPMD/openPMD-api/blob/dev/NEWS.rst). If we agree to do this, I could make a draft, to be extended/fixed later by people more knowledgeable about alpaka.

**Comment by ax3l** [comment]
Examples when embedded in the manual:
https://openpmd-api.readthedocs.io/en/0.8.0-alpha/install/upgrade.html
https://pybind11.readthedocs.io/en/master/upgrade.html

**Comment by BenjaminW3** [comment]
I already added a category called `Breaking changes` to the release notes of the upcoming release. It should contain everything that has to be done for updating.

**Comment by BenjaminW3** [comment]
I will close this ticket for now because we already have such documentation. Feel free to update/extend the release notes if you see a need for better upgrade instructions.
