### ISSUE TITLE
Allow datatypes with alignment > core::vectorization::defaultAlignment

### ISSUE THREAD

**Issue by holke** [alpaka-group/alpaka#823]
For our linear algebra library we are using alpaka together with the SIMD vectorization library [Vc](https://github.com/VcDevel/Vc) and in order to efficiently implement multiscalars we use the datatype Vc::SimdArray. This datatype models a constant number of doubles (like a constant array) together with SIMD support for elementwise operations.
The alignment of Vc::SimdArray may be larger than 64 (i.e. 128, 256) and when using it as scalar dataype together with alpaka we cause the following assertion:

[../thirdparty/alpaka-0.3.5/include/alpaka/block/shared/st/BlockSharedMemStNoSync.hpp:92:29:](https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/include/alpaka/block/shared/st/BlockSharedMemStNoSync.hpp) error: static assertion failed: Unable to get block shared static memory for types with alignment higher than defaultAlignment!

This is due to the line 

static_assert(core::vectorization::defaultAlignment >= alignof(T),…);

followed by the allocation 

 boost::alignment::aligned_alloc(core::vectorization::defaultAlignment, sizeof(T)).

defaultAlignment is hardcoded to 16,32, or 64 in [Vectorize.hpp](https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/include/alpaka/core/Vectorize.hpp).

We would be happy if alpaka could support types with larger alignment and suggest to fix the approriate allocations by choosing the maximum of defaultAlignment and alignof(T) (or the least common multiple) as alignment instead of defaultAlignment.

As @sbastrakov  pointed out in a personal answer to me, the alignments were introduced in [pull/322](https://github.com/ComputationalRadiationPhysics/alpaka/pull/322).

**Comment by sbastrakov** [comment]
@holke thanks for reporting here.
We have discussed offline with @psychocoderHPC that the suggestion looks reasonable.

**Comment by BenjaminW3** [comment]
I will take a look at this.

For static block shared memory allocation (`allocVar`) this should be no problem.

However, for dynamically allocated block shared memory this is not so easy. In this case we do not know the type before allocating the buffer. We only cast the pointer to the specific type afterwards. [See here](https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/include/alpaka/block/shared/dyn/BlockSharedMemDynBoostAlignedAlloc.hpp)

**Comment by BenjaminW3** [comment]
Do you need a solution for dynamically allocated block shared memory as well? We could simply waste some memory and overalign the memory to e.g. 256 bytes in this case.

**Comment by BenjaminW3** [comment]
@holke Could you please have a look at #824 and tell me if it solves your issue?

**Comment by holke** [comment]
Yes it solves my issue. Thank you.
Currently we do not have issues with the dynamically allocated memory.
Thanks for the quick replies.
