### ISSUE TITLE
cudaErrorIllegalInstruction in nvstd part in test/kernel

### ISSUE THREAD

**Issue by tdd11235813** [alpaka-group/alpaka#836]
- kernel test fails on Nvidia GPUs (on taurusa1 (V100, GV100, P100) and on GTX1080Ti node)
  - tested with: CUDA 10.0.130, CUDA 9.2.88; gcc7.3.0, gcc6.4.0; Boost1.66.0; different `ALPAKA_CUDA_ARCH`s
- when nvstdFunctionKernelIsWorking (KernelStdFunction.cpp) is commented, then tests pass

```zsh
terminate called after throwing an instance of 'std::runtime_error'
  what():  /alpaka/include/alpaka/mem/buf/BufCudaRt.hpp(112) 'cudaSetDevice( dev.m_iDevice)' A previous CUDA call (not this one) set the error  : 'cudaErrorIllegalInstruction': 'an illegal instruction was encountered'!

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
kernel is a Catch v2.7.2 host application.
Run with -? for options

-------------------------------------------------------------------------------
nvstdFunctionKernelIsWorking
-------------------------------------------------------------------------------
/alpaka/test/unit/kernel/src//KernelStdFunction.cpp:104
...............................................................................

/alpaka/test/unit/kernel/src//KernelStdFunction.cpp:104: FAILED:
  {Unknown expression after the reported line}
due to a fatal error condition:
  SIGABRT - Abort (abnormal termination) signal
```

**Comment by BenjaminW3** [comment]
As I can not reproduce this at the moment and "it worked for me"™️ on my consumer GPU with CUDA 9.0 on windows I would simply disable the test for now. Any objections?

**Comment by tdd11235813** [comment]
maybe this is only working on Windows. Also repeated test on hemera/K80 with CUDA9.0 with almost the same error (`cudaErrorIllegalAddress`).
I could reproduce it yet on another system (linux+RTX2070, CUDA 10.1.243) and it is almost the same, just that there is a `cudaErrorIllegalAddress` error: 
```
'cudaErrorIllegalAddress': 'an illegal memory access was encountered'!
```
We really need our own CI system to perform runtime tests (@SimeonEhrig is working on that when time permits, and the interconnect between github-gitlab-CI seems to work now).

We can disable the nvstd test, maybe only for linux?

(fun on local cluster: loaded cuda9.0 -> alpaka only accepts gcc5.5.0 or less with cuda9.0 -> by that cmake3.15.2 cannot be used due to old libstdc++ -> only have cmake3.11.3 as 2nd option on hemera -> but alpaka wants cmake3.11.4+ -> using downloaded cmake binary again)

**Comment by SimeonEhrig** [comment]
@psychocoderHPC 
We should try to connect the Alpaka Repo to our GitLab CI nodes next week.
