### ISSUE TITLE
Lots of warnings with 0.4.0.

### ISSUE THREAD

**Issue by psychocoderHPC** [alpaka-group/alpaka#842]
@krzikalla reported hundreds of warnings like this one:

```
../thirdparty/alpaka-develop/include/alpaka/vec/Vec.hpp(248): warning: device annotation is ignored on a function("operator=") that is explicitly defaulted on its first declaration
```

Applies to device and host annotations.

Used cuda compiler flags
```
['-x=cu', '-ccbin', '/scratch/FSDM/rhel_7_6/fs_dependencies/gcc/bin/g++', '-m64', '-Xcompiler', '"-g","-fopenmp","-ggdb","-fPIC","-std=c++14"', '--expt-extended-lambda', '--expt-relaxed-constexpr', '--use_fast_math', '--ftz=false', '--generate-code', 'arch=compute_52,code=sm_52', '-std=c++14', '-DALPAKA_ACC_GPU_CUDA_ENABLED']
```

I moved the cupla issue https://github.com/ComputationalRadiationPhysics/cupla/issues/119 to alpaka because @krzikalla opened the issue in the wrong repo.

**Comment by psychocoderHPC** [comment]
We need to remove the warning somehow else the compile suite from DLR will not pass :-(

**Comment by sbastrakov** [comment]
It looks like Kokkos also [encountered](https://github.com/kokkos/kokkos/issues/1473) this issue and they believe it is a compiler deficiency and so just silence it with a flag.

Edit: for them, it was some time ago, it needs to be checked if nvcc is actually doing the right thing now and we should actually fix the code.

**Comment by krzikalla** [comment]
Thank you for the pointer. This 

`-Xcudafe --diag_suppress=esa_on_defaulted_function_ignored
`
saved my day.

**Comment by sbastrakov** [comment]
So this suppresses the warning output. As I understood that Kokkos thread linked above, the thing is that default compiler-generated constructors and other special methods are actually different implementations for host and device (which makes sense), and so theoretically the correct way is to not annotate them with host and device qualifiers. However, in reality this way did not work with nvcc back then (and maybe now as well - need to check) as the device version was not generated properly. So the only way to make the compiler to generate both was to add these host device annotations, but then, of course, internally it is two different versions for host and device, and so in each of them one of the two annotations is ignored.

**Comment by BenjaminW3** [comment]
I had a look at our CMake output and we already add exactly this flag to our build options. This is not part of the 0.3.6 release but 0.4.0 should have contained this fix for a long time already. 
The CI builds also do not contain such warnings.
I will close this issue for now. If the warnings still appear for you, please re-open the issue.
