### ISSUE TITLE
Unify the Hip/Cuda backend

### ISSUE THREAD

**Issue by jkrude** [alpaka-group/alpaka#849]
Most **backend api-calls are really similar** and produce a rather great amount of code duplication.
For example all the `include/math` traits or `BufCudaRt/BufHipRt`. The code is equal except for some calls for example `cudaMalloc` is called instead of `hipMalloc`.
This is in fact so similar that a macro could be used to unify those code-duplications.
`cudaMalloc` is subsequently **replaced by a macro** similar to ALPAKA_CUDA_OR_HIP (Malloc), which decides whether to use `cudaMalloc` or `hipMalloc`.
So there will be only one file for *BufCudaRt/BufHipRt* and user-code will not be affected.
Whether it is possible to replace all those calls, still has to be explored.

**Comment by BenjaminW3** [comment]
This is exactly what I said when the HIP code was added. All this duplication should be removed ;-)

**Comment by tdd11235813** [comment]
yes, we asked @jkrude to help us with that, and there is hope, that the new hip-clang will behave even more like cuda. The former host-device restrictions by HCC/C++AMP are discussed [here](https://github.com/ROCm-Developer-Tools/HIP/issues/659#issuecomment-532744865). AMD is aware of that. 
You can take CUDA backend code as base (wrt host-device annotations) for now.
So we should also replace all the HCC namings with e.g. HIPC (HIP [clang] compiler) during the unification process, so this also affects alpakaConfig.cmake etc. (note, that HCC is the deprecated AMD GPU compiler).
If there are design questions, just leave a message here.

**Comment by tdd11235813** [comment]
@jkrude started unifying the CUDA HIP codes and we discussed together with @psychocoderHPC  the new design. So in the backend there will be only one unified codebase (e.g. CudaHipAccelerator ...) with `#if/else` for selecting cuda/hip commands, while the frontend provides (derived) types for Cuda and for Hip.
```c++
// example
using Acc = alpaka::acc::AccGpuCudaRt... // Cuda as before, so we are backwards compatible
using Acc = alpaka::acc::AccGpuHipRt... // same for HIP
using Acc = alpaka::acc::AccGpuCudaHipRt... // is the unified one, if you do not want to care about Cuda or Hip, and just want to have a GPU accelerator
```
- Not sure about namespaces though and the file structure should match, but I guess we mostly will have `alpaka::...::cudahip`
- cmake code:
  - there is a lot of redundancy wrt HIP and CUDA cmake parts
  - we could offer a unified `ALPAKA_ACC_GPU_CUDA_HIP...` parameter set with `ALPAKA_ACC_GPU_CUDA_HIP_COMPILER={nvcc,clang(nvcc),clang(hip-amd),clang(hip-nvcc),default}`
  - the device arch selector depends on the platform (AMD or NVIDIA), which would be encoded in the compiler name above

**Comment by tdd11235813** [comment]
For HIP(HCC/clang):
- The new hip-clang seems to behave much more like cuda, so we do not need to care about host-device flag-matching like with the deprecated hcc
- the unified hip/cuda would drop hcc support completely and #802 could be discarded already

**Comment by psychocoderHPC** [comment]
HIP clang works much better than the old hip compiler. I have currently tested only compiling to AMD GPUs and not NVIDIA. 
We should work soon on updating our cmake find scripts and CI to work with hip-clang instead of the old hip.

Note: I do not see it as a requirement for alpaka 0.4.0

**Comment by BenjaminW3** [comment]
@psychocoderHPC @tdd11235813 @jkrude Can this be closed now?
