### ISSUE TITLE
cudaMemset is not blocking

### ISSUE THREAD

**Issue by psychocoderHPC** [alpaka-group/alpaka#851]
Related to issue #850 the [cuda documentation for cudaMemset](https://docs.nvidia.com/cuda/cuda-runtime-api/api-sync-behavior.html#api-sync-behavior__memcpy-sync) is saying 

```
Memset
The synchronous memset functions are asynchronous with respect 
to the host except when the target is pinned host memory or a 
Unified Memory region, ...
```

This means calling `cudaMemset` to NON pinned or managed memory and directly after call a kernel which works with the date within another stream (unrelated if we created the stream with `cudaStreamNonBlocking`) we will have the possibility of a data race.

[update] I added NON into my sentence because as @sbastrakov pointed out it is safe to use cudaMemSet for pinned memory but not for NON pinned.

**Comment by BenjaminW3** [comment]
Ok, that explains it.
May this issue be related to https://github.com/ComputationalRadiationPhysics/alpaka/issues/504 ?

**Comment by psychocoderHPC** [comment]
Yes, this could be the reason. @sbastrakov and me currently trace the driver behaviors and check the cuda documentations and block posts. It looks like the behavior is expected but badly explained in the docs.

**Comment by sbastrakov** [comment]
Yes, so the quoted sentence is remarkably poorly phrased in my opinion. And I think @psychocoderHPC you also got it wrong (edit: now that message is fixed, thanks!). How I understand it is that `cudaMemset` is synchronous only when applied to pinned host memory or unified memory region. So your example use case is actually safe in that regard, but this is the only safe scenario.
