### ISSUE TITLE
Link to GTC 2016 Talk in Readme.md broken

### ISSUE THREAD

**Issue by juckel** [alpaka-group/alpaka#856]
The first Link for introduction material Introduction is broken:
"For a quick introduction, feel free to playback the recording of our presentation at GTC 2016:" links to http://mygtc.gputechconf.com/quicklink/858sI36 which requires a login.
I recommend just uploading the slides in ROBIS and linking to them there.

**Comment by ax3l** [comment]
Urgh, their homepage only includes the 2017+ recordings these days!

@psychocoderHPC I think it's best if you do that as shared first-author of that talk.

Please do not only add the slides but also a copy of the video recording of the talk. If you do not have its copy anymore, I can search for it on my other laptop. Should be there somewhere... Or on team->presentations...

**Comment by juckel** [comment]
The video link still works, but I was unable to guess the URL of the slides PDF.

**Comment by ax3l** [comment]
Ah, cool. So let's backup that one as well in the process to rodare :)

**Comment by psychocoderHPC** [comment]
I can have a look I think somewhere I have the slides. I do not think that I can upload a copy of the video because of copy right issues.

**Comment by ax3l** [comment]
Not sure they really had exclusive copyright, especially for us as authors. But might have implications, sure. Either way, at least backup the video into the team directory alongside your talk slides for future recovery :)

**Comment by j-stephan** [comment]
The video link still works but the slides are missing. The ROBIS entry unfortunately does not feature them: https://www.hzdr.de/publications/Publ-23569

Could someone add them to ROBIS?
