### ISSUE TITLE
Add arm64, ppc64le and s390x linux builds to CI

### ISSUE THREAD

**Issue by BenjaminW3** [alpaka-group/alpaka#860]
https://blog.travis-ci.com/2019-10-07-multi-cpu-architecture-support

We should try to add at least a single Arm64 build job.

**Comment by psychocoderHPC** [comment]
We are curently started to move cupla to our internal ci nodes. We will go on with alpaka after cupla is moved. 
So I suggest to do the arm build on the new ci nodes since we have ther native x86, arm and openpower nodes.

**Comment by BenjaminW3** [comment]
I am totally for adding the internal CI for CUDA runtime tests.
However, I would want to keep the travis builds as well because those allow me and everyone else to enable travis-ci builds for my (their) individual forks. I do not want to lose this.
I would like to keep travis as the main CI build system but additionally add the internal CI nodes for things that travis can not do.

**Comment by psychocoderHPC** [comment]
Yes I can understand it. But we should think about reducing the complexity for the travis tests. So that we can finish those tests faster.

As soon as we ported stuff to the internal CI we should have a video meeting about the CI handling.

**Comment by ax3l** [comment]
The "internal CI" repos will be made public on https://gitlab.hzdr.de, I guess?
Best to document them and their usage in Alpaka itself as well (or at least link to its docs).

**Comment by psychocoderHPC** [comment]
Yes we will make all public. Here is the script we are currently working on https://github.com/ComputationalRadiationPhysics/cupla/blob/dev/.gitlab-ci.yml

@BenjaminW3 likes to keep travis to allow the same tests within his fork.

**Comment by BenjaminW3** [comment]
[Travis CI now also supports IBM Power and IBM Z CPU architectures.](https://blog.travis-ci.com/2019-11-12-multi-cpu-architecture-ibm-power-ibm-z) with `arch: ppc64le` or `arch: s390x`.
So this looks really good!
Now they only have to add some NVIDIA GPUs and it would be perfect ;-)

**Comment by BenjaminW3** [comment]
As we want to reduce our external dependencies and go away from travis, I will close this.
