### ISSUE TITLE
memory pinning

### ISSUE THREAD

**Issue by psychocoderHPC** [alpaka-group/alpaka#873]
Currently, we are only able to pin memory if we are using CUDA. We have an open issue to pin memory maybe with hwloc #634.
I am currently working on adding memory pinning for AMD HIP-clang and found the following documentation for [hipHostRegister](https://rocm-developer-tools.github.io/HIP/group__Memory.html#gab8258f051e1a1f7385f794a15300e674)

```
...
Developers are strongly encouraged to register memory blocks which are aligned to the host cache-line size. (typically 64-bytes but can be obtains from the CPUID instruction).
...
```

The problem is that we in alpaka first allocate memory and then pin this memory. This will lead in data races when the driver is syncing two allocations within the same cache-line.
We are fighting since a few months in PIConGPU with an [issue 2996](https://github.com/ComputationalRadiationPhysics/picongpu/issues/2996)  which also points to this behavior on a Power9 processor.
For CUDA this behavior is not described in the official documentation.

## The problem:

Since our allocation and the pinning is independent we have no way to guarantee that we fulfill the allocation conditions (one allocation per cache-line for pinned memory).

## Possible Solutions

- extent the allocation interface and add the possibility to define that memory must be aligned and consume at least a full cache-line
  - this also requires that we can create pinned cpu buffer
- align each allocation to the cache-line size and consume at least a full cache-line
  - this can be negative for the performance if the user needs many small allocations

Please provide ideas since we need to solve this issue: @ComputationalRadiationPhysics/alpaka-developers

**Comment by psychocoderHPC** [comment]
Cache line size on x86 systems (my laptop):
```
cat /sys/devices/system/cpu/cpu0/cache/index0/coherency_line_size
64
```

Cache line size on Summit Power 9:
```
cat /sys/devices/system/cpu/cpu0/cache/index0/coherency_line_size
128
```

**Comment by BenjaminW3** [comment]
I am not yet sure which allocations you mean.
My suspicion is that you are talking about the allocations done within `BufCpu`, `BufCudaRt` and `BufHipRt`. Is this correct?

**Comment by psychocoderHPC** [comment]
Yes I mean the allocations used within the Buffers. For `BufCpu` we use ` AllocCpuBoostAligned`.

**Comment by BenjaminW3** [comment]
So for the CPU the allocations already are aligned (at least as far as this is possible). They still can be too small but we can work around this by inserting a `std::max(calculatedSize, cacheLineSize)` where `cacheLineSize` is device specific. `BufCpu` already knows the device so it should be easy to get this value.

**Comment by psychocoderHPC** [comment]
> `std::max(calculatedSize, cacheLineSize)`

Yes this is possible but I am not sure about the side effects if a user is using a lot of small allocations.
Never the less I would say this is maybe the best way.

**Comment by PrometheusPi** [comment]
@psychocoderHPC On taurus ml it is the same: `cat /sys/devices/system/cpu/cpu0/cache/index0/coherency_line_size` returns 128 while on all other nodes it returns 64.

**Comment by psychocoderHPC** [comment]
I remove the label `Backend-OpenMP` and add `Backend-CUDA` when I know that CUDA is also effect (what I expect)

**Comment by psychocoderHPC** [comment]
I checked 64byte alignment on X86 with a P100 based on [this](https://github.com/ComputationalRadiationPhysics/picongpu/issues/2996) bug we had in PIConGPU.
64byte alignment is not solving the issue. If I use 4kiB alignment (should be the default page size in linux) all works fine.

I checked some [older documentation for cudaHostRegister](http://horacio9573.no-ip.org/cuda/group__CUDART__MEMORY_g36b9fe28f547f28d23742e8c7cd18141.html) and it says

```
The pointer ptr and size must be aligned to the host page size (4 KB).
```

[New CUDA documentation](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY.html#group__CUDART__MEMORY_1ge8d5c17670f16ac4fc8fcb4181cb490c) is saying nothing about any alignment.

**Comment by BenjaminW3** [comment]
Maybe this depends on the used OS?
We can use 4k alignment but this will increase the virtual memory usage.

**Comment by psychocoderHPC** [comment]
I think the clean solution without guessing is to use `cudaMallocHost` as soon as cuda or hip is used for all alpaka buffers. 
@BenjaminW3 is there any point against doing it this way?

**Comment by psychocoderHPC** [comment]
I will try again if we can work with a bigger alignment because I am not happy with using always `cudaMallocHost`. I wrote a short test to detect the minimal alignment needed:

```C++
#include <iostream>
#include <algorithm>
#include <cuda.h>
#include <vector>
#include <limits>

int main()
{

   std::vector<uint8_t*> ptrs(100, nullptr);

   for(auto& p : ptrs)
   {
        cudaMallocHost(&p, 1);
        //std::cout<<reinterpret_cast<size_t>(p)<<std::endl;
   }

   size_t distance = std::numeric_limits<size_t>::max();

   for(size_t i = 0u; i < ptrs.size(); ++i)
   {
      const auto addr = reinterpret_cast<size_t>(ptrs[i]);
      for(size_t j = 0u; j < i; ++j)
      {
        const auto addr2 = reinterpret_cast<size_t>(ptrs[j]);
        auto min_val = std::min(addr, addr2);
        auto max_val = std::max(addr,addr2);
        distance = std::min(distance, max_val-min_val);
      }
   }
   std::cout<< "distance:" << distance <<std::endl;

   return 0;
}
```


Linux page size on both systems was: 4kib (`getconf PAGE_SIZE`) on X86 System:
- CUDA 8 - 10.2 = 512 byte
- HIP-clang        =  8192 byte

Linux page size on both systems was: 64kib (`getconf PAGE_SIZE`) on Power9+ System:
- CUDA 10.1 = 512byte

**Comment by psychocoderHPC** [comment]
Note: The CUDA example [simple stream](https://github.com/pathscale/nvidia_sdk_samples/blob/97c19db8af026f4f86821b19e0252858ca0a1fcc/simpleStreams/0_Simple/simpleStreams/simpleStreams.cu#L75-L76) is also aligning memory to 4kib together with `cudaHostRegister()`

**Comment by psychocoderHPC** [comment]
I will implement that we align all host memory to 4kiB for cuda/HIP(nvcc)  and to the cache line size for HIP(clang/hcc).

4kib is the only size where the debugger now cray about memory access if we not use cudaMallocHost to allocate host side memory.
