### ISSUE TITLE
Update library structure

### ISSUE THREAD

**Issue by j-stephan** [alpaka-group/alpaka#875]
The documentation's [library structure](https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/doc/markdown/user/implementation/library/structure.svg) still uses some outdated concepts. I'll submit a PR with a fix once my thesis is finished (~ couple of days) unless someone gets to it first.

**Comment by sbastrakov** [comment]
@j-stephan not sure if you have time now, in this case just a friendly reminder.

**Comment by j-stephan** [comment]
Thanks for the reminder! I submitted my thesis last week, I'll look into this tomorrow.

**Comment by sbastrakov** [comment]
Great, thanks in advance @j-stephan !
