### ISSUE TITLE
Failing travis CI build with current develop

### ISSUE THREAD

**Issue by sbastrakov** [alpaka-group/alpaka#891]
I mean the one displayed in the readme just after the title.

**Comment by PrometheusPi** [comment]
Looks to me like a few failed downloads. Since I have no rights to restart the alpaka TravisCI, could someone please restart the few failed tests.

**Comment by BenjaminW3** [comment]
The builds are flaky.

I never get a fully green build at the first run. I always have to go to the build and re-run failing builds.
Most of the time there are issues with the CUDA download or apt installations or similar things. We already try to use `travis_retry` to make those network dependent things less flaky but it does not help for every issue. Now that our build matrix consists of ~90 different jobs it i much more likeley to hit at least one such issue.
For PRs someone wants to get the build green and reruns the specific jobs but nobody is looking at the develop build after merging.

**Comment by BenjaminW3** [comment]
Feel free to add `travis_retry` when you find a place where it is missing. I will close the ticket for now as there is nothing we can do about the flaky infrastructure.
