### ISSUE TITLE
doxygen still says LGPL

### ISSUE THREAD

**Issue by jeffhammond** [alpaka-group/alpaka#898]
http://computationalradiationphysics.github.io/alpaka/:
> Software License
> alpaka is licensed under LGPLv3 or later.

https://github.com/ComputationalRadiationPhysics/alpaka:
> Software License
> alpaka is licensed under MPL-2.0.

This ambiguity is worth resolving, even if it is pretty obvious from https://github.com/ComputationalRadiationPhysics/alpaka/issues/637 what the current license is.

**Comment by BenjaminW3** [comment]
The currently deployed doxygen reference documentation is for the 0.3.* release branch which was still LGPL licensed. It will get updated once we release the next major 0.4.0 release.

**Comment by BenjaminW3** [comment]
I updated the doxygen documentation with the code from version 0.4.0
