### ISSUE TITLE
ApplyTuple: Returned Value Lifetime

### ISSUE THREAD

**Issue by ax3l** [alpaka-group/alpaka#912]
https://lgtm.com/projects/g/ComputationalRadiationPhysics/alpaka/?mode=list

The `invoke_impl` implementation detail of `meta::ApplyTuple` creates a warning on LGTM of the form:
```
May return stack-allocated memory from pmd.
```

What does this mean:
- https://lgtm.com/rules/1507923806246/
- occurrence: [`include/alpaka/meta/ApplyTuple.hpp` line 40](https://github.com/ComputationalRadiationPhysics/alpaka/blob/9811f23a306a731342bed038b5af7e5494310f20/include/alpaka/meta/ApplyTuple.hpp#L40)

**Comment by BenjaminW3** [comment]
The code is based on an [old version of the example implementation of std::invoke from cppreference](https://en.cppreference.com/mwiki/index.php?title=cpp/utility/functional/invoke&oldid=74766).
I am not really sure if this is a false-positive.

**Comment by bernhardmgruber** [comment]
It looks like a false positive to me. The member pointer `pmd` is used to retrieve the data member, and is not returned from the function. And since `ref` is passed as a forwarding reference, the returned value cannot dangle after the function call completes.

**Comment by j-stephan** [comment]
`ApplyTuple` was removed as part of #1493. Feel free to reopen if this problem persists even with `std::apply`.
