### ISSUE TITLE
Omp2Blocks does throw runtime error with `OMP_NUM_THREADS=1`

### ISSUE THREAD

**Issue by bertwesarg** [alpaka-group/alpaka#922]
Since #733, it is not possible anymore to run the `Omp2Blocks` backend with `OMP_NUM_THREADS=1`.

**Comment by BenjaminW3** [comment]
I was able to reproduce this. I will try to create a fix.

**Comment by BenjaminW3** [comment]
When do ou need an official release with this fix?
I already created a `release-0.4.1` branch with this fix and the version increment in it.

**Comment by bertwesarg** [comment]
I don't need a release. For SPEC we use the OP4 branch anyway.
