### ISSUE TITLE
bufferCopy example failed using GPU-HIP-clang support

### ISSUE THREAD

**Issue by saipavankalyan** [alpaka-group/alpaka#930]
I'm building alpaka on AMD GPU using HIP-clang. The configuration I'm using is
ALPAKA_ACC_CPU_B_SEQ_T_SEQ_ENABLE_DEFAULT OFF
ALPAKA_ACC_CPU_B_SEQ_T_THREADS_ENABLE_DEFAULT OFF
ALPAKA_ACC_CPU_B_SEQ_T_FIBERS_ENABLE_DEFAULT OFF
ALPAKA_ACC_CPU_B_TBB_T_SEQ_ENABLE_DEFAULT OFF
ALPAKA_ACC_CPU_B_OMP2_T_SEQ_ENABLE_DEFAULT OFF
ALPAKA_ACC_CPU_B_SEQ_T_OMP2_ENABLE_DEFAULT OFF
ALPAKA_ACC_CPU_BT_OMP4_ENABLE_DEFAULT OFF
ALPAKA_ACC_GPU_HIP_ENABLE ON
ALPAKA_ACC_GPU_HIP_ONLY_MODE ON
ALPAKA_HIP_PLATFORM clang
ALPAKA_ACC_GPU_CUDA_ONLY_MODE OFF
ALPAKA_ACC_GPU_CUDA_ENABLE OFF

I have built the application successfully except discarding reduce example for which I have raised this [issue](https://github.com/ComputationalRadiationPhysics/alpaka/issues/929).

vectorAdd, helloWorld, helloWorldLambda are working fine using GPU. But bufferCopy  is failing as memory access fault

Error log:
```
Memory access fault by GPU node-2 (Agent handle: 0x15c7330) on address 0x7ffcb2d9f000. Reason: Page not present or supervisor privilege.
Aborted (core dumped)
```

I have set the following options to identify the issue.
export HCC_SERIALIZE_KERNEL=0x3 
export HCC_SERIALIZE_COPY=0x3 
export HIP_TRACE_API=0x7 
 and found that
 
`void alpaka::kernel::hip::detail::hipKernel<std::integral_constant<unsigned long, 3ul>, unsigned long, FillBufferKernel, unsigned int*, alpaka::vec::Vec<std::integral_constant<unsigned long, 3ul>, unsigned long> >(int, alpaka::vec::Vec<std::integral_constant<unsigned long, 3ul>, unsigned long>, FillBufferKernel, unsigned int*, alpaka::vec::Vec<std::integral_constant<unsigned long, 3ul>, unsigned long>)` 
this kernel is causing the issue but unable to figure out what inside the kernel is causing the issue.

**Specifications:**
OS: Ubuntu 18.04
HIP version: 3.1.20054-66678b01
clang version 11.0.0
cmake version 3.16.4
ROCm Version: 3.0.6
 
Edit(tdd11235813): fixed issue url

**Comment by sbastrakov** [comment]
Thanks for reporting @saipavankalyan , we will have a look on this one.

**Comment by tdd11235813** [comment]
https://github.com/ComputationalRadiationPhysics/alpaka/blob/ceead8c719a5697c5891dbed57a91036e96cabdd/example/bufferCopy/src/bufferCopy.cpp#L172

this cannot be replaced with the HIP accelerator, it must be kept as CPU something. HIP backend probably can be relaxed now to allow this, see #929.

**Comment by saipavankalyan** [comment]
Thanks for the help @tdd11235813 !
