### ISSUE TITLE
Windows+CUDA CI builds broken

### ISSUE THREAD

**Issue by BenjaminW3** [alpaka-group/alpaka#931]
Travis updated the Windows images from version 1803 to 1809.
This broke the Windows+CUDA CI builds.

**Comment by j-stephan** [comment]
I'm wondering if this can be fixed with the CMake [`MSVC_RUNTIME_LIBRARY`](https://cmake.org/cmake/help/v3.15/prop_tgt/MSVC_RUNTIME_LIBRARY.html) property.

**Comment by BenjaminW3** [comment]
I am currently trying this out.

**Comment by BenjaminW3** [comment]
For now the issue is fixed by setting `cmake_policy(SET CMP0091 OLD)` in #953.
