### ISSUE TITLE
remove IDE specifics from .gitignore

### ISSUE THREAD

**Issue by psychocoderHPC** [alpaka-group/alpaka#936]
Based on the [comment  from](https://github.com/ComputationalRadiationPhysics/alpaka/pull/935#issuecomment-590409908) @bertwesarg we should think about cleaning up `.gitignore`

This issue is for collecting argument for cleaning up `.gitignore` or keep the IDE specific exclusions.

**Comment by psychocoderHPC** [comment]
I can only speak for myself but I do not configure my git environment on all systems I work with.
I  use for quick tests often not configured systems where I am happy that I not see all tmp files when I run `git diff` to compare my current changes with the last commit.

I am against cleaning up `.gitignore` to keep my dirty workflows on the 7+ systems I working on.

**Comment by ax3l** [comment]
I also [cannot follow his argument](https://github.com/alpaka-group/alpaka/pull/935#issuecomment-590432657).

There is a reason why GitHub provides `.gitignore` templates for projects, also adding the IDE files our developers use is just nice and does not harm in any way.

**Comment by bertwesarg** [comment]
> I can only speak for myself but I do not configure my git environment on all systems I work with.

But you do setup your editor, right?

> I use for quick tests often not configured systems where I am happy that I not see all tmp files when I run `git diff` to compare my current changes with the last commit.

Since when does `git diff` shoes you untracked files?

**Comment by j-stephan** [comment]
What exactly would we achieve doing this? Other than a `.gitignore` with fewer lines, that is.

**Comment by BenjaminW3** [comment]
As this topic was a poll and I see 3 votes for keeping the current state and only 1 for removing entries from the `.gitignore`, I will close this now.
