### ISSUE TITLE
Upgrade documentation

### ISSUE THREAD

**Issue by tdd11235813** [alpaka-group/alpaka#943]
The possible workflow pieces:

#### Initial pull request
- Integrate .md files into sphinx/readthedocs pipeline, readthedocs.yml etc.
- Convert from .md to .rst ( [md-vs-rst](https://eli.thegreenplace.net/2017/restructuredtext-vs-markdown-for-technical-documentation/), tl;dr: writing => md, software project => rst)
  - there are converters, not tested yet

#### Upgrade pull request(s)
- Update/Refactor documentation
  - include examples and getting-started guide
  - include doxygen documentation
  - ...

I reserved https://alpaka.readthedocs.io/, we can pass/extend the maintenance to CRP group later on.
Please add any ToDo's or feedback here about the documentation upgrade.

Refs: 
- https://picongpu.readthedocs.io/en/latest/dev/sphinx.html
- https://github.com/readthedocs/readthedocs.org
- https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html

**Comment by ax3l** [comment]
Yes, ideally convert all of them to `.rst` and make a sphinx doc out of it, as in our other projects :)

**Comment by SimeonEhrig** [comment]
Some points for the getting-started guide
- install alpaka
  - from source
  - spack (when it is done)
  - ... (maybe conda)
- add alpaka to the cmake of your project
  - enable backends
  - ALPAKA_ADD_EXCUTEABLE
  - ALPAKA_ADD_LIBRARY

Later, there should also be a detailed section about the `cmake` config.
And a section on how to use Alpaka downstream without CMake (config include helpers).

**Comment by bernhardmgruber** [comment]
What still needs to be done here? The documentation moved to reStructuredText a long time ago. Is hit issue done?

**Comment by SimeonEhrig** [comment]
The infrastructure is updated some times ago but the content is the old one, basing on Benjamin's master thesis. This is not really user friendly, also not the structure of the documentation. But this is not part of the issue.
