### ISSUE TITLE
Cmake switch for -Werror

### ISSUE THREAD

**Issue by jkelling** [alpaka-group/alpaka#958]
Is there a way to have a cmake switch to disable the -Werror compiler flag?

There are two reasons for this request:
1. The OpenMP4 backend triggers compiler warnings in clang about types note possibly being not mappable which might be technically correct, but  ultimately are pointless an cannot be avoided. In current clang releases, these could be turned off only with a flag that would also disable all other openmp (offload?) warnings, thus should not be done globally. Clang 11 introduces `-Wopenmp-mapping`. The problem with that hard-coded -Werror is thus, that while the code (examples/tests) can only be compiled without it, when point compiler vendors to the alpaka source, they would first get the warning elevated to an error.
The OpenMP4 backend in the develop branch also triggerst this warning my mapping `boundKernelFnObj`, which would actually not work if offloading were requested.
2. Convenience when debugging backends.

**Comment by BenjaminW3** [comment]
`-werror` is currently automatically enabled when building the tests/examples. There is not yet a CMake option to disable `-werror` but it should be possible to add such an option easily.

**Comment by bernhardmgruber** [comment]
I would generally remove `-Werror` and only add it back via `CXX_FLAGS` in the CI. Reasons are given here: https://embeddedartistry.com/blog/2017/05/22/werror-is-not-your-friend/. We could also have a cmake switch, but in the end this is about the same work as setting `CXX_FLAGS`. If we have the cmake switch I would also like to have it turned off by default.

**Comment by psychocoderHPC** [comment]
I agree that strict checks should only be enforced for the CI and there should be a CMake flag to test the same behavior on local systems.
