### ISSUE TITLE
`make install` should not build examples and tests

### ISSUE THREAD

**Issue by SimeonEhrig** [alpaka-group/alpaka#960]
When I run the expected install workflow:

```bash
mkdir build 
cd build
cmake ..
make install
```

Alpaka builds the examples and the test cases. This is not necessary for an install and takes some time. In some cases, like mine, it can crash with an out-of-memory exception, which should be avoided.

Current solution is to run `cmake .. -Dalpaka_BUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF`, but should be changed to `cmake ..` and for development it should changed to `cmake .. -Dalpaka_BUILD_EXAMPLES=ON -DBUILD_TESTING=ON`.

**Comment by psychocoderHPC** [comment]
We had a longer discussion about it in #942 . If testing is enabled by default depends on the project.  
At all the alpaka install needs some refactoring but @j-stephan is currently under high working load with the alpaka workshop preparation :-(

**Comment by SimeonEhrig** [comment]
I talked with Jan yesterday. He means open an Issue ;-)
I think, this topic is important for the workshop, but we can discuss it at the VC at the afternoon.

**Comment by j-stephan** [comment]
This can be closed now, there is a fix in #1016.

**Comment by SimeonEhrig** [comment]
@j-stephan Nice work. You just forgot to update the documentation. I already created a pull request: #1023
