### ISSUE TITLE
find_package(alpaka) example

### ISSUE THREAD

**Issue by SimeonEhrig** [alpaka-group/alpaka#961]
Is there an Alpaka example which can build out-of-source? I want to integrate Alpaka in my application, but I haven't found an example with a helpful `CMakeLists.txt`, because the Alpaka examples and tests are designed for in-source builds.

**Comment by sbastrakov** [comment]
Do you mean cmake out-of-source / in-source builds, or usage outside of Alpaka? I thought for cmake Alpaka only supports out-of-source. In case you meant the latter, this is a good point. Btw in the private workshop example repo (link was in mattermost, will send you there) I made a very simple example outside of Alpaka directory. This is really rudimentary, but can be a start.

**Comment by SimeonEhrig** [comment]
`Out-of-source` and `in-source` are not good terms, so I give an example, what I want to do.

# Install Alpaka on system Level or in environment
``` bash
git clone https://github.com/ComputationalRadiationPhysics/alpaka.git
mkdir build && cd build
cmake ../alpaka -Dalpaka_BUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF
make install # for example, install to /usr/local
```
# Building the projekt

CMakeLists.txt
```cmake
cmake_minimum_required(VERSION 3.14)
project(test)

find_package(alpaka REQUIRED)

alpaka_add_executable(test test.cpp)
target_link_libraries(
    test
    PUBLIC alpaka::alpaka)
```

build project and run executeable:
```bash
cd to/project
mkdir build && cd build
cmake .. 
make
./test
```

My `CMakeLists.txt` works for a simple case at the moment, but I'm note sure, if this is correct.

**Comment by sbastrakov** [comment]
I am really not an expert in this, but to me it looks okay. Except you are building your example ïn cmake "in-source" fashion, and maybe the `build` directory should be one level higher, outside of your project directory.

**Comment by SimeonEhrig** [comment]
Okay, now I understand, where is the misunderstanding. I used the terms wrong.
What I want to do, is not to put the Alpaka Source Code in my project and use a relative path. I want to install Alpaka on system level and use `find_package`.

The source of my wrong usage of the terms is the LLVM library, where I develop for. It has a special folder called `tools`. If you put your code in, the `CMakeLists.txt` of LLVM will recognize it and build your tool together with LLVM library. The LLVM dependencies are resolved automaticity. They name it in-source build. If you use `find_package(llvm)` for your tool, to use a default installation of LLVM, they name it out-of-source build.

**Comment by sbastrakov** [comment]
Ah, I see, thanks for clarifications.

**Comment by j-stephan** [comment]
Can this be closed? The workshop examples show how to use `find_package(alpaka)`.

**Comment by SimeonEhrig** [comment]
I think we can close it. Integrating the workshop documentation in clever way is another issue.

@j-stephan can you provide the link to the slide, just for documentation in this issue?

**Comment by j-stephan** [comment]
Sure. See the [Hello World](https://github.com/alpaka-group/alpaka-workshop-examples/blob/200629_cern/helloWorld/CMakeLists.txt) example.

**Comment by SimeonEhrig** [comment]
I'm stupid. I thought the `add_subdirectory` example was missing. I mixed two issues in my mind. A `find_package` example is also available in Sphinx Docs. Anyway, thanks for the link.
