### ISSUE TITLE
alpaka repository ownership transfer

### ISSUE THREAD

**Issue by psychocoderHPC** [alpaka-group/alpaka#968]
The owner ship of the alpaka repository will be transfered on 3rd April to https://github.com/alpaka-group. It could be that the CI will be offline for a short time period.

This will change the link to the repository to https://github.com/alpaka-group/alpaka. 

@ComputationalRadiationPhysics/alpaka-maintainers @ComputationalRadiationPhysics/alpaka-developers

**Comment by sbastrakov** [comment]
Is cupla being transfered to that group as well?

**Comment by ax3l** [comment]
I think that makes sense, yes!
(I would long-term even suggest to integrate cupla into alpaka as a high-level library/include functionality.)

**Comment by psychocoderHPC** [comment]
> Is cupla being transfered to that group as well?

Sry for the late response. Yes the repo will be transferred too

**Comment by psychocoderHPC** [comment]
@alpaka-group/alpaka-developers Please check that you have still all  access rights to settings and CO as before.

**Comment by BenjaminW3** [comment]
My rights on the alpaka repository seem to be limited. At least the settings menu cotains much much less options.

**Comment by psychocoderHPC** [comment]
@BenjaminW3  please try now again

**Comment by BenjaminW3** [comment]
works, thanks!

**Comment by psychocoderHPC** [comment]
The repo is transferred. Therefore I will close this issue

**Comment by ax3l** [comment]
Repo rights already work, thanks.
I've membership but no ownership of the https://github.com/alpaka-group org.
Maybe also give Benjamin ownership of the new org, to reduce the bus factor.

**Comment by psychocoderHPC** [comment]
> Repo rights already work, thanks.
> I've membership but no ownership of the https://github.com/alpaka-group org.
> Maybe also give Benjamin ownership of the new org, to reduce the bus factor.

done

**Comment by ax3l** [comment]
Awesome, please don't forget to set your membership status to "public" everyone :)
https://github.com/orgs/alpaka-group/people

**Comment by erikzenker** [comment]
done
