### ISSUE TITLE
Support for gcc 8 + CUDA backend?

### ISSUE THREAD

**Issue by sbastrakov** [alpaka-group/alpaka#983]
This question popped up during the call with a workshop team. The table does not list this combination as supported. Is the reason that something does not work, or it's just not tested?

**Comment by ax3l** [comment]
Yes you got that right, everything that is listed is tested in CI, according to the note below the table. One can adopt one of the GCC entries in CI to GCC8, which works with [CUDA 10.1 or newer](https://gist.github.com/ax3l/9489132), probably already works.

**Comment by BenjaminW3** [comment]
This is an error in the readme. We already have a test in CI with `nvcc-10.1 + gcc-8`. The problem in the readme is that we have only one column for gcc 8 and 9 combined and gcc 9 is not yet supported by nvcc.
