### ISSUE TITLE
Avoid device synchronization on cudaFree

### ISSUE THREAD

**Issue by BenjaminW3** [alpaka-group/alpaka#987]
See this blog post: https://devblogs.nvidia.com/introducing-low-level-gpu-virtual-memory-management/

**Comment by psychocoderHPC** [comment]
The disadvantage is that this function require the driver API. Currently only the tests in alpaka depends the driver API.
If we implement something like that we need to take care that we are able to build on a system without a CUDA driver. The CUDA driver ships cuda.so. 
On a system without CUDA driver we need to build against `lib/stubs/libcuda.so`. At all it is no big deal but we need to check if our CMake can handle it correctly.

**Comment by fwyzard** [comment]
CUDA 11.2 introduces `cudaMallocAsync` and `cudaFreeAsync` with stream semantic:
  - https://developer.nvidia.com/blog/enhancing-memory-allocation-with-new-cuda-11-2-features/
  - https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY__POOLS.html

**Comment by j-stephan** [comment]
`alpaka::allocAsyncBuf` was implemented for CUDA in #1481 and for HIP in #1894. We now have options for blocking and non-blocking `alloc`/`free` so this can be closed as completed.
