### ISSUE TITLE
remove duplication in compiler flag variables

### ISSUE THREAD

**Issue by psychocoderHPC** [alpaka-group/alpaka#992]
Alpaka appends options to `CUDA_NVCC_FLAGS`, `CMAKE_CXX_FLAGS`, ...
In the case where the user is using a third party library which depends e.g. on CUDA and is also appending `CUDA_NVCC_FLAGS` it could be we pass options multiple times to the compiler.

IMO we should clean (remove duplicated options) `CUDA_NVCC_FLAGS` in our cmake macro `alpaka_add_executable` and `alpaka_add_library`. #991 provides the needs to use `list(REMOVE_DUPLICATES LIST)`

Currently alpaka is [using a workaround ](https://github.com/alpaka-group/alpaka/blob/75ac3af932d8b5d9887bd51318fb3befb12522cc/cmake/alpakaCommon.cmake#L461) for duplicated flags in `CUDA_NVCC_FLAGS` by removing the previous state.
The workaround as the issue that all flags provided by a third party cmake module will be removed when those are processed by cmake before alpaka.

I opened this PR for discussions about side effects I maybe missed if we fix the above described issues by using `list(REMOVE_DUPLICATES LIST)`

CC-ing: @alpaka-group/alpaka-maintainers

**Comment by BenjaminW3** [comment]
@psychocoderHPC Do you still want to do something in alpaka about this?

**Comment by psychocoderHPC** [comment]
Yes, to avoid side effects with other libraries but due to much work this has a low priority on my todo list.

**Comment by ax3l** [comment]
Ideally, Alpaka does not add/modify to `CMAKE_...` flags unless it's the root CMake project.

With CUDA, luckily the next release will allow to set device link flags on targets and potentially also add Clang CUDA support, so we should be able to get rid of many hacks.

**Comment by j-stephan** [comment]
The way we handle CUDA has changed over the past months. Is this still an issue?

**Comment by j-stephan** [comment]
AFAIK we are assigning all flags to targets in our current CMake build system. This way CMake de-duplicates the flags by default. I'm closing this as completed; feel free to reopen if you think this still matters.
